### ISSUE TITLE
Is it possible to connect to a specific device?

### ISSUE THREAD

**Issue by kamikhanz** [boskokg/flutter_blue_plus#100]
Hi,

is it possible to connect to a specific device by MAC address, without scanning, sometimes my device doesn't appaer and its frustrating to scan everytime to get the device. BluetoothDevice constructor maybe?

**Comment by boskokg** [comment]
Yes, you can do it like this:

        protos.BluetoothDevice dev = protos.BluetoothDevice()
          ..remoteId = address;
        _bleDevice = BluetoothDevice.fromProto(dev);
