### ISSUE TITLE
Android notify issue

### ISSUE THREAD

**Issue by shukiTSP** [boskokg/flutter_blue_plus#101]
I have a problem with notify in android. It works well until I send specific command (length 27 bytes), in IOS it works well, but in Android when I send that command it doesn't get any response.

It happened also in some other commands, they're also larger than 20 bytes and I made a workaround by disconnect and connect again to device but I don't feel safe doing that every time. Seems like something is cached in android.

So can anybody help ?

**Comment by hiraokashi** [comment]
I met that problem too.

**Comment by shukri04** [comment]
@hiraokashi if you find any solution please tell me.
