### ISSUE TITLE
Device not found after build android

### ISSUE THREAD

**Issue by hiroppi401** [boskokg/flutter_blue_plus#103]
When on debug its no problem, but on build apk device not found
please guide me

**Comment by ertandagdelen** [comment]
try with this;
flutter build apk --no-shrink

**Comment by ioaccept** [comment]
Add this to your build.gradle in your android folder

    buildTypes {
        release {
            signingConfig signingConfigs.release
            shrinkResources false
            minifyEnabled false
        }
    }

**Comment by hiroppi401** [comment]
thanks guys, it fixed
