### ISSUE TITLE
v1.3.0 truncates manufacturerData in advertisement on ios

### ISSUE THREAD

**Issue by colin-lear-at-vetchip** [boskokg/flutter_blue_plus#111]
Just noticed that my ids are 2 bytes short.

Probably related to: https://github.com/boskokg/flutter_blue_plus/issues/92 which I think has already been reverted.

However the latest version 1.3.0 still has this issue on ios.

I have reverted back to 1.1.3 for the moment.

**Comment by Time-L** [comment]
俺也一样

**Comment by Time-L** [comment]
i also,Please put it back together as soon as possible

**Comment by boskokg** [comment]
1.3.1 is released with reverted code regarding this issue.
Thanks for reporting
