### ISSUE TITLE
ConnectedDevices.asStream() is not Stream'in

### ISSUE THREAD

**Issue by lloydrichards** [boskokg/flutter_blue_plus#112]
Greetings, we're working currently on rebuilding our Flutter App with the new FlutterBluePlus, and have run into some issues when trying to stream the state of BLE.

```
override
  Stream<bool> checkBtIsAvailable() =>
      flutterBlue.isAvailable.asStream().asBroadcastStream();

  @override
  Stream<bool> checkBtIsOn() => flutterBlue.isOn.asStream().asBroadcastStream();

  @override
  Stream<bool> checkBtIsScanning() =>
      flutterBlue.isScanning.asBroadcastStream();
  @override
  Stream<List<BluetoothDevice>> checkBtConnectedDevices() =>
      flutterBlue.connectedDevices.asStream().asBroadcastStream();

  @override
  Stream<List<ScanResult>> checkBtScanResults() => flutterBlue.scanResults
      .asBroadcastStream()
      .map((e) => e.where((i) => i.advertisementData.connectable).toList())
      .map((e) => e.where((i) => i.advertisementData.localName != "").toList())
      .map((e) => e..sort((a, b) => b.rssi.compareTo(a.rssi)));

  @override
  Stream<ScanResult> scan() => flutterBlue
      .scan(timeout: const Duration(seconds: 20))
      .asBroadcastStream();
}
```

Currently only the .isScanning seems to function correctly and update the UI when the scanning state changes.  For the .isOn, .isAvailable, and .connectedDevices I have to re trigger the .listen() in order to get the current state.

Is it possible to have the state act as a proper stream of the state? Or will I need to set some kind of timer to refresh every few seconds?

**Comment by Jbz797** [comment]
I have the same problem I can't turn the `connectedDevices` Future into stream.
