### ISSUE TITLE
Where can I get information on how to use this plugin.

### ISSUE THREAD

**Issue by davidAg9** [boskokg/flutter_blue_plus#115]
I am a fairly new to bluetooth technology , I will like to connect to other bluetooth mobile device ask them about about some info and also send data to them so they do something on that data . How do I achieve this and , I would like someone to point me to documentation or any sort of resource I could use.Thank you.

**Comment by Silhouette2022** [comment]
[566988](https://pub.dev/packages/flutter_blue_plus)

**Comment by Silhouette2022** [comment]
> I am a fairly new to bluetooth technology , I will like to connect to other bluetooth mobile device ask them about about some info and also send data to them so they do something on that data . How do I achieve this and , I would like someone to point me to documentation or any sort of resource I could use.Thank you.

https://pub.dev/packages/flutter_blue_plus

**Comment by davidAg9** [comment]
I have no idea what any of the terminologies  mean...such MTU , characteristics , descriptor ... is there anywhere I can find out where to read on these terminologies and what they are .

**Comment by Silhouette2022** [comment]
> 
https://learn.adafruit.com/introduction-to-bluetooth-low-energy?view=all
https://www.google.com/search?q=bluetooth+low+energy+tutorial
