### ISSUE TITLE
[iOS] OS dialog when bluetooth is turned off (for new connections)

### ISSUE THREAD

**Issue by ChristianNavolskyi** [boskokg/flutter_blue_plus#119]
I want to check whether bluetooth is turned on or off. For that I listen to the `FlutterBluePlus::state` stream and check for `BluetoothState.on` or `BluetoothState.off`.

But when I do that check and Bluetooth is turned (semi) off via control panel I get the dialog as in this [StackOverflow post](https://stackoverflow.com/questions/58600502/what-causes-this-ios-permission-prompt-for-use-bluetooth-for-new-connections).

I tried to set the [recommended option](https://developer.apple.com/documentation/corebluetooth/cbcentralmanageroptionshowpoweralertkey) in [`FlutterBluePlusPlugin.m`](https://github.com/boskokg/flutter_blue_plus/blob/master/ios/Classes/FlutterBluePlusPlugin.m#L72) but the dialog still popped up.

Is it possible to avoid that dialog from popping up?

**Comment by methompson** [comment]
I think this issue can easily be solved by this PR: https://github.com/boskokg/flutter_blue_plus/pull/114

Even if this solution isn't your preferred method, we can at least add the lines to FlutterBluePlusPlugin.m:

```
if (self.centralManager == nil) {
  NSDictionary *options = [NSDictionary dictionaryWithObjectsAndKeys:[NSNumber numberWithBool:NO], CBCentralManagerOptionShowPowerAlertKey, nil];
  self.centralManager = [[CBCentralManager alloc] initWithDelegate:self queue:nil options:options];
}
```

This would prevent the popup from showing whenever the application attempts to learn the status of BT.
