### ISSUE TITLE
in Android 12 some beacon devices can not be found

### ISSUE THREAD

**Issue by erahani** [boskokg/flutter_blue_plus#120]
in Android 12 some beacon devices can not be found using this package.
I checked ScanResult device.name and it is empty for many scanned devices on Android 12. it works on iOS.
I also tried with some third-part apps like light blue and BLE scanner.  BLE scanner can not find it (while it can find same beacons in iOS app). light blue can find it on Android 12 and ios. I appreciate for any help.

**Comment by navaronbracke** [comment]
The fact that some beacons can not be found on Android 12 is mentioned in the documentation here:
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location

```
Note: If you include neverForLocation in your android:usesPermissionFlags, some BLE beacons are filtered from the scan results.
```

The plugin does set `neverForLocation` in its manifest.

**Comment by erahani** [comment]
Thanks for your reply:
i added this line but did not help. then I manually changed Location App permission to "Allow.." and it worked. not sure how I can avoid manual set of location.
<uses-permission android:name="android.permission.BLUETOOTH_SCAN"
        tools:remove="android:usesPermissionFlags"/>
