### ISSUE TITLE
Changes to Bluetooth 5.0 compability

### ISSUE THREAD

**Issue by wldeveloperapps** [boskokg/flutter_blue_plus#121]
Hi, who wants to use this plugin with bluetooth 5.0 and all the legacy PHY :+1: :

1.- Use target Api  >= 21

2,. Change the ScanSettings to:

 ScanSettings settings = **new** ScanSettings.Builder().setLegacy(**false**).setPhy(255).setScanMode(scanMode).build();

**Comment by JP3871** [comment]
Hi wldeveloperapps,

Can you give me a example where to initialize this code:
 ScanSettings settings = new ScanSettings.Builder().setLegacy(false).setPhy(255).setScanMode(scanMode).build();

Thanks
