### ISSUE TITLE
[Android] Location permission automatically added

### ISSUE THREAD

**Issue by ChristianNavolskyi** [boskokg/flutter_blue_plus#122]
When including this package the `location` and `nearby devices` permissions are automatically added (probably because they are listed in the android manifest of this plugin).

As stated in the readme the app using this plugin should declare the necessary permissions in the app manifest. In my case, I really don't use the location functionality and therefore would like the permission to **not** appear in the app settings. 

I would assume that it is my task to set the necessary permissions and this plugin should leave me the options to not specify the ones I don't use.

Would it make sense to remove the permissions from [`AndroidManifest.xml`](https://github.com/boskokg/flutter_blue_plus/blob/master/android/src/main/AndroidManifest.xml)?

Or is there another way to not make the permissions appear in the final aab/apk?

**Comment by ChristianNavolskyi** [comment]
Thanks @navaronbracke for the workaround.

Is there a reason why the permissions are added by default? In the README it's also stated, that the permissions should be added into the app's AndroidManifest file.

My case might be an edge case, but it would work straight away if the permissions weren't added by this package.

**Comment by navaronbracke** [comment]
@ChristianNavolskyi I'm not sure why the plugin decided to add the permission flag by default.

And yes, the README should not have mentioned that the permissions should be added by the developer, since the plugin already includes those permissions. Instead the README should mention that the permissions are **already** set by the plugin.

**Comment by EdwardRodr1guez** [comment]
neither using  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" tools:node="remove" />
     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" tools:node="remove" />
     
     in my manifest, I am not still able to avoid the app request me location permission, why???
