### ISSUE TITLE
iOS disconnection after 1 message

### ISSUE THREAD

**Issue by chetan-SMRI** [boskokg/flutter_blue_plus#123]
The iOS code connects successfully with ESP32 and sends messages successfully in android without any auto-disconnection

In iOS it gets disconnected immediately after sending the first message.
```
  writeData(String data) async {
    if (targetCharacteristic == null) return;

    List<int> bytes = utf8.encode(data);
    try {await targetCharacteristic.write(bytes);}
    on Exception catch(e){
      print(e);
    }
  }
```

I sent first message and then it also has a wait for 3 sec. but it still cant send a new message,upon checking log it doesn't show much of info regarding why it happened.

**Comment by Brinfotech1407** [comment]
Any update on this as same thing happened for me as I was able to write one message but after that on connection listener received disconnected status of device.

**Comment by chetan-SMRI** [comment]
Yes, I remember some details of the project.
It was because the byte length supported by iOS is small rather than Android.
I had resolved it. If u will need, I will try to find exact code and send you. But as far as I remeber, I guess I had to shorter the text I was sending

**Comment by Brinfotech1407** [comment]
Thanks @chetan-SMRI for quick response I was looking actually readme where writeLarge extension method is mentioned  if you are referencing to that function then it is fine , otherwise it would be helpful if you send the code , thanks.
