### ISSUE TITLE
on Motorola manufacturer Data is shorter

### ISSUE THREAD

**Issue by GianMen91** [boskokg/flutter_blue_plus#125]
I am facing an issue with a Motorola g22. 
The manufacturer Data is shorter compared to other smartphones I used for testing,  this, unfortunately, contributes to the non-functioning of other features of my app which uses `flutter_ble_plus` to scan BLE devices. Example:

- Motorola: `data = {13: [24, 4, 237, 229, 193, 235]}`
- Samsung Galaxy S21+:  `data = {13: [144, 11, 3, 0, 0, 100, 0, 0, 0, 0, 128, 0, 0, 0, 0, 128, 0, 0, 0, 0, 128, 0, 0, 239, 164, 218, 50, 51, 115, 209]}`

with `data = scanresult.advertisementData.manufacturerData;`

Both devices have Android 12.

Does anyone already face this problem with Motorola devices and know how to solve it?

**Comment by figureai** [comment]
I have this problem on iOS
