### ISSUE TITLE
connectedDevices return empty List

### ISSUE THREAD

**Issue by AhmedAbogameel** [boskokg/flutter_blue_plus#131]
I'm calling this code to get connectedDevices 

`print("connectedDevices ${await flutterBlue.connectedDevices}");`

response is an empty array on android and ios
`flutter: connectedDevices []`

**Comment by narayanvyas** [comment]
I am also facing a similar kind of issue. In my case, I have to call connectedDevices two times after a 1-second delay, and then it works most of the time as usual. Don't know how to resolve this.

**Comment by moazelsawaf** [comment]
@AhmedAbogameel 
Have you found a solution for this one? I am facing the same issue ...

**Comment by Villian95** [comment]
I also have the same question,  have you found a solution for this one?

**Comment by chipweinberger** [comment]
sounds similar to https://github.com/boskokg/flutter_blue_plus/issues/319

please try 1.7.6+, feel free to reopen if you still have problems.
