### ISSUE TITLE
Listener remove

### ISSUE THREAD

**Issue by massimilianochiodi** [boskokg/flutter_blue_plus#133]
is possible remove listener for an characteristic ? 
Plese...

**Comment by navaronbracke** [comment]
@massimilianochiodi Assuming you use the following to listen to changes for a characteristic:
```
await characteristic.setNotifyValue(true);
characteristic.value.listen((value) {
    // do something with new value
});
```

You should instead cancel the `StreamSubscription` that is returned by `listen((value){...})`

I.e.

```
import 'dart:async';

StreamSubscription<List<int>>? subscription;

await characteristic.setNotifyValue(true);
subscription = characteristic.value.listen((value) {
    // do something with new value
});

subscription?.cancel();
```

**Comment by AlexQiulin** [comment]
Very good solution

**Comment by AlexQiulin** [comment]
> @massimilianochiodi Assuming you use the following to listen to changes for a characteristic:
> 
> ```
> await characteristic.setNotifyValue(true);
> characteristic.value.listen((value) {
>     // do something with new value
> });
> ```
> 
> You should instead cancel the `StreamSubscription` that is returned by `listen((value){...})`
> 
> I.e.
> 
> ```
> import 'dart:async';
> 
> StreamSubscription<List<int>>? subscription;
> 
> await characteristic.setNotifyValue(true);
> subscription = characteristic.value.listen((value) {
>     // do something with new value
> });
> 
> subscription?.cancel();
> await characteristic.setNotifyValue(false); // Not sure if this is needed
> ```

good
