### ISSUE TITLE
Document the plugin's behavior of opting into neverForLocation on Android

### ISSUE THREAD

**Issue by navaronbracke** [boskokg/flutter_blue_plus#135]
I wanted to support BLE beacons when scanning for devices.
However the docs mention a caveat:

```
Note: If you include neverForLocation in your android:usesPermissionFlags,
some BLE beacons are filtered from the scan results.
```

The plugin's manifest specifically includes this flag.

I managed to fix that by adding an explicit entry to my Manifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools"
    package="com.example.app"> <!-- needed for the tools annotation below -->

<!-- Override the permission in flutter_blue_plus's manifest with one without the permission flag -->
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" tools:node="replace"/>
```
After adding this to my manifest, the flag is gone from my merged manifest, and the permission itself is still there.

I'd suggest we do one of the following:
1) Remove the `android:usesPermissionFlags="neverForLocation"` flag on the permission in the plugin's manifest
    and redirect people to [the Bluetooth docs](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions)
    This is a breaking change (although not a big one)
2) Inform people that the plugin specifically opts into this flag and it can be removed by adding the permission explicitly with `tools:node="replace"`. The documentation on how this works is [here](https://developer.android.com/studio/build/manage-manifests)

This should fix #120 by providing people with either an opt-in or a clarification on how to _opt-out_, depending of what we  decide to do.

**Comment by tuna-f1sh** [comment]
Thanks for this, saved me from making a fork just to fix this. I got caught by this as using the flutter_beacon plug-in in parallel. Particularly annoying since I read the comment in the example App manifest and thought, 'no, I don't want that flag' not knowing it was set within the plug-ins manifest.

Migration from flutter_blue original was painless other than this...
