### ISSUE TITLE
[Feature]: Package does not have a verified uploader according to Pub

### ISSUE THREAD

**Issue by navaronbracke** [boskokg/flutter_blue_plus#14]
Apparently, the package has an `unverified uploader` according to Pub.

Can we fix that?

Related docs https://dart.dev/tools/pub/verified-publishers

**Comment by boskokg** [comment]
Hi @navaronbracke. Is this needed to anyone? The purpose of flutter_blue_plus is to be maintained by anyone, not only by me... You can see from the changelog that most of the fixes are done by someone else.

**Comment by chipweinberger** [comment]
@boskokg , could you move this package to my verified uploader? I'd love for this FlutterBluePlus to be more legitimate.

https://pub.dev/publishers/jamcorder.com/packages

<img width="560" alt="Screenshot 2023-07-25 at 11 40 33 PM" src="https://github.com/boskokg/flutter_blue_plus/assets/1863934/ddc6cb7f-9e26-44a0-a3bc-7e2b2d1a1cfa">

**Comment by chipweinberger** [comment]
Also, it would be useful to add other github contributers, and to be able to make an issue template.

**Comment by chipweinberger** [comment]
I have added  flutter_blue_plus to my publisher: `jamcorder.com`

https://pub.dev/publishers/jamcorder.com/packages
