### ISSUE TITLE
Unable to connect. Bluetooth cannot be connected after it is turned off during Bluetooth operation

### ISSUE THREAD

**Issue by AlexQiulin** [boskokg/flutter_blue_plus#145]
![image](https://user-images.githubusercontent.com/103996233/193971516-03d5c741-2307-41fb-828c-8c4022173b89.png)

**Comment by massimilianochiodi** [comment]
i solved it by completely removing the library and writing my own for both kotlin and ios.

**Comment by bradintheusa** [comment]
Can you share what you wrote?

**Comment by KimGiay** [comment]
Hi @AlexQiulin ,

I have the same problem.
Do you find a way can resolve this issue?
The workaround can resolve the issue, call the scan() method before start connect to the Bluetooth device.

**Comment by massimilianochiodi** [comment]
> Can you share what you wrote?

https://github.com/massimilianochiodi/androidble

**Comment by AlexQiulin** [comment]
> Can you share what you wrote?

Yes, I will send it to you on the computer tomorrow
