### ISSUE TITLE
I found two serious bugs with this Bluetooth plug-in. I hope the author can solve them when updating it next time

### ISSUE THREAD

**Issue by AlexQiulin** [boskokg/flutter_blue_plus#147]
1：
The first problem is that errors are often reported when finding eigenvalues. Although errors are not always reported, the probability of error is very high
![1](https://user-images.githubusercontent.com/103996233/194867602-f4bc9832-bec2-44aa-bde4-095a18740d96.png)
2：
The third problem is that when the Bluetooth device is normally connected to the APP, manually go to the mobile phone system and turn off Bluetooth. This will cause the Bluetooth device to be disconnected all the time, and cannot be connected even after recompilation, which is very strange.
![3](https://user-images.githubusercontent.com/103996233/194868676-7044172d-c7ba-4d59-98da-2a3a3609a271.png)

If you have corresponding solutions, please advise. Similarly, if you have the same problems, I hope the author can fix these bugs

This is the sample code I wrote：
https://github.com/AlexQiulin/flutter-blue-plus/blob/main/main.dart

**Comment by WeiKuang** [comment]
bad code style

**Comment by ifredom** [comment]
点击开始扫描 startScan()，直接就卡死了  ，
![image](https://user-images.githubusercontent.com/13759936/196891831-acf99aa4-d67f-4b71-9562-c832e0bb27ae.png)

**Comment by sharathltts** [comment]
same issue

**Comment by 971586331** [comment]
The same problem, there were these problems in the previous version 0.8, the strange thing is that it has not been changed, I wonder if there is a problem with the way I use it

**Comment by liyao20190808** [comment]
same issue

**Comment by chipweinberger** [comment]
please try 1.7.6+, feel free to reopen if you still have problems.
