### ISSUE TITLE
Notes on Android12 release APK (Build APK)

### ISSUE THREAD

**Issue by AlexQiulin** [boskokg/flutter_blue_plus#148]
For Android 12, the APK file after the official package (Build APK) release cannot be searched for Bluetooth devices and the system Bluetooth solution cannot be opened
![0](https://user-images.githubusercontent.com/103996233/195054642-fe82f8c1-bc92-433e-9834-81fc9922ed45.png)

**Comment by forte-sama** [comment]
Something related happens to me, a debug build behaves like a charm, in release builds the app fails to discover services on the peripheral device.

**Comment by Calvin-Ho** [comment]
I have just fixed this in my own project.

You can still use `shrinkResources` and `minifyEnabled` as shown here:
```
buildTypes {
        release {
            signingConfig signingConfigs.release

            minifyEnabled true

            shrinkResources true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
but you need to make sure to update your Proguard rules in `android/proguard-rules.pro`:

```
...

# flutter_blue_plus rules
-keep class com.boskokg.flutter_blue_plus.** { *; }
-keepclassmembernames class com.boskokg.flutter_blue_plus.* { *; }
````

This will prevent the classes and relevant members from being minified which means that they can be invoked as normal.

**Comment by kashjack** [comment]
It's working in my case, thank you

**Comment by ChampiMagic** [comment]
I dont have the "proguard-rules.pro" file on me android folder, were can I found it?

**Comment by axelvugts** [comment]
> I dont have the "proguard-rules.pro" file on me android folder, were can I found it?

You have to manually create the file if it doesn't exist yet.

**Comment by svprdga** [comment]
> buildTypes {
>         release {
>             signingConfig signingConfigs.release
> 
>             minifyEnabled true
> 
>             shrinkResources true
> 
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> ```
> 
> but you need to make sure to update your Proguard rules in `android/proguard-rules.pro`:
> 
> ```
> ...
> 
> # flutter_blue_plus rules
> -keep class com.boskokg.flutter_blue_plus.** { *; }
> -keepclassmembernames class com.boskokg.flutter_blue_plus.* { *; }
> ```

Thank you so much for this information.

Without a doubt, this information should appear prominently in the README.md for this plugin.

**Comment by zhaojun1217** [comment]
good issue  , thank every one
i used
-keep class com.boskokg.flutter_blue_plus.** { ; }
-keepclassmembernames class com.boskokg.flutter_blue_plus. { *; }
