### ISSUE TITLE
latformException(startScan, Field androidScanMode_ for m0.e0 not found. Known fields are [private int m0.e0.q, private b3.b0$i m0.e0.r, private boolean m0.e0.s, private static final m0.e0 m0.e0.t, private static volatile b3.a1 m0.e0.u], java.lang.RuntimeException: Field androidScanMode_ for m0.e0 not foun

### ISSUE THREAD

**Issue by jahnli** [boskokg/flutter_blue_plus#15]
![image](https://user-images.githubusercontent.com/20943608/156140128-0c4b2240-e398-48f7-8eb6-3212826e3839.png)

**Comment by jahnli** [comment]
-keep class com.pauldemarko.flutter_blue.** {*;  }, but it doesn't work

**Comment by BWhiteApps** [comment]
I'm having the same issue

**Comment by gregk104** [comment]
The ProGuard line you want to use is:

-keep class com.boskokg.flutter_blue_plus.* { *; }

**Comment by shubhamsinghmutualmobile** [comment]
> The ProGuard line you want to use is:
> 
> -keep class com.boskokg.flutter_blue_plus.* { *; }

This should be in the README ✅
