### ISSUE TITLE
Changes to Bluetooth 5.0 compability

### ISSUE THREAD

**Issue by JP3871** [boskokg/flutter_blue_plus#152]
Hi,

wldeveloperapps wrote:

Hi, who wants to use this plugin with bluetooth 5.0 and all the legacy PHY 👍 :
1.- Use target Api  >= 21

2. Change the ScanSettings to:
ScanSettings settings = ScanSettings.Builder().setLegacy(false).setPhy(255).setScanMode(scanMode).build();

Could you please give me an example of code: how to initialize, import a package ?
Thanks

**Comment by GiovanniRaseraF** [comment]
ScanSettings settings = ScanSettings.Builder().setLegacy(false).setPhy(255).setScanMode(scanMode).build();
this involves the platform specific code in 
android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java, 
i tried to chage it but still no scan results on S9 and S10 
...
I don't know if I'm doing it right
