### ISSUE TITLE
Logging in production mode

### ISSUE THREAD

**Issue by ju851zel** [boskokg/flutter_blue_plus#153]
**Current situation:**

When building an app in debug mode, log messages are printed to the console via the `print()` method.
On release mode no logs are printed.

**Suggestion:**
I would suggest to replace that behaviour by using the dart logging library: [logging](https://pub.dev/packages/logging)
The user can then subscribe to log messages and decide if he/she wants to print them or send them to a logging backend in debug or production.

Would this be a nice feature and would a PR be looked at and eventually be merged?

**Comment by ElreboCM** [comment]
I personally would appreciate it if extensive could be disabled in debug mode. Extensive printing makes the app unresponsive and thus debugging harder.
