### ISSUE TITLE
BluetoothGatt.writeCharacteristic is depreacated in Android API 33

### ISSUE THREAD

**Issue by choim4389** [boskokg/flutter_blue_plus#154]
`BluetoothGatt.writeCharacteristic` seems to be deprecated in latest android api.  ([refer](https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#writeCharacteristic(android.bluetooth.BluetoothGattCharacteristic)))

Is it any plan to cover that issue?

**Comment by sakina1403** [comment]
Thanks for helping me understand why it's failing on Android 13. Suprisingly its deprecated in October and still no update on the plugin :( I am trying to resolve it now, will update.

**Comment by nilsorathiya** [comment]
@sakinaboriwala 
I am having the same issue. can you help me with how I can figure it out?

I was using the Blufi plugin but it is asking for Bluetooth permission every time I open the app and again the main issue is, an outdated version of Blufi.

It will be really helpful if you can help it out!
