### ISSUE TITLE
Request MTU size higher than 23 

### ISSUE THREAD

**Issue by cnrblm** [boskokg/flutter_blue_plus#155]
I am working on samsung galaxy s20fe with android 12 installed. I can receive data via mlt-bt05 as ble module. requestMtu function works when used with 18 but it does not work above 23. I am attaching my code below.

```
await targetDevice.requestMtu(24);
await Future.delayed(const Duration(seconds: 1));
int mtu = await state.targetDevice.mtu.first;
print(mtu); // 23
```

**Comment by Pesta666** [comment]
Thats common issue on Samsung phones, they have broken MTU, phone says it sends data, but never sends. Same for incoming. Samsung knows about this issue, last year solved that problem only in one way, 3 months later broken again and didn't fix until now, from what I know. It also doesn't work on Android 11, even Galaxy S10 lineup, even newer devices... Just don't use larger MTU if you want your app to work on Samsung phones...

**Comment by DaYang816** [comment]
Can iOS change MTU?

**Comment by HyeonJungHam** [comment]
I'm not sure if it would help anyone using Samsung phones, but I found a code snippet from the old library, and confirmed it works (https://github.com/pauldemarco/flutter_blue/issues/800) 

```
widget.device.mtu.elementAt(1).then((mtu) async {
        mtu = mtu < 23 ? 20 : mtu - 3; // failsafe by always assuming an ATT MTU and not a DATA MTU
        // do your service discovery
        _services = await widget.device.discoverServices();
      });
await widget.device.requestMtu(mtuSize);
```

It seems like the MTU size negotiation is only possible right after the service discovery, although I couldn't precisely figure out the reason why.
