### ISSUE TITLE
BLE no scan results

### ISSUE THREAD

**Issue by cloudbreakstudios** [boskokg/flutter_blue_plus#157]
I have several BLE devices, but have been unable to detect them, even with the demo code!  I am using a Pixel 4 and here is an example of one of the BLE devices i am using..  [(https://www.minew.com/product/d15n-keychain-beacon/)]

Flutter Doctor output:-
PS C:\Users\Rob\Desktop\flutter_blue_plus-master\flutter_blue_plus-master> flutter doctor -v
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.2130], locale en-GB)
    • Flutter version 2.10.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (7 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Rob\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2
    • Flutter plugin version 70.2.2
    • Dart plugin version 212.5744

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\Rob\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (4 available)
    • Pixel 4 (mobile)  • 99211FFAZ009P3 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.19044.2130]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 107.0.5304.62
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 106.0.1370.37

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
PS C:\Users\Rob\Desktop\flutter_blue_plus-master\flutter_blue_plus-master>

**Comment by chwong008** [comment]
same issue, no scan results on pixel 6a (Android 13).

there are scan results on android which use Android version below 13. 
(android 12,10 are OK, no problem)

**Comment by cloudbreakstudios** [comment]
Scanning is working for me on Samsung S8 running Android 9.  Issue seems to be related to latest Android OS version update!

**Comment by sajadmaster** [comment]
Please check your bluetooth permissions in Android Manifest file. 

Also, request for permissions before calling any bluetooth api.

Android 12, 13 bluetooth permission is changed a lot.

https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

**Comment by axelvugts** [comment]
FWIW: I discovered that you need the Bluetooth Connect permission even if you're only scanning for devices.
