### ISSUE TITLE
I can't get human-readable device name on flutter_blue_plus

### ISSUE THREAD

**Issue by devberkay** [boskokg/flutter_blue_plus#161]
I am currently developing a BLE application and testing on my iOS device but I can't get human-readable device name(instead always empty string) on flutter_blue_plus, it doesn't show up using advertisementData.localname or device.name , how can i get it? 

Note : For example among the 15 devices detected only the single one i can see its name e.g. Mi Smart Band 4

I have also looked into that solution and applied to the source code but nothing has changed : https://github.com/pauldemarco/flutter_blue/issues/524

**Comment by Daniel-Mock** [comment]
I am also experiencing this issue using android. 1 device shows name with device.name.toString() and all other devices are blank.

**Comment by boskokg** [comment]
Please debug the issue by debugging the android part and see what happens with that data.
I am closing the issue. Reopen it if you get more info.
