### ISSUE TITLE
PlatformException(locateCharacteristic, service could not be located on the device, null, null)

### ISSUE THREAD

**Issue by kamilszpila** [boskokg/flutter_blue_plus#162]
It seems that we receive this error while trying to read or write to characteristic just after disconnection.
There is some solution suggested here https://github.com/trueb2/flutter_blue/pull/5

**Comment by MrCsabaToth** [comment]
Interesting, the referred PR is a fork of the boskosg/flutter_blue and not the boskosg/flutter_blue_plus. I wonder if that was merged there, why is it not in this (flutter_blue_plus) project, and what other PRs merged into that project are not in the plus project.

**Comment by kamilszpila** [comment]
@boskokg @MrCsabaToth can you please fix it in this repository as well?

**Comment by MrCsabaToth** [comment]
> @boskokg @MrCsabaToth can you please fix it in this repository as well?

I don't have time for this now, can you craft a PR if you are at it?
