### ISSUE TITLE
Is it possible to detect connection lost, if device moves out of range?

### ISSUE THREAD

**Issue by jatin-web** [boskokg/flutter_blue_plus#164]
If I connect a device with another, and then they move apart such that they cannot communicate. Is it possible to get to know using the plugin that the connection is lost?

**Comment by xtnctx** [comment]
You can measure the RSSI level between your devices but I think your question is generally the same for sudden disconnection.

```dart

StreamSubscription? deviceState;

_listenState() {
    deviceState = device.state.listen((event) {
      if (event == BluetoothDeviceState.disconnected) {
        // your code here
      }
    });
}
```

**Comment by jatin-web** [comment]
It worked perfectly fine. Thanks a lot @xtnctx
