### ISSUE TITLE
FlutterBluePlusPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by choim4389** [boskokg/flutter_blue_plus#168]
when run on android, it shows `FlutterBluePlusPlugin.java uses or overrides a deprecated API.`

is It OK to use deprecated api?

**Comment by axelvugts** [comment]
I think you're running into the problem discussed in this issue: https://github.com/boskokg/flutter_blue_plus/issues/46
Please correct me if I'm wrong :)
