### ISSUE TITLE
Statement of purpose in README? How is FlutterBluePlus is different/better?

### ISSUE THREAD

**Issue by jdar** [boskokg/flutter_blue_plus#17]
My impression is that FlutterBluePlus is intended to be a stable and more simple version of FlutterBlue.

When should I prefer this library?

**Comment by mathisfouques** [comment]
You can see the need of such a library by going to [the flutter_blue issues sorted by comments](https://github.com/pauldemarco/flutter_blue/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc).

We can think of : 
 - [#864 in flutter_blue](https://github.com/pauldemarco/flutter_blue/issues/864)
 - [#662 in flutter_blue](https://github.com/pauldemarco/flutter_blue/issues/662) which workaround is _apparently_ to configure your app for debug..
 - [#336](https://github.com/pauldemarco/flutter_blue/issues/336#issuecomment-529820877) which solution is for the user to allow location in his phone
 - [#86 in flutter_blue](https://github.com/pauldemarco/flutter_blue/issues/86), few peoples have already created forks for it.

Not to mention future improvements, and compatibility with future versions of Flutter :)
