### ISSUE TITLE
requestMtu, no instance of BluetoothGatt, have you connected first?, java.lang.Exception: no instance of BluetoothGatt, have you connected first?

### ISSUE THREAD

**Issue by elmar001** [boskokg/flutter_blue_plus#174]
In Android using this code:
```
final mtu = await widget.device.mtu.first;
await widget.device.requestMtu(512);
```
Causes unhandled exception like below (Bluetooth is connected and everything else works without problem): 
 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(requestMtu, no instance of BluetoothGatt, have you connected first?, java.lang.Exception: no instance of BluetoothGatt, have you connected first?
E/flutter ( 9820): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.locateGatt(FlutterBluePlusPlugin.java:734)
E/flutter ( 9820): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.onMethodCall(FlutterBluePlusPlugin.java:670)
E/flutter ( 9820): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 9820): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter ( 9820): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/flutter ( 9820): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter ( 9820): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 9820): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 9820): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter ( 9820): 	at android.os.Looper.loop(Looper.java:313)
E/flutter ( 9820): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/flutter ( 9820): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9820): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter ( 9820): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter ( 9820): , null)
E/flutter ( 9820): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 9820): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter ( 9820): <asynchronous suspension>
E/flutter ( 9820): #2      BluetoothDevice.requestMtu (package:flutter_blue_plus/src/bluetooth_device.dart:160:5)

**Comment by PopeyedLocket** [comment]
same here
