### ISSUE TITLE
How to disconnect the connected device when quit App

### ISSUE THREAD

**Issue by yudeying918** [boskokg/flutter_blue_plus#175]
if there is connected device when quit app,  next time open the app, it's still shows connected, but cann't operate, so i want to disconnect when app is quit, to avoid this problem,  is anyone tried before, thanks.

**Comment by farhantandia** [comment]
use this widget as a parent widget in your screen..

WillPopScope(
        onWillPop: (){
device!.disconnect();
Future.value(true)
}

**Comment by yudeying918** [comment]
Thanks very much for you reply,  I have resolved the problem with your method.

I am a primary programer, and hope that I can get your help in the future, thanks !


Best Wishes!

Denny Yu
