### ISSUE TITLE
Missing getter for scanning state & stopScan() does not return early if not scanning

### ISSUE THREAD

**Issue by navaronbracke** [boskokg/flutter_blue_plus#177]
The bluetooth scanner Dart API does not expose the current state of the `isScanning` stream.
We only have access to a `Stream<bool>`, even though the underlying `StreamController` is a `BehaviorSubject`.

Secondly, the `stopScan()` method does not return early if the `_isScanning` controller indicates that the scanner is currently not scanning.

### Proposal

1. Provide a getter for the current scanning state, implemented like this:
```dart
  final BehaviorSubject<bool> _isScanning = BehaviorSubject.seeded(false);
  
  // Renamed, because the new getter can use the old name.
  Stream<bool> get isScanningStream => _isScanning; // BehaviorSubject implements the Stream interface, so no need to access the getter
  
  bool get isScanning => _isScanning.value;
```

2. Update the `stopScan()` method to return early if the scanner is not scanning, like this:
```
  /// Stops a scan for Bluetooth Low Energy devices
  Future<void> stopScan() async {
    if(!isScanning) {
      return;
    }
  
    await _channel.invokeMethod('stopScan');
    _stopScanPill.add(null);
    _isScanning.add(false);
  }
```

3. The `startScan()` method does not define the return type of the `Future`, it should be `Future<List<ScanResult>>`. Similarly, `stopScan()` should be `Future<void>`

**Comment by chipweinberger** [comment]
merged: https://github.com/boskokg/flutter_blue_plus/commit/4040296ca14667104235a93fb707a38ba605ab60

I needed this feature too!
