### ISSUE TITLE
Bump to version 1.4.0

### ISSUE THREAD

**Issue by Indigi-managed** [boskokg/flutter_blue_plus#181]
Can we get the latest published version published to pub.dev please? This was causing major confusion and issues for a client project I am working on ..

**Comment by RandersonM** [comment]
+1

**Comment by CristianFerreira** [comment]
+1

**Comment by paulosabra** [comment]
+1

**Comment by webererico** [comment]
+1

**Comment by boskokg** [comment]
Done. Sorry for waitting
