### ISSUE TITLE
BLE devices always disconnected on Android devices

### ISSUE THREAD

**Issue by figureai** [boskokg/flutter_blue_plus#186]
BLE devices always disconnected on Android devices but easily connected on iOS devices. i have Android 12 version devices.

**Comment by steveshp** [comment]
I updated flutter_blue_plus 1.4.0 and tested on my Samsung Galaxy 21(android 13 version). I have faced same problem.

**Comment by steveshp** [comment]
I modified compileSdkVersion 31 to compileSdkVersion 33 in build.gradle file. In my case this problem is solved.

**Comment by chipweinberger** [comment]
closing. see: https://github.com/boskokg/flutter_blue_plus/commit/00f1332870105a5e601b7e1562ca1b5442d6086f
