### ISSUE TITLE
Android problem with characteristics that used for more then one property

### ISSUE THREAD

**Issue by MayaBloodsAI** [boskokg/flutter_blue_plus#188]
Hi

I'm using your plugin to manage TI device, I have one characteristic that support write and notification as well. No matter what I did with your plugin I could only write to it, and didn't got any notifications.. Sense I implement it on Ionic and it works I checked what they do there different: and as you can see https://github.com/don/cordova-plugin-ble-central/blob/master/src/android/Peripheral.java they have 3 different type of functions to find characteristic: findNotifyCharacteristic, findWritableCharacteristic, findReadableCharacteristic - please see for example when they looking for notification characteristic they check first if the characteristic has notify property:

// Check for Notify first
        List<BluetoothGattCharacteristic> characteristics = service.getCharacteristics();
        for (BluetoothGattCharacteristic c : characteristics) {
            if ((c.getProperties() & BluetoothGattCharacteristic.PROPERTY_NOTIFY) != 0 && characteristicUUID.equals(c.getUuid())) {
                characteristic = c;
                break;
            }
        }

You have only one function: locateCharacteristic
when I enter this code to it:

    BluetoothGattCharacteristic characteristic = null;
    List<BluetoothGattCharacteristic> characteristics = service.getCharacteristics();
    for (BluetoothGattCharacteristic c : characteristics) {
      if ((c.getProperties() & BluetoothGattCharacteristic.PROPERTY_NOTIFY) != 0 && UUID.fromString(characteristicId).equals(c.getUuid())) {
          characteristic = c;
          //break;
      }
    }
    if(characteristic != null) {
      log(LogLevel.INFO, "notify characteristic found");
      return characteristic;
    }

The notification finally was triggers, but it can't be the hole solution because it used also for read&write characteristic - but I hope you understood the direction of the solution..

For any help please contact me..

**Comment by chipweinberger** [comment]
This sounds like the same issue: https://github.com/boskokg/flutter_blue_plus/issues/242

**Comment by MayaBloodsAI** [comment]
Yep.. The solution I suggested still work for me.. I can get notifications  which I couldn't before (:

**Comment by chipweinberger** [comment]
please try 1.7.6+, feel free to reopen if you still have problems.
