### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by ekuleshov** [boskokg/flutter_blue_plus#2]
The original `flutter_blue` plugin had MacOS support (somewhat broken after moving to null safety). Please add this functionality to the `flutter_blue_plus`

Original issue for MacOS support and PR
https://github.com/pauldemarco/flutter_blue/issues/463

Some details on the later MacOS issue:
https://github.com/pauldemarco/flutter_blue/issues/657

**Comment by boskokg** [comment]
@ekuleshov I saw that there were several issues reported that MacOS doesn't work, so I didn't just copy that part of the code. I will do add it in the next version and validated that it actually works.
I saw that other plugins done separation of platforms in the separate subplugins, so maybe we should do the same thing here...

**Comment by ekuleshov** [comment]
> I saw that other plugins done separation of platforms in the separate subplugins, so maybe we should do the same thing here...

Moving to [federated plugins](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#federated-plugins) is a bigger task, imho. It is a good idea for the long run maintenance and to support other platforms, but perhaps do it as a separate refactoring task after bringing the existing macos code in.

**Comment by FXschwartz** [comment]
Looks like possible some amount of effort went into moving to a [federated plugin setup in the old flutter_blue](https://github.com/pauldemarco/flutter_blue/issues/778), I wonder if we could pick up where they left off.

**Comment by ekuleshov** [comment]
> Looks like possible some amount of effort went into moving to a [federated plugin setup in the old flutter_blue](https://github.com/pauldemarco/flutter_blue/issues/778), I wonder if we could pick up where they left off.

What I see there is that android, ios and macos implementations are still under the same module, and they just extracted a platform interface and did a separate module/plugin for linux.

All in all, it still better to bring back the macos first and then refactor to federated or pull in that linux branch, if developers are still around (it been 11 months since last change out there).

**Comment by chipweinberger** [comment]
macOS support has landed. 

use 1.7.4.
