### ISSUE TITLE
[iOS] `isOn` method to check if bluetooth functionality is turned on, not working on iOS

### ISSUE THREAD

**Issue by chengboonrong** [boskokg/flutter_blue_plus#206]
I was getting this error message when this method was fired on iOS. 

`Unhandled Exception: MissingPluginException(No implementation found for method getBondedDevices on channel flutter_blue_plus/methods)`

Any solution or workaround for this? Thanks in advance!!!

**Comment by figureai** [comment]
I got the same problem.

**Comment by figureai** [comment]
I got the same problem.

**Comment by hidenxtt2001** [comment]
any solution for this ?

**Comment by manuel75o** [comment]
This works for me:
`bool isOn = await flutterBlue.isOn; //Check if BLE is on!
    if (isOn) {
      //Do Stuff
    }`
