### ISSUE TITLE
Can't run in apple m2 chip

### ISSUE THREAD

**Issue by Kirubhasankar** [boskokg/flutter_blue_plus#216]
Execution failed for task ':flutter_blue_plus:generateDebugProto'.
> protoc: stdout: . stderr: protoc-gen-lite: program not found or is not executable
  Please specify a program using absolute path or make sure the program is available in your PATH system variable
  --lite_out: protoc-gen-lite: Plugin failed with status code 1.

**Comment by Indigi-managed** [comment]
Hey @Kirubhasankar,

As per the README, you need to run this on a real physical device. The underlying hardware targeted cannot be emulated.

```
Alpha version
This package must be tested on a real device.
```
