### ISSUE TITLE
Not find device 

### ISSUE THREAD

**Issue by gamestap99** [boskokg/flutter_blue_plus#22]
I have a device and i can see it by bluetooth of mobile but i can no see it by this plugin

**Comment by watsmyname** [comment]
What is that bluetooth device?

**Comment by Hitbee-dev** [comment]
Checked Permission?

**Comment by ryuujo1573** [comment]
Hi, is your device's name full ASCII name?

**Comment by gamestap99** [comment]
Thank you all, My device is GLO™ 2. I think it not support ble
