### ISSUE TITLE
device connect hangs in await after a disconnect

### ISSUE THREAD

**Issue by raymadigan** [boskokg/flutter_blue_plus#220]
I am building an app that uses the bloc state management tech.

The bloc handler for connect is:

    void _onConnect(Connect event, Emitter<DeviceState> emit) async {
        log("DB: onConnect: ");
        if (state.device.hasDevice()) {
            log("DB: onConnect: hasDevice");
            BluetoothDevice device = state.device.bluetoothDevice!;
            await device.connect().then((value) {
                emit(state.connect());
                add(Connecting());
            }, onError: (e) {
                log(e.toString());
            });
            log("DB: onConnect: post await");
        }
    }

Hangs on await device.connect() after connect and disconnect

**Comment by cvanbeek13** [comment]
I'm having issues where the `device.connect()` function takes up to a minute to complete.  Do you know what caused this issue for you?
