### ISSUE TITLE
Handle disconnection

### ISSUE THREAD

**Issue by thewh1teagle** [boskokg/flutter_blue_plus#221]
When I listening to character of service and bluetooth is turned off or the bluetooth device is turned off so I got disconnection, it doesn't reconnect, and the listen method of the character doesn't throws error
how should I handle that?

**Comment by thewh1teagle** [comment]
![image](https://user-images.githubusercontent.com/61390950/225466336-2b15c79d-83f4-48b9-aac7-ac49aa22d73e.png)
this is what happening after the device is disconnected from my phone but I don't know where to catch that

**Comment by brain9520** [comment]
device.state.listen((event) {
      // Here you can monitor the Bluetooth connection status
      if (event == BluetoothDeviceState.disconnected) {
        _isDisconnected = true;
      }
      if (event == BluetoothDeviceState.connected) {
        _isDisconnected = false;
      // Here you can reconnect the device
      }
    });

**Comment by alexvnesta** [comment]
@brain9520 I had this same question - Thanks so much for your response! Also, good timing. Asked the question just hours before I needed the solution :)

**Comment by brain9520** [comment]
> @brain9520 I had this same question - Thanks so much for your response! Also, good timing. Asked the question just hours before I needed the solution :)

You are welcome, it is my honor to help you, I think this is also the meaning of sharing。
