### ISSUE TITLE
Manufacturer data stream not working in android.

### ISSUE THREAD

**Issue by Hesam-Taleghani** [boskokg/flutter_blue_plus#223]
I run the example app on both ios and android, and I have a scale that sends the data via the manufacturer data. While running on iOs, the manufacturer data changes as the weight on the scale changes, but in android the stream is always the same and the manufacturer data don't seem to change.

**Comment by chipweinberger** [comment]
let me know if you fixed this.

**Comment by chipweinberger** [comment]
please try 1.7.6+, reopen a new issue if you still have problems.
