### ISSUE TITLE
BluetoothDevice instance without scanning

### ISSUE THREAD

**Issue by cfontana0** [boskokg/flutter_blue_plus#228]
Hello! I'd like to know if it's possible to create an instance of the `BluetoothDevice` class without scanning for devices.
Basically, I'd like to store in the mobile app the `BluetoothDevice.id` attribute and use it for connecting directly to that device without scanning for other devices.

Is that possible?

I want to make it go as fast as possible, and if I can skip the scanning step, it's going to be the best!

**Comment by whatdtech** [comment]
You can do it like this connectdev() async {
   
    final device = BluetoothDevice.fromId('mac');
    
    await device.connect();
  }

**Comment by cfontana0** [comment]
Hi @whatdtech 
That method doesn't work on iOS, right?
Thanks,
Carlos

**Comment by whatdtech** [comment]
On Android it is working, didn't check on IOS

**Comment by WeiKuang** [comment]
this method work on iOS.but,on the iOS,the mac is uuid.

**Comment by FXschwartz** [comment]
Remember that the device ID is obfuscated and can change at any time. So it might work for a bit and then fail at any time.

See - https://github.com/pauldemarco/flutter_blue/issues/719

**Comment by chipweinberger** [comment]
yes this this is now possible in 1.7.0.

reopen a new issue if you still have problems.
