### ISSUE TITLE
Unable to search for any bluetooth devices after running the example

### ISSUE THREAD

**Issue by anla-xu** [boskokg/flutter_blue_plus#229]
hi .After I run the example, I click the search button, but there is no Bluetooth device information, and the interface is blank

**Comment by linkel77** [comment]
same here, I tried debugging in a samsung tab and it found the S-Pen. So I think it only gets the low energy devices.

**Comment by LaoWang7096** [comment]
I tried it on XiaoMi Mi11 with MIUI 14.0.8, click the search button but nothing found in the list. I've added uses-permission in AndroidManifest.xml as below but still not work:
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

**Comment by LaoWang7096** [comment]
<uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

**Comment by whatdtech** [comment]
https://github.com/boskokg/flutter_blue_plus/issues/225
follow this thread and it clears all your device discovery issues

**Comment by hamza2026** [comment]
> #225 follow this thread and it clears all your device discovery issues

This thread is also not working

**Comment by whatdtech** [comment]
Earlier I faced the same problem but after following all the steps mentioned  in that thread working fine in Android 13

**Comment by whatdtech** [comment]
```
    <!-- Allow Bluetooth -->
    <uses-feature
        android:name="android.hardware.bluetooth_le"
        android:required="true" />
    <!-- Request legacy Bluetooth permissions on older devices. -->
    <uses-permission android:name="android.permission.BLUETOOTH"
        android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"
        android:maxSdkVersion="30" />
    <!-- Needed only if your app looks for Bluetooth devices.
        If your app doesn't use Bluetooth scan results to derive physical
        location information, you can strongly assert that your app
        doesn't derive physical location. -->
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <!-- Needed only if your app makes the device discoverable to Bluetooth
         devices. -->
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
    <!-- Needed only if your app communicates with already-paired Bluetooth
      devices. -->
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <!-- If your application supports a service and can run on Android 10 (API level 29) or Android 11, you must also declare 
    the ACCESS_BACKGROUND_LOCATION permission to discover Bluetooth devices. -->
    <!-- <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" /> -->



  List<Permission> permissions = [
        Permission.location,
        Permission.storage,
        Permission.bluetooth,
        Permission.bluetoothConnect,
        Permission.bluetoothScan,
        ];
   await permissions.request();
```

All the above permissions in xml file and asking permissions during app initialisation are mandatory for Android latest versions.

Just do flutter clean and then build. It works for sure
