### ISSUE TITLE
2 Characteristic with same UUID but Different Properties (notify and write without response)

### ISSUE THREAD

**Issue by riorizki** [boskokg/flutter_blue_plus#230]
Hi 

i got BLE device that got 1 service.
when i discover the service they have 2 char with same UUID

<img width="803" alt="image" src="https://user-images.githubusercontent.com/28858623/229728155-f98d5dcf-2550-4bad-a2b5-6a722b1e48f3.png">

<img width="802" alt="image" src="https://user-images.githubusercontent.com/28858623/229728289-66e729d5-38fc-4608-9d2d-52922059d37e.png">

here is the code for receiving the Characteristic for notify and read

<img width="662" alt="image" src="https://user-images.githubusercontent.com/28858623/229728402-9933db6c-428d-40a5-826c-8007d547af9c.png">

but i still cant receive the data when listening to its char

<img width="515" alt="image" src="https://user-images.githubusercontent.com/28858623/229728482-23ca2d11-5a9c-4a45-98b3-799733a53c68.png">

how can i receive the data ?

Thank you

**Comment by chipweinberger** [comment]
There is no issue here. Characteristics can have Write, Notify, Indicate, properties simultaneously.

I imagine your issue is likely that your device is not sending any data!
