### ISSUE TITLE
Ble devices automatically disconnects after few seconds of successfully connecting

### ISSUE THREAD

**Issue by Kerimkullov** [boskokg/flutter_blue_plus#238]
In my project i will have multiple ble devices, (watch, sos button, panic button).

I need to connect to ble device and listen that user click sos button, how i can write characteristic for all that devices?

Now i'm trying to listen like: ` onTapSwitch: () async { // Connect to the device await device.connect();

                    var services = await device.discoverServices();
                    for (var service in services) {
                      for (var c in service.characteristics) {
                        await c.read();

                        await c.setNotifyValue(true);
                        c.value.listen((value) {
                          print('Success $value');
                        });
                      }
                    }
                  });`
But can't get any response, and ble devices automatically disconnects after few seconds of successfully connecting

**Comment by chipweinberger** [comment]
please try 1.7.6+, reopen a new issue if you still have problems.
