### ISSUE TITLE
Future of this library

### ISSUE THREAD

**Issue by Indigi-managed** [boskokg/flutter_blue_plus#245]
Hey @boskokg 

We really love this package and it's helped a lot of people out so I'm posting this here to ask, how can we as a community better help you?

Some ideas:

- Add another trusted owner/contributor to approve pull-requests
- Add a sponsor button to allow others to sponsor this repo (I would happily pay monthly for the future of this package)

Keen to hear your thoughts.

**Comment by chipweinberger** [comment]
I'm using this library for a new project, so I'll be working on it for the next while.

**Comment by boskokg** [comment]
@chipweinberger can you please send me the email that I can use to add permission for uploading new version to pub.dev

**Comment by chipweinberger** [comment]
@boskokg were you able to add me?

1. you need to create a pub.dev publisher
2. add me to the publisher
3. add the package to the publisher

**Comment by boskokg** [comment]
Hello @chipweinberger 
I have sent the invitation

![Screenshot 2023-05-06 at 04 36 06](https://user-images.githubusercontent.com/18428281/236594223-9b1e02e1-2ca3-4d5e-9655-0f65ea2524e4.png)

**Comment by chipweinberger** [comment]
great! got it!
