### ISSUE TITLE
Background scanning support?

### ISSUE THREAD

**Issue by shawn-grant** [boskokg/flutter_blue_plus#26]
@boskokg  I've been searching for a way to do a ble scan in the background, I was using **flutter_blue** but that doesnt work. does this package support it? or plans to?

**Comment by gregk104** [comment]
flutter_blue_plus is a direct, continuing fork from flutter_blue, so in a fundamental functional sense, it's going to act like flutter_blue.  As for future plans, I defer to @boskokg.

**Comment by watsmyname** [comment]
You could try using dart's isolate library for background scanning.

**Comment by shawn-grant** [comment]
@watsmyname  Thanks, I'll check that out
