### ISSUE TITLE
Periodic disconnect/reconnect loop

### ISSUE THREAD

**Issue by bagintz** [boskokg/flutter_blue_plus#277]
I am working through some basic connection tests/issues with my BLE project.  Sometimes it connects just fine and stays connected, other times it gets into a loop where it disconnects/reconnects over and over again.

Any ideas of what I might be able to do to stabilize this?

**Comment by chipweinberger** [comment]
no. but try pulling master branch.

**Comment by Sajonji** [comment]
@bagintz:
i had a similar behaviour (random disconnects, no reconnects though) with my BLE device.
what helped for me: replace device.connect() with device.connect(timeout: const Duration(seconds: 3), autoConnect: false), setting autoconnect to false being the important bit.

**Comment by bagintz** [comment]
@chipweinberger I am getting these errors after pulling from master in pubspec.  Do I need to do something else?

```
/Users/homedir/.pub-cache/git/flutter_blue_plus-8f1330e81a88d1d5987b4cc7d19392aec18093a3/android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java:564: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                                                        ^
  symbol:   variable TIRAMISU
  location: class VERSION_CODES
/Users/homedir/.pub-cache/git/flutter_blue_plus-8f1330e81a88d1d5987b4cc7d19392aec18093a3/android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java:567: error: method writeCharacteristic in class BluetoothGatt cannot be applied to given types;
            if ((gattServer.writeCharacteristic(characteristic, request.getValue().toByteArray(), BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE)) != BluetoothStatusCodes.SUCCESS) {
                           ^
  required: BluetoothGattCharacteristic
  found:    BluetoothGattCharacteristic,byte[],int
  reason: actual and formal argument lists differ in length
/Users/homedir/.pub-cache/git/flutter_blue_plus-8f1330e81a88d1d5987b4cc7d19392aec18093a3/android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java:572: error: method writeCharacteristic in class BluetoothGatt cannot be applied to given types;
            if ((gattServer.writeCharacteristic(characteristic, request.getValue().toByteArray(), BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT)) != BluetoothStatusCodes.SUCCESS) {
                           ^
  required: BluetoothGattCharacteristic
  found:    BluetoothGattCharacteristic,byte[],int
  reason: actual and formal argument lists differ in length
/Users/homedir/.pub-cache/git/flutter_blue_plus-8f1330e81a88d1d5987b4cc7d19392aec18093a3/android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java:624: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                                                        ^
  symbol:   variable TIRAMISU
  location: class VERSION_CODES
/Users/homedir/.pub-cache/git/flutter_blue_plus-8f1330e81a88d1d5987b4cc7d19392aec18093a3/android/src/main/java/com/boskokg/flutter_blue_plus/FlutterBluePlusPlugin.java:625: error: method writeDescriptor in class BluetoothGatt cannot be applied to given types;
          if(gattServer.writeDescriptor(descriptor, request.getValue().toByteArray()) != BluetoothStatusCodes.SUCCESS){
                       ^
  required: BluetoothGattDescriptor
  found:    BluetoothGattDescriptor,byte[]
  reason: actual and formal argument lists differ in length
```

**Comment by chipweinberger** [comment]
I haven't changed the java code.

Can look through my commits? We did change some configuration related things.

**Comment by chipweinberger** [comment]
@tuna-f1sh changed those lines

**Comment by chipweinberger** [comment]
lmk if you further it out.

I assume you need to update your android studio or build for a more recent android version ir something

**Comment by tuna-f1sh** [comment]
Yes I assume you need to update your Android build environment. It might be better to use the int value rather than the version enum though:  https://github.com/tuna-f1sh/flutter_blue_plus/tree/version-code

**Comment by andresc-dev** [comment]
I set pubspec.yaml 
```
flutter_blue_plus:
    git:
      url: https://github.com/tuna-f1sh/flutter_blue_plus
      ref: version-code
```
The erros @bagintz showed, due to the TIRAMISU enum, were corrected.

Then set build.gradle file to have `minSdkVersion`, `targetSdkVersion` and `compileSdkVersion` to 33.

Still get these errors

```
C:\apps\flutter\.pub-cache\git\flutter_blue_plus-4d414fdf02bc15edac1cc3ed213bc62199fde9fd\android\src\main\java\com\boskokg\flutter_blue_plus\FlutterBluePlusPlugin.java:567: error: method writeCharacteristic in class BluetoothGatt cannot be applied to given types;
            if ((gattServer.writeCharacteristic(characteristic, request.getValue().toByteArray(), BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE)) != BluetoothStatusCodes.SUCCESS) {
                           ^
  required: BluetoothGattCharacteristic
  found: BluetoothGattCharacteristic,byte[],int
  reason: actual and formal argument lists differ in length
C:\apps\flutter\.pub-cache\git\flutter_blue_plus-4d414fdf02bc15edac1cc3ed213bc62199fde9fd\android\src\main\java\com\boskokg\flutter_blue_plus\FlutterBluePlusPlugin.java:572: error: method writeCharacteristic in class BluetoothGatt cannot be applied to given types;
            if ((gattServer.writeCharacteristic(characteristic, request.getValue().toByteArray(), BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT)) != BluetoothStatusCodes.SUCCESS) {
                           ^
  required: BluetoothGattCharacteristic
  found: BluetoothGattCharacteristic,byte[],int
  reason: actual and formal argument lists differ in length
C:\apps\flutter\.pub-cache\git\flutter_blue_plus-4d414fdf02bc15edac1cc3ed213bc62199fde9fd\android\src\main\java\com\boskokg\flutter_blue_plus\FlutterBluePlusPlugin.java:625: error: method writeDescriptor in class BluetoothGatt cannot be applied to given types;
          if(gattServer.writeDescriptor(descriptor, request.getValue().toByteArray()) != BluetoothStatusCodes.SUCCESS){
                       ^
  required: BluetoothGattDescriptor
  found: BluetoothGattDescriptor,byte[]
  reason: actual and formal argument lists differ in length
3 errors

FAILURE: Build failed with an exception
```

really appreciate your work!

**Comment by chipweinberger** [comment]
@tuna-f1sh we should fix this before pub.dev is updates 

there must be a way to do conditional compilation in android, no?

**Comment by tuna-f1sh** [comment]
Yes, I can't reproduce this however. I'm building and running for SDK 33 with this code and it works. I'm not working on this at the moment so any pointers for anyone else would be helpful.

@andresc-dev , the fact the compiler is still complaining about the incorrect args suggest it's not using SDK 33 - but even so it should not execute that code if it was on the wrong version because of the catch.

You can see it's expecting the args for the old functions https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#writeDescriptor(android.bluetooth.BluetoothGattDescriptor)

**Comment by chipweinberger** [comment]
ChatGPT says it's possible but it sounds annoying. damn. what should we do

Yes, you can use a similar approach for a Flutter Android plugin to ensure compatibility with different Android API levels. Flutter plugins are essentially Android libraries, so the same principles apply. Here's how you can create build variants for your Flutter Android plugin:

1. Open your plugin's `android/build.gradle` file (the one located in the `android` directory of your plugin).
2. Inside the `android` block, add a `productFlavors` block to define different flavors, like this:

```groovy
android {
    ...
    productFlavors {
        lowApi {
            minSdkVersion 21
            maxSdkVersion 25
        }
        highApi {
            minSdkVersion 26
        }
    }
}
```

3. Create new source directories for each flavor. By default, your code is in the `main` source directory (`src/main`). Create `src/lowApi` and `src/highApi` directories.

4. Place the code specific to each flavor in the respective directories. For example, you can have a class implementing a certain feature in both the `lowApi` and `highApi` directories, but with different implementations.

5. In the `README.md` or any other documentation, mention the steps required for users of your plugin to configure their build.gradle file and select the correct build variant.

For example, in their app's `build.gradle` file, they should include:

```groovy
android {
    ...
    flavorDimensions "apiLevel"
    productFlavors {
        lowApi {
            dimension "apiLevel"
            minSdkVersion 21
            maxSdkVersion 25
        }
        highApi {
            dimension "apiLevel"
            minSdkVersion 26
        }
    }
}
```

And they should select the desired build variant in the "Build Variants" panel in Android Studio.

However, note that creating build variants for a plugin might not be the most convenient way for users to consume your plugin, as it requires additional configuration on their side. It's generally preferable to use runtime checks with `Build.VERSION.SDK_INT` and provide fallbacks for lower API levels within your plugin's code, so users don't have to deal with build variants.

**Comment by chipweinberger** [comment]
we should probably revert your commit until next year or so.

**Comment by tuna-f1sh** [comment]
I was hoping this would be the case 

> It's generally preferable to use runtime checks with Build.VERSION.SDK_INT and provide fallbacks for lower API levels within your plugin's code, so users don't have to deal with build variants

But I guess those are not ignored by the compiler. Seems odd there is not a `ifdef` style block available. Yes I would revert if others have the issue. Bare in mind it will create incompatibility with the latest Android release though.

**Comment by andresc-dev** [comment]
@tuna-f1sh if you were compiling correctly on you `version-code` branch, may you please use a lower Adnroid SDK version (ex: 31) and check if it compiles correctly?


>  But I guess those are not ignored by the compiler. Seems odd there is not a ifdef style block available.

I would expect the same. That's the whole idea behind conditional compilation.

**Comment by chipweinberger** [comment]
I've deleted the comments that are unrelated to this specific issue (connection/disconnection).

@bagintz please open a new issue when you have a new issue.

**Comment by bagintz** [comment]
@chipweinberger will do, thanks

**Comment by chipweinberger** [comment]
please try 1.7.6+, reopen a new issue if you still have problems.

**Comment by chipweinberger** [comment]
autoconnect is now false by default:

7c2d33b1cd07c028705828cf965beec70f6a72de
