### ISSUE TITLE
Andorid: connectedDevices only returns incomplete list

### ISSUE THREAD

**Issue by jhoffi** [boskokg/flutter_blue_plus#279]
"connectedDevices" only returns a list of devices that are not media devices. Devices such as watches (e.g. Garmin Vivoactive 3) are shown. Bluetooth Speaker and Headphones (e.g. Sony Linkbuds, JBL Charge 4) are missing.

**Comment by chipweinberger** [comment]
Bluetooth speakers and headphones are not *BLE* devices.

This library only supports BLE.
