### ISSUE TITLE
autoConnect doesn't work if BT was turned off then on again

### ISSUE THREAD

**Issue by zemmyang** [boskokg/flutter_blue_plus#285]
Scenario: 
- app opens while BT is on
- app reads data from device
- user turns off BT (for example, turned on airplane mode)
- user manually turns on BT
- what happens: app doesn't reconnect to device

---

I tried using RxDart's RetryWhenStream to force the reconnection:

```
  RetryWhenStream(
        () => flutterBluePlus.state
            .map((i) async {

              if (i == BluetoothState.on){
                await device.connect(autoConnect: true);
                return dataStream;
              }
              else {
                throw "BT not on";
              }
        }),
          (Object e, StackTrace s) =>
          Rx.timer<void>(null, const Duration(seconds: 1)),
  ).listen((event) {
// stuff
  });
```

where the [initial setup for the stream is done like this](https://github.com/boskokg/flutter_blue_plus/issues/274#issuecomment-1539803590). i also tried putting that entire function in the if BT.on block in the code above, but it still doesn't reconnect.

Maybe I'm missing something?

**Comment by chipweinberger** [comment]
please open a PR if you fix the problem

**Comment by chipweinberger** [comment]
please try 1.7.6+, reopen a new issue if you still have problems.
