### ISSUE TITLE
CoreBluetooth API MISUSE

### ISSUE THREAD

**Issue by codepgq** [boskokg/flutter_blue_plus#293]
`[CoreBluetooth] API MISUSE: <CBCentralManager: 0x281fc8000> can only accept this command while in the powered on state
`
Every time I open the app, I will be prompted with the above information

SDK vresion: flutter_blue_plus: ^1.5.0
Dart Version: 3.10.1

**Comment by chipweinberger** [comment]
thanks for filing. feel free to open a PR if you fix it.

**Comment by chipweinberger** [comment]
I have not been able to repro this, so you will need to debug it yourself.

**Comment by codepgq** [comment]
What I found here is different from your sample code is that I didn’t check whether the Bluetooth is turned on, and started searching for devices directly. When I also checked the Bluetooth status, this problem would not occur.

**Comment by chipweinberger** [comment]
great that you solved it.
