### ISSUE TITLE
setNotifyValue failed 

### ISSUE THREAD

**Issue by stonehiy** [boskokg/flutter_blue_plus#299]
Failed to display in 1.5. x, but there is no problem in 1.4.0，Please help me, thank you！

**Comment by chipweinberger** [comment]
please share more logs, ios / android , what is the actual error, etc

**Comment by wangdongmeng** [comment]
Same problem, call setNotifyValue(true) and raise an exception

<img width="894" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/7833854/3befd554-18f3-4350-a21b-f7bbb0cbeb88">

**Comment by chipweinberger** [comment]
Interesting. Yes that is a new check I added. 

Are you on iOS or android?  Ideally, please add logs to the ios obj-c code and android java code so you can inspect why they are returning failure

**Comment by wangdongmeng** [comment]
There is a problem with Android, but there is no problem with ios. I try to add the log

**Comment by wangdongmeng** [comment]
Need to update the plugin? thank you

**Comment by chipweinberger** [comment]
yes ill push an update shortly

**Comment by chipweinberger** [comment]
https://github.com/boskokg/flutter_blue_plus/commit/541fa971ed66c9c81bb272fbcfb4da5ad6e7e332

fixed

**Comment by wangdongmeng** [comment]
> 

Thanks sir. Verified. You can turn this off
