### ISSUE TITLE
characteristic write and read callback data ,but error occurred!

### ISSUE THREAD

**Issue by Goallying** [boskokg/flutter_blue_plus#301]
MyCode :

        await c.write([0xab, 0x00, 0x04, 0x00, 0x02, 0xc1, 0xaf],
                                withoutResponse: false);
         var value = await c.read();
         print("onWritePressed ,value =$value");

Reslut ：
<img width="729" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/12438493/87d507b4-a348-4425-80f3-3fe8a23cb914">

**Comment by chipweinberger** [comment]
Please look at the logs, there should be a more detailed error.

see this line:         NSLog(@"[FBP-iOS] didWriteValueForCharacteristic: [Error] %@", [error localizedDescription]);

```
- (void)peripheral:(CBPeripheral *)peripheral
    didWriteValueForCharacteristic:(CBCharacteristic *)characteristic
                             error:(NSError *)error
{
    if (error) {
        NSLog(@"[FBP-iOS] didWriteValueForCharacteristic: [Error] %@", [error localizedDescription]);
    } else if (_logLevel >= debug) {
        NSLog(@"[FBP-iOS] didWriteValueForCharacteristic");
    }

    ProtosWriteCharacteristicRequest *request = [[ProtosWriteCharacteristicRequest alloc] init];
    [request setRemoteId:[peripheral.identifier UUIDString]];
    [request setCharacteristicUuid:[characteristic.UUID fullUUIDString]];
    [request setServiceUuid:[characteristic.service.UUID fullUUIDString]];

    ProtosWriteCharacteristicResponse *result = [[ProtosWriteCharacteristicResponse alloc] init];
    [result setRequest:request];
    [result setSuccess:(error == nil)];

    [_channel invokeMethod:@"WriteCharacteristicResponse" arguments:[self toFlutterData:result]];
}
```

**Comment by chipweinberger** [comment]
or android:       `log(LogLevel.DEBUG, "[onCharacteristicWrite] uuid: " + characteristic.getUuid().toString() + " status: " + status);`

```
    @Override
    public void onCharacteristicWrite(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, int status) {
      log(LogLevel.DEBUG, "[onCharacteristicWrite] uuid: " + characteristic.getUuid().toString() + " status: " + status);
      Protos.WriteCharacteristicRequest.Builder request = Protos.WriteCharacteristicRequest.newBuilder();
      request.setRemoteId(gatt.getDevice().getAddress());
      request.setCharacteristicUuid(characteristic.getUuid().toString());
      request.setServiceUuid(characteristic.getService().getUuid().toString());
      Protos.WriteCharacteristicResponse.Builder p = Protos.WriteCharacteristicResponse.newBuilder();
      p.setRequest(request);
      p.setSuccess(status == BluetoothGatt.GATT_SUCCESS);
      invokeMethodUIThread("WriteCharacteristicResponse", p.build().toByteArray());
    }
```

**Comment by Goallying** [comment]
> Please look at the logs, there should be a more detailed error.
> 
> see this line: ` NSLog(@"[FBP-iOS] didWriteValueForCharacteristic: [Error] %@", [error localizedDescription]);`
> 
> ```
> - (void)peripheral:(CBPeripheral *)peripheral
>     didWriteValueForCharacteristic:(CBCharacteristic *)characteristic
>                              error:(NSError *)error
> {
>     if (error) {
>         NSLog(@"[FBP-iOS] didWriteValueForCharacteristic: [Error] %@", [error localizedDescription]);
>     } else if (_logLevel >= debug) {
>         NSLog(@"[FBP-iOS] didWriteValueForCharacteristic");
>     }
> 
>     ProtosWriteCharacteristicRequest *request = [[ProtosWriteCharacteristicRequest alloc] init];
>     [request setRemoteId:[peripheral.identifier UUIDString]];
>     [request setCharacteristicUuid:[characteristic.UUID fullUUIDString]];
>     [request setServiceUuid:[characteristic.service.UUID fullUUIDString]];
> 
>     ProtosWriteCharacteristicResponse *result = [[ProtosWriteCharacteristicResponse alloc] init];
>     [result setRequest:request];
>     [result setSuccess:(error == nil)];
> 
>     [_channel invokeMethod:@"WriteCharacteristicResponse" arguments:[self toFlutterData:result]];
> }
> ```
Thank you, I fix this error by changing "writeWithResponse" to "writewithoutResponse" , but the "didWriteValueForCharacteristic" method not called when I had send some data.

**Comment by chipweinberger** [comment]
that error message means you are writing to a characteristic that does not allow writing.

it should mean there is a bug in your program.

**Comment by chipweinberger** [comment]
> but the "didWriteValueForCharacteristic" method not called when I had send some data.

you will need to debug that yourself. I can't know the reason.

**Comment by ZameerHaider** [comment]
but it writes when I send a single line to the same printer

**Comment by chipweinberger** [comment]
> but it writes when I send a single line to the same printer

?

**Comment by Goallying** [comment]
> that error message means you are writing to a characteristic that does not allow writing.
> 
> it should mean there is a bug in your program.

**Comment by JDongKhan** [comment]
I also got the same issue for iOS.  

didWriteValueForCharacteristic: [Error] Writing is not permitted.
