### ISSUE TITLE
"characteristic.value.listen((value)" does't have any callback.

### ISSUE THREAD

**Issue by Goallying** [boskokg/flutter_blue_plus#307]
My Code Like：

  c1.setNotify(true);
 c1.value.listen((value){
  print("callback");
  });
   c2.write(data);

Result:
  there is no callback, why?

**Comment by Goallying** [comment]
> My Code Like：
> 
> c1.setNotify(true); c1.value.listen((value){ print("callback"); }); c2.write(data);
> 
> Result: there is no callback, why?

I add the code "c1.read();" before "c2.write(data);" and there are Multiple callbacks ! what happened?

**Comment by Oooooori** [comment]
same issues
but can't receive callback after “c1.read()”
