### ISSUE TITLE
withoutResponse only write 20bits?

### ISSUE THREAD

**Issue by guduqiucai** [boskokg/flutter_blue_plus#310]
c.writeChar.write([0x12, 0x34, ......]); 
can write than 100 characters, but slow in speed, why neen about 3 seconds?
c.writeChar.write([0x12, 0x34, ......], withoutResponse: true); 
only write 20 characters, but fast in speed, why neen about 3 milliseconds?
I need to unpack and send packages of around 1M, how should I write the sending of each package?

**Comment by brain9520** [comment]
The amount of written data depends on whether the BLE device is 5.0 or below. If the BLE device is 5.0, it can write up to 250 bytes at a time. If it is 4.0, it can write up to 20 bytes at a time.

**Comment by chipweinberger** [comment]
^ this is correct. You can increase the mtu size to try and get faster data rate.
