### ISSUE TITLE
Arduino module HC-05

### ISSUE THREAD

**Issue by Emanuel108** [boskokg/flutter_blue_plus#311]
Is this plugin compatible with HC-05 module?
https://www.electronicwings.com/sensors-modules/bluetooth-module-hc-05-

**Comment by Dracula-101** [comment]
This package is meant for BLE device, whereas HC-05 is a bluetooth classic device. I recommend going with flutter_bluetooth_serial that can help you connect and even communicate with HC-05 module

**Comment by xbug42** [comment]
Note that flutter_bluetooth_serial does not work on iOS. Afaik, if you want to support iOS, you have to use BLE (so you cannot use HC-05...).

**Comment by chipweinberger** [comment]
please try 1.7.6+, reopen a new issue if you still have problems.
