### ISSUE TITLE
PlatformException(locateCharacteristic, service could not be located on the device, null, null)

### ISSUE THREAD

**Issue by dhvani-2023** [boskokg/flutter_blue_plus#312]
Getting this error after connecting to a BLE device from ios.

**Comment by sachin-ngendev** [comment]
Same issue in iOS. Please fix this if it's a platform specific issue.

**Comment by chipweinberger** [comment]
sounds like you are trying to use a service that does not exist.

otherwise, please open a PR if you fix it

**Comment by chipweinberger** [comment]
please try 1.7.6+, reopen a new issue if you still have problems.
