### ISSUE TITLE
Unable to get response error from ble device

### ISSUE THREAD

**Issue by mohamedsl22** [boskokg/flutter_blue_plus#316]
Hi,
With the ble device that I’m working with there is custom error responses that I can’t receive! There is one general error in the library that is saying “failed to write to characteristic“ not specifying the error code that I receive from the device! Can you please show me a way to get the error code ? Thank you

**Comment by chipweinberger** [comment]
look at the logs. ios will log the specific error code. 

you must be on version 1.5.2

**Comment by chipweinberger** [comment]
AFAIK, Android does not return an error code when writeCharacteristic fails. It just returns success or failure.

Feel free to open a PR if you think otherwise.
