### ISSUE TITLE
how to get number of current active connected deivces.?

### ISSUE THREAD

**Issue by exmlcxjv** [boskokg/flutter_blue_plus#317]
I've seen this in the console printed every seconds showing the number of active ble connections.

**D/FlutterBluePlugin( 5256): mDevices size: 0**

How can access the value 'mDevices size' from flutter source code?

**Comment by jeffreywolberg** [comment]
Try
`List<BluetoothDevices> devices = await FlutterBluePlus.instance.connectedDevices`

**Comment by exmlcxjv** [comment]
> Try `List<BluetoothDevices> devices = await FlutterBluePlus.instance.connectedDevices`

thanks mate, works well !
