### ISSUE TITLE
Cannot obtain list of connected devices on macOS

### ISSUE THREAD

**Issue by jeffreywolberg** [boskokg/flutter_blue_plus#319]
I have the following connected devices to my M1 MacBook pro
<img width="485" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/54825193/a0260ffd-7a84-4fcf-a2ac-2cd1208d4265">

However, doing 
```
List<BluetoothDevice> bluetoothDevices = await FlutterBluePlus.instance.connectedDevices;
```
returns an empty list.

This seems like a pretty important feature to have working.

Here's the relevant Flutter output from `flutter doctor`
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)

**Comment by chipweinberger** [comment]
I think you need to scan and connect with FBP.

I don't see this being implemented.

What is your use case?

**Comment by chipweinberger** [comment]
please try 1.7.5+. reopen if you have issues.

macOS code is near identical to IOS now.

**Comment by chipweinberger** [comment]
speakers and headphones do not support BLE, only Bluetooth Classic.

They will not be usable with this app.
