### ISSUE TITLE
Cant find any devices while flutter blue scanning

### ISSUE THREAD

**Issue by Vimalnath1** [boskokg/flutter_blue_plus#325]
I have a button that is supposed to scan for all BLE devices, but it never finds anything. The terminal always responds with 
D/BluetoothLeScanner(25915): could not find callback wrapper
D/BluetoothAdapter(25915): isLeEnabled(): ON
D/BluetoothLeScanner(25915): onScannerRegistered() - status=0 scannerId=5 mScannerId=0
D/BluetoothAdapter(25915): isLeEnabled(): ON

Here is my code:
FlutterBluePlus flutterBlue = FlutterBluePlus.instance;
setState(() {
                  devicelist=Set();
                });
              
                flutterBlue.startScan(timeout: const Duration(seconds: 4));
                result=flutterBlue.scanResults;

                result.listen((results) {
                  for (ScanResult devices in results){
                    print(devices.device.name);
                    devicelist.add(devices.device.name);
                  }
                 },
                 onError: (err) {
                   print("Not working");
                 }
                 );
                 print(devicelist);
                
                // Stop scanning
                flutterBlue.stopScan();

**Comment by wwwdwanfangdata** [comment]
I also encountered this problem, Android 13 plug-in version 1.4.0 and later can not scan Bluetooth devices
[https://github.com/boskokg/flutter_blue_plus/issues/225#issuecomment-1477241661](url)
I've added all the permissions requested, and it's still not working. But version 1.4.0 is fine.

**Comment by chipweinberger** [comment]
If either of you fix the issue, please open a PR

**Comment by Vimalnath1** [comment]
I figured it out. For some reason I have to scan twice in order for it to detect devices like this.

FlutterBluePlus.instance.startScan(timeout: const Duration(milliseconds: 100));

FlutterBluePlus.instance.stopScan();

Timer(Duration(milliseconds: 100), () {

flutterBlue.startScan(timeout: const Duration(seconds: 1));

});

//print(flutterBlue.);

result=flutterBlue.scanResults;

result.listen((results) {

for (ScanResult devices in results){

print(devices.device.name);

devicelist.add(devices.device.name);

}

},

onError: (err) {

print("Not working");

}

);

print(devicelist);

**Comment by yutakau** [comment]
Hello,
I am facing the same problem.
Did you solve the problem by simply scanning twice?
I am very curious, this problem does not occur when compiling with android studio on windows, but when compiling with android studio on mac, it does not return scan results.

**Comment by yutakau** [comment]
Yes, when compiled on mac, the version is 1.5.2 and two scans have not solved the problem for me. But your information seems to be a clue to a solution. Thanks.

**Comment by chipweinberger** [comment]
perhaps macOS has problems

https://github.com/boskokg/flutter_blue_plus/issues/319

**Comment by yutakau** [comment]
I tested it. Upgrading to 1.6.1 solved the problem of no scan results when compiling on mac.
Thanks.

**Comment by gorychama** [comment]
new version of android works fine , ios works fine . only old version of android need to scan twice

**Comment by yutakau** [comment]
I noticed another point of view.
The important thing is the termination process.
I needed to ensure that the scan stopped and turned off when exiting.
Without this process, after the second and subsequent startups, the scan would definitely run and find nothing, and no timeouts would occur. Tested ver 1.5.0 and 1.6.1


  Future<void> _disconnectDevice() async {
    await FlutterBluePlus.instance.stopScan();
    await FlutterBluePlus.instance.turnOff();
  }
  @override
  void dispose() {
    _disconnectDevice();
    super.dispose();
  }

**Comment by yutakau** [comment]
I'm not sure if 1.6.1 retracted version.
Yes, it is not in the pub.dev. I had installed as following in pubspec.yaml.

```
dependencies:
  flutter_blue_plus:
    git:
      url: https://github.com/boskokg/flutter_blue_plus.git
      ref: 1.6.1

```

**Comment by CoThomas** [comment]
I encounter the issue on both Android and iOS devices.

On my side, the issue was I did this : 

```
flutterBlue.stopScan();
flutterBlue.startScan(timeout: const Duration(seconds: 3));
```

But, since 1.5.0, it seems that `stopScan` need some time ?

So, I just have to do this : 

```
flutterBlue.stopScan();
// Need to wait a little between stopScan and startScan
Timer(const Duration(milliseconds: 100), () {
  flutterBlue.startScan(timeout: const Duration(seconds: 3));
});
```

No need for double call on my side it seems.
And it works on 1.5.2.

**Comment by chipweinberger** [comment]
please try 1.7.5+. reopen if you have issues.
