### ISSUE TITLE
On iOS. Can not receive data after setNotifyValue.

### ISSUE THREAD

**Issue by Oooooori** [boskokg/flutter_blue_plus#329]
1. await readCharacteristic.setNotifyValue(true);
2. show Log：[FBP-iOS] didUpdateNotificationStateForCharacteristic
3. show Log：[FBP-iOS] didUpdateValueForDescriptor
4. readCharacteristic.onValueChangedStream.listen(() {  callback  });   
5. wirteCharacteristic.write(xxxxx);
6. show Log：[FBP-iOS] didWriteValueForCharacteristic
7. But callback never called

BUT!!!  if I add 5 seconds delay after setNotifyValue

1. await readCharacteristic.setNotifyValue(true);
2. show Log：[FBP-iOS] didUpdateNotificationStateForCharacteristic
3. show Log：[FBP-iOS] didUpdateValueForDescriptor
4. readCharacteristic.onValueChangedStream.listen(() {  callback  });
5. await Future.delayed(const Duration(seconds: 5), () async {}) /// add this code
6. wirteCharacteristic.write(xxxxx);
7. show Log：[FBP-iOS] didWriteValueForCharacteristic
8. show Log:  [FBP-iOS] didUpdateValueForCharacteristic
9. callback called

flutter_blue_plus version : 1.5.2

Why???  what changes after 5 seconds delayed???

**Comment by Oooooori** [comment]
same on 1.4.0

**Comment by Hickstone** [comment]
I had a similar problem. I solved it by switching the listener assignment and notifyValue.
Does not work:
1. await readCharacteristic.setNotifyValue(true);
2. readCharacteristic.onValueChangedStream.listen(() { callback });
Does work:
1. readCharacteristic.onValueChangedStream.listen(() { callback });
2. await readCharacteristic.setNotifyValue(true);

Maybe this helps.

**Comment by WeiKuang** [comment]
> I had a similar problem. I solved it by switching the listener assignment and notifyValue. Does not work:
> 
> 1. await readCharacteristic.setNotifyValue(true);
> 2. readCharacteristic.onValueChangedStream.listen(() { callback });
>    Does work:
> 3. readCharacteristic.onValueChangedStream.listen(() { callback });
> 4. await readCharacteristic.setNotifyValue(true);
> 
> Maybe this helps.
yes, me too

**Comment by WeiKuang** [comment]
> I had a similar problem. I solved it by switching the listener assignment and notifyValue. Does not work:
> 
> 1. await readCharacteristic.setNotifyValue(true);
> 2. readCharacteristic.onValueChangedStream.listen(() { callback });
>    Does work:
> 3. readCharacteristic.onValueChangedStream.listen(() { callback });
> 4. await readCharacteristic.setNotifyValue(true);
> 
> Maybe this helps.



Yes, me too

**Comment by chipweinberger** [comment]
please open a PR if you can fix this properly. I am not sure the cause.

**Comment by chipweinberger** [comment]
I think this problem should be resolved. This code has been changed and simplified a lot since June 8th.

If you continue to have problems, please open a new issue.
