### ISSUE TITLE
The app from Example couldn't run on Android

### ISSUE THREAD

**Issue by 0xThomas3000** [boskokg/flutter_blue_plus#333]
I couldn't make the app run properly on Android although it can run successfully on IOS. Already turned on the Bluetooth, allowed the app to access the location. But when I clicked on the 'TURN ON' button, there seem to be nothing going to happen, the screen keeps displaying like below.
<img width="200" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/13832667/1a8d0b22-227d-4118-b48e-6505d7e7715a">

Also have added these lines into the 'AndroidManifest.xml' to grant some permissions to the app for Android but no success.
<img width="500" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/13832667/81cbb369-9ddf-4c9b-89e3-d4098af3f183">

**Comment by 0xThomas3000** [comment]
I fixed that problem and it now can run on Android.

**Comment by kalismeras61** [comment]
@0xThomas3000 what was the issue ?
