### ISSUE TITLE
BLE Scan Continuously 

### ISSUE THREAD

**Issue by Kavinkumarsimple** [boskokg/flutter_blue_plus#334]
How do i continuously scan for BLE Devices? Im building a BLE Scanner app and it should always scan and show the changes

**Comment by GrayLand119** [comment]
> How do i continuously scan for BLE Devices? Im building a BLE Scanner app and it should always scan and show the changes

Try this branch, I created a commit to support scan continuously.
Set params updateInterval, expiredInterval, and allowDuplicates=true in scan method.

https://github.com/GrayLand119/flutter_blue_plus/commit/5b5afa145cf7a19103e44e8f8f62d0a77fb346ae

**Comment by R-Emagina** [comment]
Hi,

I'd love to see this in the master branch.
Does someone know when it could be merged?

Thanks!

**Comment by GrayLand119** [comment]
PR Created: https://github.com/boskokg/flutter_blue_plus/pull/382

**Comment by chipweinberger** [comment]
thanks for the PR, but AFAICT, it should be easy for the user to implement this feature themself. 

Just create a timer and repeatedly call `FlutterBluePlus.instance.scan` yourself, etc.

This repo already has a ton of bugs. We can't handle more complexity.

Thanks again.
