### ISSUE TITLE
Real device redmi 8 not working scan

### ISSUE THREAD

**Issue by Sebuahhobi** [boskokg/flutter_blue_plus#335]
### Not working device redmi 8

I'm try same code work if not device redmi.
Why not work if i'm using device redmi 8?

This android manifest

`<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />`

> This my code on flutter:

`Future<void> initBluetooth() async {
    try {
      await flutterBlue.startScan(timeout: const Duration(seconds: 4));
      flutterBlue.scanResults.listen((results) {
        for (ScanResult r in results) {
          log("R $r");
          log('${r.device.name} found! rssi: ${r.rssi}');
        }
      }, onDone: () {
        log("Done scan");
      });

      log('list of paired devices');
      flutterBlue.connectedDevices.asStream().listen((paired) {
        log('paired device: $paired');
      }, onDone: () {
        log("Done");
      });

      List<BluetoothDevice> connectedDevices = await flutterBlue.connectedDevices;
      for (BluetoothDevice device in connectedDevices) {
        log('Device name: $device');
      }

      flutterBlue.scan(timeout: const Duration(seconds: 4)).listen((scanResult) {
        var device = scanResult.device;
        log("Bluettoh tersimpan : $scanResult");
        log('${device.name} found! rssi: ${scanResult.rssi}');
      }, onDone: () => log("Selessai scan"));

      flutterBlue.stopScan();
    } catch (error) {
      log("Error blue $error");
    }
  }`

**Comment by chipweinberger** [comment]
please try 1.7.5+. reopen if you have issues.
