### ISSUE TITLE
Remove protobuf

### ISSUE THREAD

**Issue by MrCsabaToth** [boskokg/flutter_blue_plus#338]
iOS and MacOS is done: https://github.com/boskokg/flutter_blue_plus/commit/1848617e6ce25385c2a7b4129aa199801bcfee71
Android needs to be taken care of

**Comment by MrCsabaToth** [comment]
Haven't had time to progress with this so far unfortunately.
But looking into some Google in-house plugins they use Pigeon for method channels: https://pub.dev/packages/pigeon

**Comment by chipweinberger** [comment]
this work is now done in 1.7.0
