### ISSUE TITLE
Ios: Every time you open the APP, the first scan always fails, and the second scan is normal  

### ISSUE THREAD

**Issue by jahnli** [boskokg/flutter_blue_plus#34]
Ios: Every time you open the APP, the first scan always fails, and the second scan is normal  

This problem does not exist with Flutter Blue

**Comment by jahnli** [comment]
@boskokg   Ios: Every time you open the APP, the first scan always fails, and the second scan is normal

**Comment by jahnli** [comment]
first scan  :
![image](https://user-images.githubusercontent.com/20943608/160780016-1dc3ca1c-1df6-4a7c-b0ad-ce140a537826.png)

**Comment by jahnli** [comment]
two scan 
![image](https://user-images.githubusercontent.com/20943608/160780085-e82901ba-8391-4223-b9e8-7a9916de253f.png)

**Comment by JaysonJia** [comment]
I had the same issue: when first startscan:
'[CoreBluetooth] API MISUSE: <CBCentralManager: 0x282854480> can only accept this command while in the powered on state'

**Comment by MATTYGILO** [comment]
Having the same problem, any updates?

**Comment by boskokg** [comment]
Can you please debug the problem and propose the merge request of the solution?

**Comment by eriksoderstrom** [comment]
try {
      await for(final state in _flutterBlue.state.timeout(const Duration(seconds: 5))) {
        if(state == bt.BluetoothState.on) {
          _logger.info('BT Adapter turned ON');
          break;
        }
      }
    } catch(e) {
      _logger.info('Timeout when waiting for BT adapter ON');
    }
    return _flutterBlue.startScan(timeout: timeout, withServices: [typeToScan]);



I've used this to wait until BT adapter switches ON for iOS.

**Comment by Hitbee-dev** [comment]
``` dart
@override
initState() {
  super.initState();
Future.delayed(const Duration(milliseconds: 100), () {
      scan();
    });
}
```

It was resolved by delaying `100ms` when entering the Bluetooth settings page and scanning.
