### ISSUE TITLE
Support for Long write

### ISSUE THREAD

**Issue by explorer2050** [boskokg/flutter_blue_plus#340]
does flutter_blue_plus package has support for "long writes" e.g. > 512 bytes of data?

**Comment by mynaner** [comment]
if (Platform.isAndroid) {
        await device?.requestMtu(64);
      }

**Comment by deverlex** [comment]
It doesn't. You need a chunks data to list<list<Uint8>> and call write each item. Or you can move to https://pub.dev/packages/flutter_reactive_ble

**Comment by chipweinberger** [comment]
no.
