### ISSUE TITLE
Sudden Disconnect Causes App To Crash

### ISSUE THREAD

**Issue by FXschwartz** [boskokg/flutter_blue_plus#342]
I'm still investigating this and trying to track down the root cause, but I wanted to create an issue in case anyone else sees this.

The only change I made was updating to the latest flutter_blue_plus version. Now, I'm seeing random app crashes on iOS if the app loses connection to a paired Bluetooth device. Crashylitcs logs aren't helpful, but I'll keep updating this as I learn more.

Downgrading fixes the issue

It seems to happen every fourth lost connection. I've been unable to reproduce it when built locally, it only happens for prod builds. I also don't know if it affects Android.

Tested on iPhone 14 Pro Max

**Comment by chipweinberger** [comment]
please open a pr if you fix it

**Comment by 18723309899** [comment]
> 如果你修好了，请打开一个pr


The reason for this error is that the Kotlin version is too high. My previous version was 1.6.10 and there were no error reports. After upgrading to 1.7.0, this issue occurred. We hope the author can fix this bug as soon as possible

**Comment by chipweinberger** [comment]
please submit a PR if you want it to be fixed. thanks.

**Comment by 18723309899** [comment]
> please submit a PR if you want it to be fixed. thanks.
> 
> In not sure where kotlin version is specified, or how it relates to this bug.

I will try, but I'm not sure if I can fix it, it may take some time

**Comment by FXschwartz** [comment]
> > 如果你修好了，请打开一个pr
> 
> The reason for this error is that the Kotlin version is too high. My previous version was 1.6.10 and there were no error reports. After upgrading to 1.7.0, this issue occurred. We hope the author can fix this bug as soon as possible

So far this is only happening to me on iOS. The Kotlin version shouldn't be affecting anything like this.

**Comment by WeiKuang** [comment]
I have some issues.
It looks like a reconnection issue. But I haven't found the specific crash information.

**Comment by chipweinberger** [comment]
need a backtrack

**Comment by WeiKuang** [comment]
I get crash info.
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Application Specific Information:
abort() called


Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1e4d3e558 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x205b83118 pthread_kill + 268
2   libsystem_c.dylib             	       0x1ad37bc04 __abort + 128
3   libsystem_c.dylib             	       0x1ad323184 abort + 192
4   libc++abi.dylib               	       0x205ac1bf8 abort_message + 132
5   libc++abi.dylib               	       0x205ab1444 demangling_terminate_handler() + 348
6   libobjc.A.dylib               	       0x19eea1ea4 _objc_terminate() + 144
7   libc++abi.dylib               	       0x205ac0fbc std::__terminate(void (*)()) + 16
8   libc++abi.dylib               	       0x205ac0f60 std::terminate() + 56
9   libdispatch.dylib             	       0x1ad2c2ec0 _dispatch_client_callout + 40
10  libdispatch.dylib             	       0x1ad2d16a4 _dispatch_main_queue_drain + 928
11  libdispatch.dylib             	       0x1ad2d12f4 _dispatch_main_queue_callback_4CF + 44
12  CoreFoundation                	       0x1a5e8bc28 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
13  CoreFoundation                	       0x1a5e6d560 __CFRunLoopRun + 1992
14  CoreFoundation                	       0x1a5e723ec CFRunLoopRunSpecific + 612
15  GraphicsServices              	       0x1e130f35c GSEventRunModal + 164
16  UIKitCore                     	       0x1a81ff6e8 -[UIApplication _run] + 888
17  UIKitCore                     	       0x1a81ff34c UIApplicationMain + 340
18  Runner                        	       0x1001a9b38 main + 64
19  dyld                          	       0x1c534adec start + 2220

Thread 1 name:  com.apple.uikit.eventfetch-thread
Thread 1:
0   libsystem_kernel.dylib        	       0x1e4d37c84 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1e4d4ab54 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1e4d4ae2c mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x1e4d381c8 mach_msg + 24
4   CoreFoundation                	       0x1a5e6c024 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a5e6d250 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a5e723ec CFRunLoopRunSpecific + 612
7   Foundation                    	       0x1a00f2fd4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8   Foundation                    	       0x1a00f2ebc -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9   UIKitCore                     	       0x1a83323fc -[UIEventFetcher threadMain] + 416
10  Foundation                    	       0x1a010c544 __NSThread__start__ + 716
11  libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
12  libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 2 name:  io.flutter.1.ui
Thread 2:
0   libsystem_kernel.dylib        	       0x1e4d37c84 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1e4d4ab54 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1e4d4ae2c mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x1e4d381c8 mach_msg + 24
4   CoreFoundation                	       0x1a5e6c024 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a5e6d250 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a5e723ec CFRunLoopRunSpecific + 612
7   Flutter                       	       0x1009e254c 0x1006fc000 + 3040588
8   Flutter                       	       0x1009e203c 0x1006fc000 + 3039292
9   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 3 name:  io.flutter.1.raster
Thread 3:
0   libsystem_kernel.dylib        	       0x1e4d37c84 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1e4d4ab54 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1e4d4ae2c mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x1e4d381c8 mach_msg + 24
4   CoreFoundation                	       0x1a5e6c024 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a5e6d250 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a5e723ec CFRunLoopRunSpecific + 612
7   Flutter                       	       0x1009e254c 0x1006fc000 + 3040588
8   Flutter                       	       0x1009e203c 0x1006fc000 + 3039292
9   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 4 name:  io.flutter.1.io
Thread 4:
0   libsystem_kernel.dylib        	       0x1e4d37c84 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1e4d4ab54 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1e4d4ae2c mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x1e4d381c8 mach_msg + 24
4   CoreFoundation                	       0x1a5e6c024 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a5e6d250 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a5e723ec CFRunLoopRunSpecific + 612
7   Flutter                       	       0x1009e254c 0x1006fc000 + 3040588
8   Flutter                       	       0x1009e203c 0x1006fc000 + 3039292
9   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 5 name:  io.worker.1
Thread 5:
0   libsystem_kernel.dylib        	       0x1e4d38558 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x205b84078 _pthread_cond_wait + 1232
2   Flutter                       	       0x100744a60 0x1006fc000 + 297568
3   Flutter                       	       0x1009dc0cc 0x1006fc000 + 3014860
4   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 6 name:  io.worker.2
Thread 6:
0   libsystem_kernel.dylib        	       0x1e4d38558 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x205b84078 _pthread_cond_wait + 1232
2   Flutter                       	       0x100744a60 0x1006fc000 + 297568
3   Flutter                       	       0x1009dc0cc 0x1006fc000 + 3014860
4   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 7 name:  io.worker.3
Thread 7:
0   libsystem_kernel.dylib        	       0x1e4d38558 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x205b84078 _pthread_cond_wait + 1232
2   Flutter                       	       0x100744a60 0x1006fc000 + 297568
3   Flutter                       	       0x1009dc0cc 0x1006fc000 + 3014860
4   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 8 name:  io.worker.4
Thread 8:
0   libsystem_kernel.dylib        	       0x1e4d38558 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x205b84078 _pthread_cond_wait + 1232
2   Flutter                       	       0x100744a60 0x1006fc000 + 297568
3   Flutter                       	       0x1009dc0cc 0x1006fc000 + 3014860
4   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 9 name:  io.worker.5
Thread 9:
0   libsystem_kernel.dylib        	       0x1e4d38558 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x205b84078 _pthread_cond_wait + 1232
2   Flutter                       	       0x100744a60 0x1006fc000 + 297568
3   Flutter                       	       0x1009dc0cc 0x1006fc000 + 3014860
4   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 10 name:  io.worker.6
Thread 10:
0   libsystem_kernel.dylib        	       0x1e4d38558 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x205b84078 _pthread_cond_wait + 1232
2   Flutter                       	       0x100744a60 0x1006fc000 + 297568
3   Flutter                       	       0x1009dc0cc 0x1006fc000 + 3014860
4   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 11 name:  dart:io EventHandler
Thread 11:
0   libsystem_kernel.dylib        	       0x1e4d395bc kevent + 8
1   Flutter                       	       0x100bd37e0 0x1006fc000 + 5076960
2   Flutter                       	       0x100c02780 0x1006fc000 + 5269376
3   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
4   libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 12 name:  io.jiguang.hxhg.cache
Thread 12:
0   libsystem_kernel.dylib        	       0x1e4d37c84 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1e4d4ab54 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1e4d4ae2c mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x1e4d381c8 mach_msg + 24
4   CoreFoundation                	       0x1a5e6c024 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a5e6d250 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a5e723ec CFRunLoopRunSpecific + 612
7   CoreFoundation                	       0x1a5eb4ea4 CFRunLoopRun + 64
8   Runner                        	       0x10024b180 0x1001a4000 + 684416
9   Foundation                    	       0x1a010c544 __NSThread__start__ + 716
10  libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
11  libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 13 name:  org.hxhg.jiguang.thread
Thread 13:
0   Foundation                    	       0x1a00c6b44 newJSONString + 264
1   Foundation                    	       0x1a014baa8 newJSONObject + 464
2   Foundation                    	       0x1a014baa8 newJSONObject + 464
3   Foundation                    	       0x1a014c56c newJSONValue + 496
4   Foundation                    	       0x1a014bb10 newJSONObject + 568
5   Foundation                    	       0x1a014c56c newJSONValue + 496
6   Foundation                    	       0x1a014c790 newJSONValue + 1044
7   Foundation                    	       0x1a0123584 -[_NSJSONReader parseData:options:error:] + 1096
8   Runner                        	       0x10020b278 0x1001a4000 + 422520
9   Runner                        	       0x100252f18 0x1001a4000 + 716568
10  Runner                        	       0x100252da4 0x1001a4000 + 716196
11  Foundation                    	       0x1a00ec7ac __NSThreadPerformPerform + 264
12  CoreFoundation                	       0x1a5ec6128 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
13  CoreFoundation                	       0x1a5ed27b4 __CFRunLoopDoSource0 + 176
14  CoreFoundation                	       0x1a5e575e8 __CFRunLoopDoSources0 + 244
15  CoreFoundation                	       0x1a5e6d0d4 __CFRunLoopRun + 828
16  CoreFoundation                	       0x1a5e723ec CFRunLoopRunSpecific + 612
17  Foundation                    	       0x1a00f2fd4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
18  Foundation                    	       0x1a00f2e68 -[NSRunLoop(NSRunLoop) run] + 64
19  Runner                        	       0x1001d41d4 0x1001a4000 + 197076
20  Foundation                    	       0x1a010c544 __NSThread__start__ + 716
21  libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
22  libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 14 name:  io.jiguang.hxhg.network
Thread 14:
0   libsystem_kernel.dylib        	       0x1e4d37c84 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1e4d4ab54 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1e4d4ae2c mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x1e4d381c8 mach_msg + 24
4   CoreFoundation                	       0x1a5e6c024 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a5e6d250 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a5e723ec CFRunLoopRunSpecific + 612
7   CoreFoundation                	       0x1a5eb4ea4 CFRunLoopRun + 64
8   Runner                        	       0x1001e52d8 0x1001a4000 + 266968
9   Foundation                    	       0x1a010c544 __NSThread__start__ + 716
10  libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
11  libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 15 name:  com.apple.CFSocket.private
Thread 15:
0   libsystem_kernel.dylib        	       0x1e4d387e8 __select + 8
1   CoreFoundation                	       0x1a5ebb99c __CFSocketManager + 636
2   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
3   libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 16 name:  com.apple.NSURLConnectionLoader
Thread 16:
0   libsystem_kernel.dylib        	       0x1e4d37c84 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1e4d4ab54 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1e4d4ae2c mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x1e4d381c8 mach_msg + 24
4   CoreFoundation                	       0x1a5e6c024 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a5e6d250 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a5e723ec CFRunLoopRunSpecific + 612
7   CFNetwork                     	       0x1a705d580 0x1a6e04000 + 2463104
8   Foundation                    	       0x1a010c544 __NSThread__start__ + 716
9   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
10  libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8

Thread 17:
0   libsystem_pthread.dylib       	       0x205b7cb74 start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib       	       0x205b7cb74 start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib       	       0x205b7cb74 start_wqthread + 0

Thread 20:
0   libsystem_pthread.dylib       	       0x205b7cb74 start_wqthread + 0

Thread 21:
0   libsystem_pthread.dylib       	       0x205b7cb74 start_wqthread + 0

Thread 22:
0   libsystem_pthread.dylib       	       0x205b7cb74 start_wqthread + 0

Thread 23:
0   libsystem_pthread.dylib       	       0x205b7cb74 start_wqthread + 0

Thread 24:
0   libsystem_pthread.dylib       	       0x205b7cb74 start_wqthread + 0

Thread 25 name:  DartWorker
Thread 25:
0   libsystem_kernel.dylib        	       0x1e4d38558 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x205b840a4 _pthread_cond_wait + 1276
2   Flutter                       	       0x100d88180 0x1006fc000 + 6865280
3   Flutter                       	       0x100dc21cc 0x1006fc000 + 7102924
4   Flutter                       	       0x100d87b4c 0x1006fc000 + 6863692
5   libsystem_pthread.dylib       	       0x205b7d6b8 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x205b7cb88 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000989680   x6: 0x0000000000000072   x7: 0x0000000000000cd0
    x8: 0x7e7ebfac76c90b1c   x9: 0x7e7ebfad8aa7cfdc  x10: 0x00000000000003e8  x11: 0x000000000000000c
   x12: 0x000000000000000c  x13: 0x00000000001ff800  x14: 0x00000000000007fb  x15: 0x0000000086a3a07e
   x16: 0x0000000000000148  x17: 0x00000001fc6ec4c0  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x00000001fc6ec5a0  x22: 0x0000000000000000  x23: 0x0000000000000114
   x24: 0x0000000000000000  x25: 0x00000001fc6ec5a0  x26: 0x0000000282724240  x27: 0x000000000000000f
   x28: 0x0000000000000000   fp: 0x000000016fc5a640   lr: 0x0000000205b83118
    sp: 0x000000016fc5a620   pc: 0x00000001e4d3e558 cpsr: 0x40001000
   far: 0x0000000280918000  esr: 0x56000080  Address size fault

Binary Images:
       0x1001a4000 -        0x1002fbfff Runner arm64  <5a4e6c116d5a3310a7744e7f87159534> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Runner
       0x100410000 -        0x10041ffff FMDB arm64  <74f1212bdbd735c6bad28013054f13d3> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/FMDB.framework/FMDB
       0x10043c000 -        0x100447fff MTBBarcodeScanner arm64  <05e5e9bda0273d4ab1701ece95664c41> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/MTBBarcodeScanner.framework/MTBBarcodeScanner
       0x10045c000 -        0x100463fff device_info_plus arm64  <b2d0ab56884a386e864ef54f816ca701> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/device_info_plus.framework/device_info_plus
       0x100470000 -        0x10047ffff flutter_blue_plus arm64  <26e3aa71728739efbb3a779f4b90647a> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/flutter_blue_plus.framework/flutter_blue_plus
       0x100494000 -        0x10049ffff flutter_local_notifications arm64  <f6805001fcdc3d4d955cc90f5166f500> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/flutter_local_notifications.framework/flutter_local_notifications
       0x1004b4000 -        0x1004c7fff image_picker_ios arm64  <1a0e822560923d7e9dd85d67ce1a9a7a> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/image_picker_ios.framework/image_picker_ios
       0x1004ec000 -        0x1004f3fff package_info_plus arm64  <dc14b18c9456353397aa52fd2fe7d371> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/package_info_plus.framework/package_info_plus
       0x100500000 -        0x10050bfff path_provider_foundation arm64  <e9373114ecb73d6f89d56a509cfb4241> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/path_provider_foundation.framework/path_provider_foundation
       0x100520000 -        0x10052ffff qr_code_scanner arm64  <f0442bde0924345c9a253e40e0af2e06> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/qr_code_scanner.framework/qr_code_scanner
       0x100550000 -        0x10055bfff share_plus arm64  <16b0e6cef746310ab929de94ef19797b> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/share_plus.framework/share_plus
       0x10056c000 -        0x100577fff shared_preferences_foundation arm64  <6ad712fc0a363fb891fc57930653a78b> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/shared_preferences_foundation.framework/shared_preferences_foundation
       0x100590000 -        0x10059ffff sqflite arm64  <5d2334c3f52330e9a5732cce687a0f2b> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/sqflite.framework/sqflite
       0x1005b8000 -        0x1005bffff url_launcher_ios arm64  <bec3a9f72f113860992375cb4101d6a9> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/url_launcher_ios.framework/url_launcher_ios
       0x1005d0000 -        0x1005dbfff vibration arm64  <8047edebc74a3fca8bcd45359bfb521f> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/vibration.framework/vibration
       0x100680000 -        0x1006a3fff webview_flutter_wkwebview arm64  <9a7bd171abbf373f84ee64ef15d5be1c> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/webview_flutter_wkwebview.framework/webview_flutter_wkwebview
       0x1006fc000 -        0x100f93fff Flutter arm64  <4c4c448b55553144a1517a35ce73c4aa> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/Flutter.framework/Flutter
       0x101350000 -        0x10135bfff libobjc-trampolines.dylib arm64e  <695a8449aae838b6851cced0b1176f03> /private/preboot/Cryptexes/OS/usr/lib/libobjc-trampolines.dylib
       0x107b04000 -        0x1085dffff App arm64  <6e0665330ab63b83abab74f7c029393c> /private/var/containers/Bundle/Application/958A041F-52CF-4366-9955-322B747D71BF/Runner.app/Frameworks/App.framework/App
       0x1e4d37000 -        0x1e4d6eff7 libsystem_kernel.dylib arm64e  <75da6452934e3f80b181d47074378e83> /usr/lib/system/libsystem_kernel.dylib
       0x205b7c000 -        0x205b87ff3 libsystem_pthread.dylib arm64e  <56698309210a313797d414e4604b1117> /usr/lib/system/libsystem_pthread.dylib
       0x1ad306000 -        0x1ad383ff3 libsystem_c.dylib arm64e  <3548f8ee7a073b678d699c7d42096513> /usr/lib/system/libsystem_c.dylib
       0x205ab0000 -        0x205ac7fff libc++abi.dylib arm64e  <b65049d9dda43d039e130b4795138702> /usr/lib/libc++abi.dylib
       0x19ee84000 -        0x19eec7f9f libobjc.A.dylib arm64e  <085a190c621438eaaccb428c3e8afa65> /usr/lib/libobjc.A.dylib
       0x1ad2bf000 -        0x1ad305fff libdispatch.dylib arm64e  <bb347f0ef21c360782e6c8d750fdbf8c> /usr/lib/system/libdispatch.dylib
       0x1a5df3000 -        0x1a61dafff CoreFoundation arm64e  <4230c12242e8383bbeecee7b61f8bb61> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x1e130e000 -        0x1e1316fff GraphicsServices arm64e  <e830ad84d6123b6b8de7ea61a786d132> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x1a7e62000 -        0x1a9686fff UIKitCore arm64e  <b3834960244b34e49ea0ca4bb44ef0f3> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x1c5335000 -        0x1c53baa23 dyld arm64e  <6987370ac3853135a27f6731706bcbd8> /usr/lib/dyld
       0x1a00b1000 -        0x1a098efff Foundation arm64e  <6e76dc9611af3b2eb71e215f9cc6e822> /System/Library/Frameworks/Foundation.framework/Foundation
       0x1a6e04000 -        0x1a71cffff CFNetwork arm64e  <6aafe7c4f1c43020ad1670591c86d7b0> /System/Library/Frameworks/CFNetwork.framework/CFNetwork

EOF

**Comment by chipweinberger** [comment]
I dont see anything particularly specific to FBP in that. I am not able to debug it.

**Comment by chipweinberger** [comment]
It would also be useful to have the logs immediately before the crash.

Currently, I think this is not a FlutterBluePlus issue. 

Perhaps the issue is in your own code, or in the Dart VM code.

**Comment by WeiKuang** [comment]
@chipweinberger 
Yes, you are right. My problem is with my own code.

**Comment by chipweinberger** [comment]
glad you figured it out!
