### ISSUE TITLE
Devices scan doesn't work

### ISSUE THREAD

**Issue by DanielGr12** [boskokg/flutter_blue_plus#344]
Hello, I upgraded to a new computer and I downloaded the new Android Studio and Flutter SDK, I ran my app that was working on my old computer but on the new computer it doesn't show any devices even tough the code stayed exactly the same. I also tried to copy only the lib and change the permissions to the desired ones but it still didn't work. Does anyone has an idea why it happens?

**Comment by chipweinberger** [comment]
try 1.7.5+. reopen if you have problems.
