### ISSUE TITLE
not to use singleton mode

### ISSUE THREAD

**Issue by ludy520** [boskokg/flutter_blue_plus#351]
It is best not to use singleton mode, otherwise it will be troublesome to connect multiple devices at the same time

**Comment by FXschwartz** [comment]
> It is best not to use singleton mode, otherwise it will be troublesome to connect multiple devices at the same time

I don't see how using a singleton makes it troublesome to connect to multiple devices at the same time. Connecting to multiple devices at the same time is a very easy thing to do that I haven't seen any issues with.

**Comment by ludy520** [comment]
> > It is best not to use singleton mode, otherwise it will be troublesome to connect multiple devices at the same time
> 
> I don't see how using a singleton makes it troublesome to connect to multiple devices at the same time. Connecting to multiple devices at the same time is a very easy thing to do that I haven't seen any issues with.

For example, if I connect two devices at the same time and subscribe to the connection status in a single case, it is impossible to distinguish which device the current connection status belongs to.

**Comment by FXschwartz** [comment]
> For example, if I connect two devices at the same time and subscribe to the connection status in a single case, it is impossible to distinguish which device the current connection status belongs to.

It is not impossible, you can use the device and device service from the connection and each will have its own unique ID.

**Comment by MrCsabaToth** [comment]
Maybe @ludy520 is accidentally thinking about [QuickBlue](https://pub.dev/packages/quick_blue) which is actually mentioned at the top of the Flutter Blue Plus README. QuickBlue is sucha  singleton that cannot handle multiple connections (last time I looked some months ago). Flutter Blue Plus is definitely able to handle multiple devices and characteristics, I've been using it that way. Singleton pattern does not contradict that internally it can handle multiple machines and connections.

**Comment by chipweinberger** [comment]
multiple devices works fine
