### ISSUE TITLE
It doesn't read or write on android 13

### ISSUE THREAD

**Issue by mohamedsl22** [boskokg/flutter_blue_plus#352]
Hey, 
I tried the app on android 13 (pixel 6) it connects to device but doesn't read or write to it, although sometimes it works ! 
with another android version it works fine all the time! 
please help 
also tried with version 1.4.0 it doesn’t work

**Comment by mohamedsl22** [comment]
@FXschwartz 
only with android 13 I get this error when trying to read:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(discover_services_error, no instance of BluetoothGatt, have you connected first?, java.lang.Exception: no instance of BluetoothGatt, have you connected first?

**Comment by deverlex** [comment]
> @FXschwartz only with android 13 I get this error when trying to read: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(discover_services_error, no instance of BluetoothGatt, have you connected first?, java.lang.Exception: no instance of BluetoothGatt, have you connected first?

You need disconnect to blue before call to writing data
