### ISSUE TITLE
[Bug]: Autoconnect not working in Directed Advertisement

### ISSUE THREAD

**Issue by shreyasgshanbhag** [boskokg/flutter_blue_plus#353]
Environment : Android

Requirement : 
1)Connect the Application to the BLE Module. 
2)Re-Connect to the BLE Module when the application is closed and re-opened.
3)Re-Connect to the BLE Module when the BLE is reset.

When I try this with a BLE Module doing general advertisement , all my requirements are being met. I have used connect() and disconnect() functions.

When I try this with a BLE Module doing directed advertisement , requirement #1 is met where I can connect to the module, but requirement #2 & #3 are not met where I am not able to reconnect to the module after connection is lost.
I have used connect() followed by pair() for pairing and disconect() functions.

**Comment by MrCsabaToth** [comment]
What happens, do you get any error messages? A lot more info is needed.
(Make sure about one thing: while your app is disconnected from the BT device, if something else connects to that BT device that will keep it occupied and possibly won't show up for your app when you try to reconnect.)

**Comment by chipweinberger** [comment]
is this still a problem? Let me know, otherwise I will close.

I did recently fix an autoconnect bug on android.
