### ISSUE TITLE
scanning: Android 12 after Disconnect device not found in later scans

### ISSUE THREAD

**Issue by Narayanhegde14** [boskokg/flutter_blue_plus#357]
In Android version 12 when we do `flutterBluePlus.disconnect()`  connection listener gives `disconnected` update.

But when I do rescan that device is not in the scan result.

This issue is there in only Android 12, I have checked in Android 11 its working fine.

**Comment by shawsa-artc** [comment]
same issue here.

**Comment by chipweinberger** [comment]
try version 1.7.1

**Comment by MrCsabaToth** [comment]
What about Android 13?

**Comment by chipweinberger** [comment]
Also, its possible that your device has stopped sending advertisements after the first connection.

**Comment by chipweinberger** [comment]
Closing this issue.

I assume this is because your device stopped advertising. 

Some BLE devices only advertise at startup, stop advertising after connection, and never advertise again.
