### ISSUE TITLE
FormatException: The format is invalid

### ISSUE THREAD

**Issue by Mark1850** [boskokg/flutter_blue_plus#359]
We have found this error using some android 8 and previous Samsung devices.
We found this error during the discovery services when some serviceUuid is an empty string.
We thought to add a default all zeros uuid in the Guid._fromString for fix the issue:

`if(input.isEmpty) input = "00000000-0000-0000-0000-000000000000";`

It's possible to add this check in the official library code?
Thank you and best regards.

**Comment by chipweinberger** [comment]
Please open a PR! thanks.

**Comment by chipweinberger** [comment]
fixed in 1.7.0
