### ISSUE TITLE
PlatformException(connect, Peripheral not found, null)

### ISSUE THREAD

**Issue by WeiKuang** [boskokg/flutter_blue_plus#36]
My flow was:

1、Init & scan etc
2、Connect device
3、Discover services & Characteristics etc
4、Do stuff
5、Disconnect all BT devices
6、Resume app
7、Init and scan etc

[https://github.com/pauldemarco/flutter_blue/issues/497](url)

**Comment by toxamontsg** [comment]
Similar problem. I plug in the device and everything works fine. I added automatic reconnect to ios [3f5b937](https://github.com/boskokg/flutter_blue/pull/10/commits/3f5b9378077b71f3f2ceda8c743b634a1892702e) and when reconnecting, this error pops up.

**Comment by WeiKuang** [comment]
I found the problem. The reason is because when Bluetooth starts scanning, if the scan result is monitored immediately, an exception will be thrown in the ios file. This problem does not appear at the beginning of the scan, but only when the bluetooth is disconnected and re-scanned to connect.

**Comment by mevluttosun** [comment]
I've still same issue. Maybe I am using proto to connect device. In android I have no issue but in my test device IOS 12.5.5, ( I hadn't try with another device) always giving same PlatformException(connect, Peripheral not found, null, null)

Here is my proto extention

extension BluetoothDeviceExtension on BluetoothDeviceModel { BluetoothDevice toBluetoothDevice() { proto.BluetoothDevice p = proto.BluetoothDevice.create(); 
p.name = name; 
p.type = proto.BluetoothDevice_Type.LE;
p.remoteId = id; 
return BluetoothDevice.fromProto(p);
 } }

Here is my connect method

Future<void> connect(bool autoConnect) async { 
log.fine('connecting'); 
emit(const BluetoothModelDeviceState.connecting());
final bluetoothDevice = device.toBluetoothDevice();
await bluetoothDevice .connect( autoConnect: autoConnect, ) 
.onError((error, stackTrace) => log.warning('Connection Error ${error.toString()}')); }

**Comment by WeiKuang** [comment]
me too

**Comment by WeiKuang** [comment]
iOS is not working from proto

**Comment by ryanhz** [comment]
> I found the problem. The reason is because when Bluetooth starts scanning, if the scan result is monitored immediately, an exception will be thrown in the ios file. This problem does not appear at the beginning of the scan, but only when the bluetooth is disconnected and re-scanned to connect.

This is not the reason and cause of the problem, this issue should not be closed

**Comment by keskink** [comment]
Hello friends. I fixed the "peripheral not found" issue.
Now I can connect/reconnect to the device without scanning, also for iOS.
this plugin can already connect without scanning on Android.

I can share my solution with plugin owners.
