### ISSUE TITLE
requestMtu() not return on version 1.6.1

### ISSUE THREAD

**Issue by zhxst** [boskokg/flutter_blue_plus#360]
The code below not return on version 1.6.1
It was fine on 1.5.2 and below.
The target device is a embedded system with bluetooth chip.

``` dart
if (Platform.isAndroid) {
     await tDevice.requestMtu(209);
}
```

It seems work at the first time. but after that,  the `await` never returns.

**Comment by chipweinberger** [comment]
fix merged https://github.com/boskokg/flutter_blue_plus/commit/267427b372e0610a02c20c8614e9f99a8ccad057
