### ISSUE TITLE
About iOS Peripheral not found issue fixed.

### ISSUE THREAD

**Issue by WeiKuang** [boskokg/flutter_blue_plus#366]
there is a bug in PR iOS Peripheral not found issue fixed.
When peripheral is null,it not run next method.
![20230711142646](https://github.com/boskokg/flutter_blue_plus/assets/12131724/1c24b427-d961-4b70-a5b9-a32e4b579979)
![20230711142709](https://github.com/boskokg/flutter_blue_plus/assets/12131724/c07147b5-fc81-493f-85f6-456bcdbfc275)

**Comment by chipweinberger** [comment]
thanks for reporting!

**Comment by chipweinberger** [comment]
should be fixed in 1.7.1
