### ISSUE TITLE
Mobile Receipt Printer not found (Bixolon SPP-R200III)

### ISSUE THREAD

**Issue by leutbounpaseuth** [boskokg/flutter_blue_plus#367]
HI,

I use this printer and I'm able to pair the device properly on Android device.

Trying to discover the bluetooth mobile printer but it is not listed in the scan results.

Any idea ?

**Comment by chipweinberger** [comment]
please try version 1.7.0

**Comment by leutbounpaseuth** [comment]
Updated with 1.7.3 but I have compile problem now.

https://github.com/boskokg/flutter_blue_plus/issues/369#issuecomment-1637532089

**Comment by leutbounpaseuth** [comment]
Found the problem, seems that blue_print_pos package uses your old package.
https://github.com/boskokg/flutter_blue_plus/issues/369#issuecomment-1637709805

But my printer is still not listed :(

**Comment by chipweinberger** [comment]
The issue is likely that your Printer is not discoverable. Are other BLE scanner apps from the App Store finding it?
