### ISSUE TITLE
ACCESS_FINE_LOCATION - PlatformException - Version 1.7.1 - Android 13

### ISSUE THREAD

**Issue by cedar-yxs** [boskokg/flutter_blue_plus#370]
When I run example app, then I click search button, I had an error
Logs as below:
```
E/flutter ( 5612): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(startScan, FlutterBluePlus requires android.permission.ACCESS_FINE_LOCATION permission, null, null)
E/flutter ( 5612): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 5612): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter ( 5612): <asynchronous suspension>
E/flutter ( 5612): #2      FlutterBluePlus.scan (package:flutter_blue_plus/src/flutter_blue_plus.dart:189:7)
E/flutter ( 5612): <asynchronous suspension>
```

I run it with flutter 3.7.12 and 3.10.6. I had the same error

The action button is 'TURN OFF'. I hit the button and nothing happened

**Comment by chipweinberger** [comment]
perhaps we/you need to update the permissions here

https://github.com/boskokg/flutter_blue_plus/blob/master/example/android/app/src/main/AndroidManifest.xml

**Comment by huayun502** [comment]
me too,I update the permissions,but not working - Android 13

**Comment by chipweinberger** [comment]
it may be due to this

https://github.com/boskokg/flutter_blue_plus/commit/c0b1de652b141a5962477b48d6cd6de757fa36f0

perhaps you can add breakpoints and debug if the permission is being requested

**Comment by huayun502** [comment]
E/flutter (15423): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(startScan, FlutterBluePlus requires android.permission.ACCESS_FINE_LOCATION permission, null, null)
E/flutter (15423): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
E/flutter (15423): #1      MethodChannel._invokeMethod
platform_channel.dart:310
E/flutter (15423): <asynchronous suspension>
E/flutter (15423): #2      FlutterBluePlus.scan
flutter_blue_plus.dart:189
E/flutter (15423): <asynchronous suspension>

**Comment by chipweinberger** [comment]
you can also try reverting this commit: https://github.com/boskokg/flutter_blue_plus/commit/8a35c6a0b6aca2fe23e5cd3730b7d3cf7903437c

**Comment by chipweinberger** [comment]
or setting this permission: <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />

**Comment by a371057600** [comment]
> you can also try reverting this commit: [8a35c6a](https://github.com/boskokg/flutter_blue_plus/commit/8a35c6a0b6aca2fe23e5cd3730b7d3cf7903437c)
> 
> or perhaps setting this permission: `<uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation" />`
> 
> to be honest, I'm not sure what the fix is.
There's still no way to fix it

**Comment by a371057600** [comment]
update the permissions,but not working  in Android 13

**Comment by FritzMatthaeus** [comment]
I have made a pull request to fix this

**Comment by FritzMatthaeus** [comment]
I just double checked it. Version 1.7.3 throws a PlatformException on Android 13 without ACCESS_FINE_LOCATION

```
 Unhandled Exception: PlatformException(startScan, FlutterBluePlus requires android.permission.ACCESS_FINE_LOCATION permission, null, null)
```

I have been using this package for more than a year and i checked my project history. I had issues with Android 13 about 6 month ago and could fix it by adding
```
<uses-permission android:name="android.permission.BLUETOOTH_SCAN"
                     android:usesPermissionFlags="neverForLocation" />
<uses-permission android:name="android.permission.NEARBY_DEVICES"/>
```
I used flutter_blue_plus Version 1.4.0 at that time and did not need the ACCESS_FINE_LOCATION permission. So this exception might be a regression.

**Comment by FritzMatthaeus** [comment]
I am no Java expert, but it seems to me that the changes in "startScan" in the onMethodCall method in dynamically handling the permissions for >= Android Version 31 might be at the origin for this issue.

**Comment by FritzMatthaeus** [comment]
I have just checked Version 1.4.0 and there we already had the ACCESS_FINE_LOCATION but without maxSDK Restriction. It is commented as legacy, but obviously it kept the package working on Android 13.

```
    <!-- New Bluetooth permissions in Android 12
           https://developer.android.com/about/versions/12/features/bluetooth-permissions
      -->
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

    <!-- Request legacy Bluetooth permissions on older devices. -->
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

Seems to me as if ACCESS_FINE_LOCATION always has been required.

**Comment by FritzMatthaeus** [comment]
@chipweinberger: You were right on the permissions, but the package always requested this permission as the 
androidUsesFineLocation flag defaulted to true in the scan and startScan method.

I've made a pull request to fix this and updated the readMe and commentation

**Comment by chipweinberger** [comment]
thanks for the high quality PR!

**Comment by chipweinberger** [comment]
It looks like there is a discrepancy here? Should `android/src/main/AndroidManifest.xml` have `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="30"/>` as well?

<img width="1008" alt="Screenshot 2023-07-18 at 12 38 53 AM" src="https://github.com/boskokg/flutter_blue_plus/assets/1863934/6c34d5c2-dce4-4ceb-a700-c98fe9f82965">

**Comment by FritzMatthaeus** [comment]
Yeah, i did miss that. Sorry. Though it is not actually needed as the example worked fine on my device this way. But for better unterstanding, i would add it this way: 
```
<!-- remove the maxSdkVersion restriction to access location information via Bluetooth on Android Version >=31 -->
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="30"/>
```

**Comment by chipweinberger** [comment]
would be great if you could update your branch. easier than me doing it.  no worries either way

**Comment by FritzMatthaeus** [comment]
No problem, i added it to my pull request

**Comment by chipweinberger** [comment]
Please try 1.7.7+. reopen a new issue if you still have problems.
