### ISSUE TITLE
Characteristic Properties Always true

### ISSUE THREAD

**Issue by kvery** [boskokg/flutter_blue_plus#371]
bluetooth_msgs.dart
![image](https://github.com/boskokg/flutter_blue_plus/assets/66050871/3206327a-795a-4a0b-a831-9e477ce96d7d)
MessageMaker.java
![image](https://github.com/boskokg/flutter_blue_plus/assets/66050871/64fba665-e661-4325-9adc-643b0d8f1f26)

The value of HashMap in Java files is always Boolean,
So the code in DART is JSON ["xxx"] != 0 will always be true,
It should be removed "!= 0"

**Comment by rahul-yr** [comment]
Even I am facing this issue.

**Comment by chipweinberger** [comment]
yes you are correct. will fix.

**Comment by chipweinberger** [comment]
fixed: 61f8840ad76e5a958e5338cc57f2795e3f6fda03
