### ISSUE TITLE
Tried to call ScanResult on closed channel

### ISSUE THREAD

**Issue by Eashubh128** [boskokg/flutter_blue_plus#372]
I used workmanager to schedule a scan in background , but instead got this "Tried to call ScanResult on closed channel"

**Comment by chipweinberger** [comment]
this is fixed in 1.7.7.

**Comment by chipweinberger** [comment]
more info is needed. where does this log come from? android? ios? version?

**Comment by Eashubh128** [comment]
Android , and the flutter version is 3.10.4 , when i used background service instead of workmanager it was solved

**Comment by chipweinberger** [comment]
great. glad you found the issue.
