### ISSUE TITLE
ACCESS_FINE_LOCATION Exception

### ISSUE THREAD

**Issue by ariantlk** [boskokg/flutter_blue_plus#373]
Same issue after updating the flutter_blue_plus to 1.7.1. I double checked the permissions but it seams it's due to ACCESS_FINE_LOCATION becoming optional.

**Comment by chipweinberger** [comment]
please open a PR if you can fix it

**Comment by chipweinberger** [comment]
duplicate issue: https://github.com/boskokg/flutter_blue_plus/issues/370
