### ISSUE TITLE
StreamBuilder<BluetoothState> is not updated by BT on/off changes 

### ISSUE THREAD

**Issue by talitshak** [boskokg/flutter_blue_plus#378]
flutter_blue_plus 1.7.4
 (tested on android)
 
 Followed the example code, but getting no changes:
 
     ```
return Scaffold(
            appBar: AppBar(
              title: const Text('Bluetooth'),
            ),
            body: StreamBuilder<BluetoothState>(
              stream: FlutterBluePlus.instance.state,
              initialData: BluetoothState.unknown,
              builder: (context, snapshot) {
                final state = snapshot.data;
                if (state == BluetoothState.on) {
                  return BluetothOnScreen()
                  .........
```
              
              
 added needed permission:
  
    <uses-feature android:required="true" android:name="android.hardware.bluetooth_le"/>
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30"/>
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE"/>
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
              
what might be the reason?
thanks

**Comment by chipweinberger** [comment]
Just pushed a fix. try master branch. 709ab810dc70a53a1a2405df7c38530c22f48a10

**Comment by talitshak** [comment]
Thanks, now it does work but device.connect does not for some reason

**Comment by chipweinberger** [comment]
please open a new issue
