### ISSUE TITLE
iOS can't read descriptors value, works perfect for Android.

### ISSUE THREAD

**Issue by abcdggs** [boskokg/flutter_blue_plus#38]
As the title suggests I am trying to read the value of descriptors for characteristics. This works fine on android but doesn't seem to work for iOS. Has anyone experienced or overcome this issue?

**Comment by janleskovec** [comment]
It might be related to this issue: https://github.com/pauldemarco/flutter_blue/issues/760 .
If the device is already connected or paired, you can't seem to be able to discover services.

**Comment by unitedsoftworks** [comment]
currently facing this issue on iOS and not android.

**Comment by AymenXD** [comment]
same goes for me, this is an example:

Android (works fine):
![android](https://user-images.githubusercontent.com/41294956/221299925-ada365a2-edd4-4626-bc3a-c798f75d2ff2.png)

iOS:
![ios](https://user-images.githubusercontent.com/41294956/221299930-12868366-ad0c-4753-9631-78fa2831cd05.png)

**Comment by jojoX94** [comment]
Same issue on iOS.

**Comment by chipweinberger** [comment]
Please try 1.7.6+. reopen a new issue if you still have problems.

And feel free to open a PR.
