### ISSUE TITLE
【Android】"characteristic.value.listen((value)" does't have any callback.

### ISSUE THREAD

**Issue by wanxiao** [boskokg/flutter_blue_plus#381]
c1.setNotify(true);
c1.value.listen((value){
print("callback");
});

c2.write(data);

On Android , it does't have any callback.

**BUT not every characteristic has the same problem**.

I have two characteristics for receiving notifications, one gets notifications, one doesn't.

This problem occurs in v1.7.x and does not occur in v1.6.1, which was forked earlier.
However on v1.6.1, Android 12 cannot return scan results.
Is there no release for 1.6.x?

**Comment by chipweinberger** [comment]
please open a PR if you fix it, and we'll update 1.7.x

**Comment by shawsa-artc** [comment]
I was facing the same problem, managed to solved it.
It occurs when you are trying to subscribing to multiple characteristics at same time.
You need to surround each with a try catch

          try {
            await c.setNotifyValue(true);
            // set listener for changes
            c.value.listen((value) {
              //print('2a37: ${value.toString()}');
              getHRM = value[1];
            });
          } catch (error) {
            // Handle the error
            //print('Error occurred while setting notify value: $error');
          }

**Comment by MrCsabaToth** [comment]
"does't have any callback" means that the listener callback function is not called, so the second listener is mute?

**Comment by chipweinberger** [comment]
seems like same issue: https://github.com/boskokg/flutter_blue_plus/issues/329

**Comment by chipweinberger** [comment]
Note, calling `write()` DOES NOT cause `lastValueStream`, `lastValue`, or `onValueReceived` to be updated. This is by design. 

Reads are treated very separately from writes in many BLE protocols, so we cannot treat a write as "setting" the read value.

**Comment by chipweinberger** [comment]
please open a new if it still occurs on the latest releases.
