### ISSUE TITLE
discover_services_error

### ISSUE THREAD

**Issue by Akiitp** [boskokg/flutter_blue_plus#383]
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(discover_services_error, no instance of BluetoothGatt, have you connected first?, java.lang.Exception: no instance of BluetoothGatt, have you connected first?`

this issues occurs when my devices is connected state.
I am using flutter blue plus-flutter_blue_plus: **^1.5.2** 
this issues occurs in both android as well as IOS

**Comment by chipweinberger** [comment]
please open a pr if you fix it.

btw, don't forget to include basic information like android/ios and which version of this library you are using.

**Comment by MrCsabaToth** [comment]
Is this in a code which worked fine with pre 1.7.0 Flutter Blue Plus versions by any chance?

**Comment by chipweinberger** [comment]
try 1.8.4

**Comment by chipweinberger** [comment]
Any updates? There have been some bugs in the adapterState, so I think this is fixed now. Please reopen the issue if you still see problems in 1.10.3+
