### ISSUE TITLE
Bluetooth permission ask on start up in ios 

### ISSUE THREAD

**Issue by divyaEncodework** [boskokg/flutter_blue_plus#388]
@boskokg 
when I start my application in ios Bluetooth permission is asked on startup but I need Bluetooth on only one screen how can I manage it?
if anyone has a solution please update me
thank you

**Comment by chipweinberger** [comment]
just make sure not to call any FlutterBluePlus code until needed and it should work i think.

**Comment by chipweinberger** [comment]
not sure. try looking at the device logs using a Macbook and opening Console.app.

**Comment by divyaEncodework** [comment]
i cant find any Bluetooth services in logs and I am not using it in start up

**Comment by chipweinberger** [comment]
perhaps you permissions plist has issues? try removing the bluetooth permission and see what happens.

**Comment by divyaEncodework** [comment]
but I need Bluetooth permissions on another screen

**Comment by chipweinberger** [comment]
I know. But temporarily remove the permission to help troubleshoot. Perhaps you need to specify something else.

**Comment by divyaEncodework** [comment]
if I remove permission then my app crashes on my iPhone with the message that app is trying to access data without permission

**Comment by chipweinberger** [comment]
let me know if you fix it.

This might happen when we instantiate the CBCentralManager.

Try searching the code and try commenting those lines out and seeing what happens.

**Comment by chipweinberger** [comment]
did you figure it out?

**Comment by divyaEncodework** [comment]
no,
precisely that's because of CBCentralManager.
but I don't know which file I have to change.

**Comment by chipweinberger** [comment]
The CBCentralManager is only invoked if you interact with FlutterBluePlus.

If you see any logs like:

`2023-07-24 21:29:14.845 macos[72103:5766776] [FBP-iOS] handleMethodCall: XXXXXXXX`

Then the problem is in your code. You should not be calling any FlutterBluePlus functions at all.

**Comment by divyaEncodework** [comment]
no, I am not using any flutterBluePlus functions and not receiving logs like this

**Comment by chipweinberger** [comment]
Have you tried commenting out all of your flutterBluePlus code?

Try temporarily deleting all flutterBluePlus code for your app.

**Comment by divyaEncodework** [comment]
I can't do this 
it's a live project
we need it for device configurations.

**Comment by chipweinberger** [comment]
?  I am not asking for you to save the changes.

**Comment by divyaEncodework** [comment]
I comment out all the code and run the application
Bluetooth permission dialogue still occurs.

**Comment by divyaEncodework** [comment]
ok, I found that this dialogue is not because of your plugin.
thank you.

**Comment by chipweinberger** [comment]
glad you figured it out!
