### ISSUE TITLE
Unhandled Exception: Exception: PlatformException(read_characteristic_error, unknown reason, may occur if readCharacteristic was called before last read finished., null, null)

### ISSUE THREAD

**Issue by iresolveservices** [boskokg/flutter_blue_plus#389]
> E/flutter (15606): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: PlatformException(read_characteristic_error, unknown reason, may occur if readCharacteristic was called before last read finished., null, null) #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
> E/flutter (15606): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
> E/flutter (15606): <asynchronous suspension>
> E/flutter (15606): #2      BluetoothCharacteristic.read.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:111:7)
> E/flutter (15606): <asynchronous suspension>
> E/flutter (15606): #3      _Mutex.synchronized (package:flutter_blue_plus/src/utils.dart:314:7)
> E/flutter (15606): <asynchronous suspension>
> E/flutter (15606): #4      BluetoothCharacteristic.read (package:flutter_blue_plus/src/bluetooth_characteristic.dart:85:5)
> E/flutter (15606): <asynchronous suspension>
> E/flutter (15606): 
> E/flutter (15606): #0      BluetoothCharacteristic.read.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:124:7)
> E/flutter (15606): #1      _RootZone.runBinary (dart:async/zone.dart:1666:54)
> E/flutter (15606): #2      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
> E/flutter (15606): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
> E/flutter (15606): #4      Future._propagateToListeners (dart:async/future_impl.dart:817:13)
> E/flutter (15606): #5      Future._completeError (dart:async/future_impl.dart:592:5)
> E/flutter (15606): #6      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:683:7)
> E/flutter (15606): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
> E/flutter (15606): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
> E/flutter (15606): 
>

**Comment by chipweinberger** [comment]
read errors can happen for many reasons.
- connection lost
- read is not supported by the ble device
- ble device returned an error during read
- radio interference

you cannot fix this. you must handle the exception.

**Comment by iresolveservices** [comment]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: PlatformException(read_characteristic_error, unknown reason, may occur if readCharacteristic was called before last read finished., null, null) #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 8133): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 8133): <asynchronous suspension>
E/flutter ( 8133): #2      BluetoothCharacteristic.read.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:111:7)
E/flutter ( 8133): <asynchronous suspension>
E/flutter ( 8133): #3      _Mutex.synchronized (package:flutter_blue_plus/src/utils.dart:311:7)
E/flutter ( 8133): <asynchronous suspension>
E/flutter ( 8133): #4      BluetoothCharacteristic.read (package:flutter_blue_plus/src/bluetooth_characteristic.dart:85:5)
E/flutter ( 8133): <asynchronous suspension>
E/flutter ( 8133): 
E/flutter ( 8133): #0      BluetoothCharacteristic.read.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:124:7)
E/flutter ( 8133): #1      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter ( 8133): #2      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter ( 8133): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
E/flutter ( 8133): #4      Future._propagateToListeners (dart:async/future_impl.dart:817:13)
E/flutter ( 8133): #5      Future._completeError (dart:async/future_impl.dart:592:5)
E/flutter ( 8133): #6      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:683:7)
E/flutter ( 8133): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 8133): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 8133):

**Comment by iresolveservices** [comment]
> read errors can happen for many reasons.
> 
> * connection lost during read
> * read is not supported by the ble device
> * ble device returned an error during read
> * radio interference
> 
> you cannot 100% fix this. you must handle the exception.

ok let me check

**Comment by iresolveservices** [comment]
D/FlutterBluePlugin(16663): [onReadRemoteRssi] rssi: -50 status: 0
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a00-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00001800-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
D/BluetoothGatt(16663): onConnectionUpdated() - Device=@@:@@:$$:%%:&&:## interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(16663): onConnectionUpdated() - Device=@@:@@:$$:%%:&&:## interval=39 latency=0 timeout=500 status=0
D/BluetoothGatt(16663): readRssi() - device: @@:@@:$$:%%:&&:##
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a01-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00001800-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a18-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00001808-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: false, writeWithoutResponse: false, write: false, notify: true, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [BluetoothDescriptor{uuid: 00002902-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00001808-0000-1000-8000-00805f9b34fb, characteristicUuid: 00002a18-0000-1000-8000-00805f9b34fb, value: []}], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a51-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00001808-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a52-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00001808-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: false, writeWithoutResponse: false, write: true, notify: false, indicate: true, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [BluetoothDescriptor{uuid: 00002902-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00001808-0000-1000-8000-00805f9b34fb, characteristicUuid: 00002a52-0000-1000-8000-00805f9b34fb, value: []}], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a08-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00001808-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a23-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 0000180a-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a24-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 0000180a-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a25-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 0000180a-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a26-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 0000180a-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a29-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 0000180a-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a2a-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 0000180a-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a50-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 0000180a-0000-1000-8000-00805f9b34fb, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: false, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00000000-0000-1000-1000-000000000001, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: false, writeWithoutResponse: false, write: true, notify: false, indicate: true, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [BluetoothDescriptor{uuid: 00002902-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, characteristicUuid: 00000000-0000-1000-1000-000000000001, value: []}], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00000000-0000-1000-1000-000000000002, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: false, writeWithoutResponse: false, write: false, notify: true, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [BluetoothDescriptor{uuid: 00002902-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, characteristicUuid: 00000000-0000-1000-1000-000000000002, value: []}], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00002a52-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: false, writeWithoutResponse: false, write: true, notify: false, indicate: true, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [BluetoothDescriptor{uuid: 00002902-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, characteristicUuid: 00002a52-0000-1000-8000-00805f9b34fb, value: []}], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00000000-0000-1000-1000-000000000010, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: false, writeWithoutResponse: false, write: false, notify: true, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [BluetoothDescriptor{uuid: 00002902-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, characteristicUuid: 00000000-0000-1000-1000-000000000010, value: []}], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00000000-0000-1000-1000-000000000011, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: false, writeWithoutResponse: false, write: true, notify: false, indicate: true, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [BluetoothDescriptor{uuid: 00002902-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, characteristicUuid: 00000000-0000-1000-1000-000000000011, value: []}], value: []}
I/flutter (16663): characteristics---> BluetoothCharacteristic{uuid: 00000000-0000-1000-1000-000000000012, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, secondaryServiceUuid: null, properties: CharacteristicProperties{broadcast: false, read: true, writeWithoutResponse: false, write: false, notify: true, indicate: false, authenticatedSignedWrites: false, extendedProperties: false, notifyEncryptionRequired: false, indicateEncryptionRequired: false}, descriptors: [BluetoothDescriptor{uuid: 00002902-0000-1000-8000-00805f9b34fb, deviceId: @@:@@:$$:%%:&&:##, serviceUuid: 00000000-0000-1000-1000-000000000000, characteristicUuid: 00000000-0000-1000-1000-000000000012, value: []}], value: []}

**Comment by chipweinberger** [comment]
try 1.7.8

**Comment by iresolveservices** [comment]
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: PlatformException(platformException, java.lang.Exception: service (00001808-0000-1000-8000-00805f9b34fb) could not be located on the device, java.lang.Exception: service (00001808-0000-1000-8000-00805f9b34fb) could not be located on the device
E/flutter (10409): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.locateCharacteristic(FlutterBluePlusPlugin.java:1125)
E/flutter (10409): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.onMethodCall(FlutterBluePlusPlugin.java:628)
E/flutter (10409): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (10409): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (10409): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (10409): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (10409): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (10409): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (10409): 	at android.os.Looper.loopOnce(Looper.java:240)
E/flutter (10409): 	at android.os.Looper.loop(Looper.java:351)
E/flutter (10409): 	at android.app.ActivityThread.main(ActivityThread.java:8381)
E/flutter (10409): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (10409): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/flutter (10409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/flutter (10409): , null) #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (10409): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (10409): <asynchronous suspension>
E/flutter (10409): #2      BluetoothCharacteristic.read.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:111:7)
E/flutter (10409): <asynchronous suspension>
E/flutter (10409): #3      _Mutex.synchronized (package:flutter_blue_plus/src/utils.dart:311:7)
E/flutter (10409): <asynchronous suspension>
E/flutter (10409): #4      BluetoothCharacteristic.read (package:flutter_blue_plus/src/bluetooth_characteristic.dart:85:5)
E/flutter (10409): <asynchronous suspension>
E/flutter (10409): 
E/flutter (10409): #0      BluetoothCharacteristic.read.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:124:7)
E/flutter (10409): #1      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter (10409): #2      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (10409): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
E/flutter (10409): #4      Future._propagateToListeners (dart:async/future_impl.dart:817:13)
E/flutter (10409): #5      Future._completeError (dart:async/future_impl.dart:592:5)
E/flutter (10409): #6      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:683:7)
E/flutter (10409): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (10409): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (10409):

**Comment by iresolveservices** [comment]
getting this

**Comment by chipweinberger** [comment]
`service (00001808-0000-1000-8000-00805f9b34fb) could not be located on the device`

this is your problem. Your ble device does not support this service.

**Comment by iresolveservices** [comment]
![WhatsApp Image 2023-07-20 at 4 07 09 PM](https://github.com/boskokg/flutter_blue_plus/assets/42065876/25c053a4-b7e5-4562-9c96-4c11193d9a0b)

"We obtained the data from the BLE device, but when I clicked on the characteristic with the value 0x2A52, it threw an error."

D/FlutterBluePlugin(13128): [onReadRemoteRssi] rssi: -51 status: 0
I/flutter (13128): remoteId: F4:B8:98:45:0C:E8characteristicUuid: 00002a52-0000-1000-8000-00805f9b34fbserviceUuid: 00000000-0000-1000-1000-000000000000
E/flutter (13128): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: PlatformException(read_characteristic_error, The READ property is not supported by this BLE characteristic, null, null) #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (13128): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (13128): <asynchronous suspension>
E/flutter (13128): #2      BluetoothCharacteristic.read.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:111:7)
E/flutter (13128): <asynchronous suspension>
E/flutter (13128): #3      _Mutex.synchronized (package:flutter_blue_plus/src/utils.dart:311:7)
E/flutter (13128): <asynchronous suspension>
E/flutter (13128): #4      BluetoothCharacteristic.read (package:flutter_blue_plus/src/bluetooth_characteristic.dart:85:5)
E/flutter (13128): <asynchronous suspension>
E/flutter (13128): 
E/flutter (13128): #0      BluetoothCharacteristic.read.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:124:7)
E/flutter (13128): #1      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter (13128): #2      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (13128): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
E/flutter (13128): #4      Future._propagateToListeners (dart:async/future_impl.dart:817:13)
E/flutter (13128): #5      Future._completeError (dart:async/future_impl.dart:592:5)
E/flutter (13128): #6      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:683:7)
E/flutter (13128): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (13128): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (13128):
