### ISSUE TITLE
discoverServices() ==>java.lang.Exception: no instance of BluetoothGatt, have you connected first?

### ISSUE THREAD

**Issue by Eashubh128** [boskokg/flutter_blue_plus#390]
I am using the flutter_blue_plus version ^1.7.5 . And getting this error while trying to discover services.
This problem specifically occurs when I try this
`
_connDevices= await FlutterBluePlus.instance.connectedDevices();
if(connDevices.isnotEmpty)
{
    _services = _connDevices.elementAt(0).discoverServices();  ////This causes the error
}
`
If I i connect to a device and then discover the services it works fine , but getting connected devices using connectedDevices() and then discovering services causes the error.

![image](https://github.com/boskokg/flutter_blue_plus/assets/61642602/c474d34b-dcdc-455a-a710-2c2e7545c273)

**Comment by chipweinberger** [comment]
I think you are mistaken. This can never work without first calling connect().

<img width="700" alt="Screenshot 2023-07-20 at 4 32 43 AM" src="https://github.com/boskokg/flutter_blue_plus/assets/1863934/ce107878-659b-4fb5-b867-8b07a792006a">

**Comment by chipweinberger** [comment]
<img width="698" alt="Screenshot 2023-07-20 at 4 34 27 AM" src="https://github.com/boskokg/flutter_blue_plus/assets/1863934/8c75f386-d5d0-4ee4-ade9-47f4332905ae">

**Comment by Eashubh128** [comment]
I am sorry , i assumed this would work , because i changed my dependency from flutter_blue to flutter_blue_plus. 
And this worked in flutter blue without any exception 


> I am using the flutter_blue_plus version ^1.7.5 . And getting this error while trying to discover services. This problem specifically occurs when I try this `_connDevices= await FlutterBluePlus.instance.connectedDevices(); if(connDevices.isnotEmpty) { _services = _connDevices.elementAt(0).discoverServices(); ////This causes the error }` If I i connect to a device and then discover the services it works fine , but getting connected devices using connectedDevices() and then discovering services causes the error.
> 
> ![image](https://user-images.githubusercontent.com/61642602/254838673-c474d34b-dcdc-455a-a710-2c2e7545c273.png)

**Comment by chipweinberger** [comment]
i'm going to close this issue.

If you think this can actually be solved, please try to implement it and open a PR.
