### ISSUE TITLE
onDone function is never triggered

### ISSUE THREAD

**Issue by charmosz** [boskokg/flutter_blue_plus#395]
When is the onDone function normally triggered ? Do I forget something ? 

`await charMeasure?.setNotifyValue(true);`

_notifySubscription = charMeasure?.onValueChangedStream.listen((value) {
  if (value.isNotEmpty) {
    print('sending ${value.toString()}');
  }
},
onError: (err) {
  print('error : ' + err);
},
onDone: () {
  print('done');
}
);

`await charMeasure?.read();`

**Comment by chipweinberger** [comment]
onDone is never called. do not worry about it.
