### ISSUE TITLE
Peripheral not getting cleaned up when Android app is backgrounded

### ISSUE THREAD

**Issue by sqcsabbey** [boskokg/flutter_blue_plus#397]
When I swipe my app away, a peripheral is staying connected, but my app is losing access to it; here's what I'm seeing:

When backgrounding, I see these log lines from this plugin:

> D/FlutterBluePlugin( 4445): onDetachedFromActivity
> D/FlutterBluePlugin( 4445): onDetachedFromEngine
> D/FlutterBluePlugin( 4445): teardown

Then I start seeing lots of log lines like:

> W/FlutterBluePlugin(18881): Tried to call OnCharacteristicChanged on closed channel

We were using version 1.3.7 of this plugin, but I upgraded to 1.8.2 and continue to see this behavior. 

What should happen here— should the app be responsible for disconnecting when it's being closed, or is this cleanup something this plugin could do? Or something else altogether?

**Comment by chipweinberger** [comment]
to be honest I'm not sure. If you figure it out, please report back.

**Comment by chipweinberger** [comment]
<img width="712" alt="Screenshot 2023-07-20 at 1 09 30 PM" src="https://github.com/boskokg/flutter_blue_plus/assets/1863934/20f3c5f5-af0c-4393-a72c-9e1f54165ef5">

**Comment by chipweinberger** [comment]
should be fixed: a103824339d20377a02f41983d9e6212f8618b28

**Comment by sqcsabbey** [comment]
Thank you, @chipweinberger!

**Comment by chipweinberger** [comment]
let me know if it works

**Comment by sqcsabbey** [comment]
> let me know if it works

@chipweinberger Yes, it worked for me; the peripheral disconnects a few seconds after the app is backgrounded. I get a couple of the 'on closed channel' messages before the cleanup happens, but I don't suspect that would have bad effects.

**Comment by chipweinberger** [comment]
great!
