### ISSUE TITLE
Question regarding txPower, AoA and AoD

### ISSUE THREAD

**Issue by watsmyname** [boskokg/flutter_blue_plus#4]
Hi, 

I am not sure whether its issue or not, but I do have got few questions

1. `txPower` always seems to be null  for my beacons when checked via Android
2. Bluetooth 5 transmits AoA and AoD (Angle of Arrival and Angle of Departure). This will help to find direction of the beacon. Is it possible to fetch these with this plugin?

Thanks a lot

**Comment by boskokg** [comment]
Hello @watsmyname. Can you please do a research on this topic and provide a merge request?
