### ISSUE TITLE
Question About ServiceUuids

### ISSUE THREAD

**Issue by phucho236** [boskokg/flutter_blue_plus#403]
in version 1.4.0. I'm using advertisementData.serviceUuids for device classification. In newer versions, serviceUuids return an empty. how to get serviceUuids  in scan results?

**Comment by chipweinberger** [comment]
it is likely a bug in MessageMake.java

feel free to submit a PR

**Comment by MrCsabaToth** [comment]
Android or iOS? With FBP 1.8.8 version and Android platform I seem to get the service UUIDs. It's crucial for me because I decide if I support a BT device or not based on these UUIDs.

**Comment by chipweinberger** [comment]
going to close. 

please reopen the issue if it is still broken in 1.9.0+
