### ISSUE TITLE
[Question]: [1.10.0] API changed without major version number update

### ISSUE THREAD

**Issue by pvaibhav** [boskokg/flutter_blue_plus#413]
Just wanted to mention that the API changed significantly between v1.7.x and 1.9.x.

Isn't it generally accepted to update the major version number when making breaking changes to the APIs? I'd have assumed the version would be bumped to v2.x.x. Or am I misunderstanding something?

**Comment by chipweinberger** [comment]
What API changed? There are no change AFAIK.

**Comment by mrRedSun** [comment]
Renames are breaking changes
The BluetoothConnectionState, method renames are all breaking changes and should bump the major

**Comment by chipweinberger** [comment]
doing an automated copy paste replacement is not a breaking change.

**Comment by mrRedSun** [comment]
1. Any change in the package that requires users to do anything in the project is a breaking change
2. No, they don't
3. Classes were renamed so that at least is a breaking change

**Comment by mrRedSun** [comment]
<img width="804" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/22750848/4af2fe2f-0b00-4e93-8820-798d8d17dd10">
Changelogs seem to acknowledge the breaking changes

**Comment by chipweinberger** [comment]
yes those are fair points. 1.10.0 should have been 2.0 using the dart versioning rules.

**Comment by chipweinberger** [comment]
> Also moving methods from instance to static, why was it even done? Instance is way more testable

The change was made because multiple instances will not actually work. The plugin uses named platform channels that can only exist once, and Android and iOS only support a single Bluetooth adapter.

**Comment by mrRedSun** [comment]
It's not really about multiple instances, the thing is that single instance classes can be mocked  – static classes can not

**Comment by MrCsabaToth** [comment]
#407

**Comment by jfacoustic** [comment]
@chipweinberger The only way that you'd be able to mock it is by creating a wrapper around Bluetooth calls.  If we were to update to the latest version of the package, we would have to change a significant amount of code because we would no longer be able to directly inject flutter blue plus as a dependency.  

It makes more sense to have an accessible instance getter rather than accessing Bluetooth calls through static methods.

**Comment by chipweinberger** [comment]
@jfacoustic yes you're correct. apologies for that.
