### ISSUE TITLE
MacOS ScanResult.advertisementData.serviceUuids is always empty

### ISSUE THREAD

**Issue by ekuleshov** [boskokg/flutter_blue_plus#415]
On MacOS the `ScanResult.advertisementData.serviceUuids` is always empty. Probably the same issue on iOS.

**Comment by chipweinberger** [comment]
what version? 1.9.4?

please feel free to debug it. I won't be able to fix it today.

**Comment by ekuleshov** [comment]
> what version? 1.9.4?
> please feel free to debug it. I won't be able to fix it today. it's probably a simple issue.

Been like that probably since 1.5.x or 1.6.x. PR is linked above.

**Comment by chipweinberger** [comment]
fixed in 1.9.5
