### ISSUE TITLE
[Bug:] cannot connect without scanning on iOS/MacOS : PlatformException(connect, Peripheral not found, null, null)

### ISSUE THREAD

**Issue by mocheffendi** [boskokg/flutter_blue_plus#417]
BluetoothDevice.fromId(Uuid)
use Uuid or macAddress for iOS/MacOS ?

2023-07-24 15:25:16.112 macos[44629:7566851] [FBP-iOS] handleMethodCall: connect
2023-07-24 15:25:16.309 macos[44629:7566851] [FBP-iOS] centralManagerDidUpdateState 5
2023-07-24 15:25:16.387 macos[44629:7566851] [FBP-iOS] handleMethodCall: getConnectionState
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(connect, Peripheral not found, null, null)

**Comment by chipweinberger** [comment]
> use Uuid or macAddress for iOS/MacOS ?

You should use a the UUID of the remote device. iOS generates this UUID randomly per device. It changes every so often, so if the peripheral cannot be found, the UUID may have expired and you'll need to scan again.

let me know if you fix the problem

**Comment by mocheffendi** [comment]
I did another scan and the remoteId is still the same, did I miss something? it works on Android. 

please give an example function code to scan without showing it on the page.

**Comment by chipweinberger** [comment]
To be clear, you are trying to connect without having to first scan every time right?

I suggest you put some logs in this function to see why it is not found.

```
- (CBPeripheral *)findPeripheral:(NSString *)remoteId
{
    NSUUID *uuid = [[NSUUID alloc] initWithUUIDString:remoteId];

    NSArray<CBPeripheral *> *peripherals = [_centralManager retrievePeripheralsWithIdentifiers:@[uuid]];

    CBPeripheral *peripheral;
    for (CBPeripheral *p in peripherals)
    {
        if ([[p.identifier UUIDString] isEqualToString:remoteId])
        {
            peripheral = p;
            break;
        }
    }
    return peripheral;
}
```

**Comment by mocheffendi** [comment]
I try this and solve, thanks for your great library.

scanconnect() async {
    try {
      // Start scanning for Bluetooth devices.
      FlutterBluePlus.scan(timeout: Duration(seconds: 5))
          .listen((scanResult) async {
        // Check if the desired device is found using its deviceId.
        if (scanResult.device.remoteId.toString() == macAddress) {
          targetdevice = scanResult.device;
          print(targetdevice.toString());

          try {
            // Connect to the desired device.
            await targetdevice.connect(
                autoConnect:
                    false); // Set autoConnect to true if you want auto-reconnect.
            print('Connected to device: ${targetdevice.localName}');

            // You can now discover services and characteristics to communicate with the device.
            discoverServices();
          } catch (e) {
            print('Error connecting to device: $e');
          }
        }
      });
    } catch (e) {
      print('Error scanning for devices: $e');
    }
}

**Comment by chipweinberger** [comment]
what was the fix?

**Comment by mocheffendi** [comment]
stopped at stopscan

2023-07-25 07:18:18.621 macos[35640:7922083] [FBP-iOS] handleMethodCall: setLogLevel
2023-07-25 07:18:18.622 macos[35640:7922083] [FBP-iOS] handleMethodCall: startScan
2023-07-25 07:18:18.749 macos[35640:7922083] [FBP-iOS] centralManagerDidUpdateState 5
2023-07-25 07:18:23.624 macos[35640:7922083] [FBP-iOS] handleMethodCall: stopScan

but when click the restart button at debug toolbar it can go

2023-07-25 08:39:38.077 macos[40460:7939719] [FBP-iOS] handleMethodCall: setLogLevel
2023-07-25 08:39:38.078 macos[40460:7939719] [FBP-iOS] handleMethodCall: startScan
flutter: BluetoothDevice{remoteId: 38D9D5EA-2A41-0D32-0AB6-43A1B4CF0806, localName: ESP32 Test, type: BluetoothDeviceType.le, isDiscoveringServices: false, _services: []}
2023-07-25 08:39:38.287 macos[40460:7939719] [FBP-iOS] handleMethodCall: connect
2023-07-25 08:39:38.290 macos[40460:7939719] [FBP-iOS] handleMethodCall: getConnectionState
flutter: BluetoothDevice{remoteId: 38D9D5EA-2A41-0D32-0AB6-43A1B4CF0806, localName: ESP32 Test, type: BluetoothDeviceType.le, isDiscoveringServices: false, _services: []}

**Comment by chipweinberger** [comment]
I don't follow. What was the fix? what lines of code did you need to add?

If I can improve our code to be better, I would like to.

**Comment by WeiKuang** [comment]
<img width="989" alt="截屏2023-07-25 11 26 23" src="https://github.com/boskokg/flutter_blue_plus/assets/12131724/1a39bf74-26b4-480b-b39f-be9328e2da5e">

**Comment by chipweinberger** [comment]
@WeiKuang why would that fix anything?

**Comment by WeiKuang** [comment]
@chipweinberger 
I think it's keeping a reference to the peripheral. Of course, this is just my guess, not a perfect solution.

**Comment by chipweinberger** [comment]
I've researched the problem more and released 1.10.5

**Comment by JDongKhan** [comment]
same issue when upgrade 1.12.8.

```
 NSArray<CBPeripheral *> *peripherals = [_centralManager retrievePeripheralsWithIdentifiers:@[uuid]];
```
peripherals is empty array.

**Comment by JDongKhan** [comment]
only call connect.
![image](https://github.com/boskokg/flutter_blue_plus/assets/4929805/abb167c6-77ed-4622-89c7-6d69f76be0e1)

after call  scan  and then call connect
![image](https://github.com/boskokg/flutter_blue_plus/assets/4929805/ba308f92-87b5-4ba6-b619-7c147b8d1d55)

**Comment by chipweinberger** [comment]
thanks for debugging a bit more.

If `retrievePeripheralsWithIdentifiers` is empty, I'm not sure what else we can do. 

Maybe try reading the iOS documentation more. Perhaps this is expected?

**Comment by JDongKhan** [comment]
Maybe, I have reviewed many blog and get same response.

**Comment by chipweinberger** [comment]
ok. tell me if you find a fix

**Comment by chipweinberger** [comment]
ChatGPT:
- This method only returns peripherals that have been discovered during a prior scan by your app and that are currently in range. If the peripheral is not in range or turned off, the method may not return that peripheral.

Seems like this is expected behavior. Your app needs to scan at least once.
