### ISSUE TITLE
crash when  upgrade to latest version

### ISSUE THREAD

**Issue by JDongKhan** [boskokg/flutter_blue_plus#418]
#11756  FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:263:7)
I/flutter (  634): │ ⛔ #11757  FlutterBluePlus.setLogLevel (package:flutter_blue_plus/src/flutter_blue_plus.dart:243:11)
I/flutter (  634): │ ⛔ #11758  FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:263:7)
I/flutter (  634): │ ⛔ #11759  FlutterBluePlus.setLogLevel (package:flutter_blue_plus/src/flutter_blue_plus.dart:243:11)
I/flutter (  634): │ ⛔ #11760  FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:263:7)
I/flutter (  634): │ ⛔ #11761  FlutterBluePlus.setLogLevel (package:flutter_blue_plus/src/flutter_blue_plus.dart:243:11)
I/flutter (  634): │ ⛔ #11762  FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:263:7)
I/flutter (  634): │ ⛔ #11763  FlutterBluePlus.setLogLevel (package:flutter_blue_plus/src/flutter_blue_plus.dart:243:11)
I/flutter (  634): │ ⛔ #11764  FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:263:7)
I/flutter (  634): │ ⛔ #11765  FlutterBluePlus.setLogLevel (package:flutter_blue_plus/src/flutter_blue_plus.dart:243:11)
I/flutter (  634): │ ⛔ #11766  FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:263:7)
I/flutter (  634): │ ⛔ #11767  FlutterBluePlus.setLogLevel (package:flutter_blue_plus/src/flutter_blue_plus.dart:243:11)
I/flutter (  634): │ ⛔ #11768  FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dar

**Comment by chipweinberger** [comment]
fixed in 1.10.2
