### ISSUE TITLE
Last value sent twice since onValueChangedStream => onValueReceived

### ISSUE THREAD

**Issue by charmosz** [boskokg/flutter_blue_plus#419]
Since the change onValueChangedStream => onValueReceived it seems the last value is sent twice. Do I have something else to change ?

Before : 

```
await charMeasure?.setNotifyValue(true);

_notifySubscription = charMeasure?.onValueChangedStream.listen((value) {
if (value.isNotEmpty) {
print('sending ${value.toString()}');
}
},
);

await charMeasure?.read();
```

After : 
```
await charMeasure?.setNotifyValue(true);

_notifySubscription = charMeasure?.onValueReceived.listen((value) {
if (value.isNotEmpty) {
print('sending ${value.toString()}');
}
},
);

await charMeasure?.read();
```

**Comment by chipweinberger** [comment]
can you clarify what you mean? do you have logs?

**Comment by charmosz** [comment]
On the device I know I have 11 values. In the first case when I trigger read() I have 11 logs, one for each value. In the second case I have 12 logs, the last one is printed twice.

**Comment by chipweinberger** [comment]
This is expected because you are calling `await charMeasure?.read();`

When you call `await charMeasure?.read()`, it causes onValueReceived to get the value again.

**Comment by chipweinberger** [comment]
This should not have been an API change though. I believe it has always works this way...

**Comment by charmosz** [comment]
Ok thanks for the explanation. I think it's a good idea to make both platforms work the same way.
And for my specific needs I will find a way to manage the fact that the last value is retrieved twice.
