### ISSUE TITLE
Scanning Device Cache Issue : While Scanning Returning Non-Active(Previously Active) Devices Too

### ISSUE THREAD

**Issue by pranil-iottive** [boskokg/flutter_blue_plus#421]
Using Version flutter_blue_plus: ^1.10.5

### **Start Scan:** 

`Future startBluScanAction() async {
  try {

    await FlutterBluePlus.startScan(
      allowDuplicates: true,
      withServices: [
        Guid("0000ffe0-0000-1000-8000-00805f9b34fb"),
      ],
    );
  }catch(e){
    log("error while starting the scan ");
  }
}`

###  **For Scan Result :** 

`FlutterBluePlus.scanResults.listen((event) {}).onData((ondata) {}`

I'm using ScanResult Stream where I'm receiving the cache of the previous devices, even if the device is not active then.

Steps to reproduce : 

1. Start scan without any certain duration
2. Turn on 1 device to advertise 
3. Turn off the same device 
4. Turn on any other device to advertise, but make sure it'll not be the same.
5. Still will able to see 2 devices, even if there is only one device is active.

### **Conclusion:** 
I'm getting devices in the scan from the cache, even if the devices are not active.
the ideal case should be, if the device is not active then it should not appear in the ScanResult Stream.

@boskokg any help?

**Comment by chipweinberger** [comment]
this is how to works,

The ScanResults have a timestamp in them. Just check the timestamp if you want to exclude old devices.
