### ISSUE TITLE
"requestMtu" not complete

### ISSUE THREAD

**Issue by Jbz797** [boskokg/flutter_blue_plus#425]
Since version 1.10.6, the method `RequestMcu`don't work :

```
TimeoutException (TimeoutException after 0:00:15.000000: Future not completed)
```

**Comment by chipweinberger** [comment]
iOS or android?

**Comment by Jbz797** [comment]
Android

**Comment by chipweinberger** [comment]
fixed. 1.10.8

thanks for reporting

**Comment by rahul-mobilecoderz** [comment]
Unhandled Exception: FlutterBluePlusException: requestMtu: (code: 6) Timed out after 15s . it is showing in version 1.14.9 . Kindly resolve it soon .

**Comment by chipweinberger** [comment]
@rahul-mobilecoderz, open a new issue w/ logs, version, platform, etc.
