### ISSUE TITLE
Why this looks like it is from scratch while being a fork?

### ISSUE THREAD

**Issue by tapkain** [boskokg/flutter_blue_plus#43]
Hello, I'm wondering why you didn't just forked the previous one with whole commit history and previous acknowledgement of all of the contributors but created a new one from scratch? Are there some reasons for this?

**Comment by boskokg** [comment]
Hello @tapkain . No special reason I remember. We had to use a different name of the plugin and flutter creates many internal logic based on the name. First I created it as a fork but after some time of trying to resolve all the issue related to plugin renaming I decided that it is easier for me to create a new plugin and just copy the code.
The original plugin has many reported issues and merge requests not maintained by anyone and if anyone needs the history, there is the original plugin to view it.
