### ISSUE TITLE
.discoverServices() throws [CoreBluetooth] API MISUSE: can only accept commands while in the connected state

### ISSUE THREAD

**Issue by sudoadarsh** [boskokg/flutter_blue_plus#432]
Plugin Version: Latest. 
Platform: iOS 16

Steps to reproduce:

1. Connect to a Bluetooth Device.
2. Turn off Bluetooth adapter.
3. Connect to the Bluetooth Device and listen to device.connectionState
4. When connectionState == BluetoothConnectionState.connected, use the BluetoothDevice Object to call ~.discoverDevices()~ discoverServices().

This throws _[CoreBluetooth] API MISUSE: can only accept commands while in the connected state_ even though the connection state is received as BluetoothConnectionState.connected.

**Comment by chipweinberger** [comment]
discoverDevices? That does not exist...

**Comment by sudoadarsh** [comment]
The method is .discoverServices() and for the logs, I have reverted my code back to plugin version 1.4.0 and it's working fine.

**Comment by chipweinberger** [comment]
Yes, the logs would be very helpful. All of them.

**Comment by chipweinberger** [comment]
Can you explain these steps more?

2. Turn off Bluetooth adapter.
3. Connect to the Bluetooth Device and listen to device.connectionState

How are yo connecting while the adapter is off?

**Comment by chipweinberger** [comment]
should be fixed in 1.11.5
