### ISSUE TITLE
[Bug]: Automatic reconnection failed

### ISSUE THREAD

**Issue by LvJson** [boskokg/flutter_blue_plus#435]
### FlutterBluePlus Version

1.11.4

### What OS?

Android

### OS Version

HarmonyOS 3.0.0

### What happened?

The latest version of automatic reconnection failed.
But the old version before is normal. (e.g. 1.5.2 is normal)

### Logs

```shell
no logs.
```

**Comment by chipweinberger** [comment]
Not enough detail.

**Comment by LvJson** [comment]
device.connect(
          timeout: const Duration(milliseconds: CON_TIMEOUT),
          autoConnect: true)

It doesn't work when I set autoConnect to true，but no more logs.
