### ISSUE TITLE
[Bug]: FlutterBluePlus.startScan() throws error.

### ISSUE THREAD

**Issue by sudoadarsh** [boskokg/flutter_blue_plus#437]
### FlutterBluePlus Version

1.11.8

### What OS?

Android

### OS Version

13

### What happened?

When trying to call the method .startScan() on Android 13, the following error is thrown.

### Logs

```shell
D/[FBP-Android](23610): [FBP-Android] onMethodCall: setLogLevel
D/[FBP-Android](23610): [FBP-Android] onMethodCall: isOn
D/[FBP-Android](23610): [FBP-Android] onMethodCall: isOn
D/[FBP-Android](23610): [FBP-Android] onMethodCall: getAdapterState
I/flutter (23610): Instance of 'BLEOnS'
D/[FBP-Android](23610): [FBP-Android] onMethodCall: getConnectedSystemDevices
D/[FBP-Android](23610): [FBP-Android] onMethodCall: getConnectedSystemDevices
D/[FBP-Android](23610): [FBP-Android] onMethodCall: startScan
D/BluetoothAdapter(23610): isLeEnabled(): ON
I/flutter (23610): Instance of 'DosemiScanningS'
D/BluetoothLeScanner(23610): onScannerRegistered() - status=0 scannerId=4 mScannerId=0
D/[FBP-Android](23610): [FBP-Android] onMethodCall: startScan
D/BluetoothAdapter(23610): isLeEnabled(): ON
D/[FBP-Android](23610): [FBP-Android] onScanFailed: SCAN_FAILED_ALREADY_STARTED
E/flutter (23610): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter (23610): #0      _StreamController._subscribe (dart:async/stream_controller.dart:678:7)
E/flutter (23610): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:828:19)
E/flutter (23610): #2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
E/flutter (23610): #3      new _AddStreamState (dart:async/stream_controller.dart:893:34)
E/flutter (23610): #4      new _StreamControllerAddStreamState (dart:async/stream_controller.dart:943:9)
E/flutter (23610): #5      _StreamController.addStream (dart:async/stream_controller.dart:578:9)
E/flutter (23610): #6      _AsyncStarStreamController.addStream (dart:async-patch/async_patch.dart:98:39)
E/flutter (23610): #7      _BufferStream.stream (package:flutter_blue_plus/src/utils.dart)
E/flutter (23610): <asynchronous suspension>
E/flutter (23610): #8      FlutterBluePlus.scan (package:flutter_blue_plus/src/flutter_blue_plus.dart:188:5)
E/flutter (23610): <asynchronous suspension>
E/flutter (23610): 
E/flutter (23610): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FlutterBluePlusException: name:scan errorCode:1, errorString:SCAN_FAILED_ALREADY_STARTED
E/flutter (23610): #0      FlutterBluePlus.scan (package:flutter_blue_plus/src/flutter_blue_plus.dart:191:9)
E/flutter (23610): <asynchronous suspension>
E/flutter (23610): 
D/[FBP-Android](23610): [FBP-Android] onMethodCall: stopScan
D/BluetoothAdapter(23610): isLeEnabled(): ON
D/[FBP-Android](23610): [FBP-Android] onMethodCall: stopScan
D/BluetoothAdapter(23610): isLeEnabled(): ON
D/BluetoothLeScanner(23610): could not find callback wrapper
```

**Comment by sudoadarsh** [comment]
`
@override
  Stream<DosemiStatus> getDosemi({
    required String name,
    required Function(BLELogC error) onError,
  }) async* {
    // Guard the [FlutterBluePlus] instance.
    // if (_bluePlus == null) return;

    // Start scanning for Doseminder.
    yield DosemiStatus.scanning;

    try {
      bool isFound = false;

      // Check if Doseminder contains in the connected devices.
      final List<BluetoothDevice> devices =
          await FlutterBluePlus.connectedSystemDevices;
      for (BluetoothDevice device in devices) {
        if (device.localName == name) {
          connectedDevice = device;
          _availableServices = await device.discoverServices();
          _getServicesAndChar(_availableServices);
          yield DosemiStatus.connected;
          return;
        }
      }

      // Stop any current bluetooth scan.
      // await _bluePlus!.stopScan();
      await FlutterBluePlus.stopScan();

      Future.delayed(const Duration(seconds: 10), () {
        if (isFound) return;
        onError(BLELogC.doseminderNotFound);
      });

      // Start the scan.
      FlutterBluePlus.startScan(
        scanMode: ScanMode.lowLatency,
        timeout: const Duration(seconds: 10),
      );

      // Listen scan results.
      await for (List<ScanResult> results in FlutterBluePlus.scanResults) {
        for (ScanResult r
            in results.where((e) => e.device.localName.isNotEmpty)) {
          LogUtil.i(BLELogC.scannedDevice.i + r.device.localName);

          if (r.device.localName == name) {
            // Stop the scan.
            isFound = true;
            // await _bluePlus!.stopScan();
            await FlutterBluePlus.stopScan();

            // Connected to Doseminder with a timeout of 10 seconds.
            yield DosemiStatus.connecting;

            try {
              await r.device.connect(
                timeout: const Duration(seconds: 5),
                autoConnect: false,
              );
            } on TimeoutException catch (_) {
              // yield DosemiStatus.failed;
              // yield DosemiStatus.unableToConnect;
              try {
                await r.device.connect(
                  timeout: const Duration(seconds: 10),
                  autoConnect: false,
                );
              } on TimeoutException catch (_) {
                yield DosemiStatus.unableToConnect;
              }
            }

            await for (BluetoothConnectionState dosemiState
                in r.device.connectionState) {
              switch (dosemiState) {
                case BluetoothConnectionState.disconnected:
                  yield DosemiStatus.disconnected;
                  break;
                case BluetoothConnectionState.connecting:
                  yield DosemiStatus.connecting;
                  break;
                case BluetoothConnectionState.connected:
                  // Store the connected device.
                  connectedDevice = r.device;
                  _availableServices = await r.device.discoverServices();
                  _getServicesAndChar(_availableServices);
                  yield DosemiStatus.connected;
                  break;
                case BluetoothConnectionState.disconnecting:
                  yield DosemiStatus.disconnecting;
                  break;
              }
            }
          }
        }
      }
    } catch (_) {
      yield DosemiStatus.unknownError;
    }
  }

`

**Comment by chipweinberger** [comment]
I've pushed this to master. e3e031df2ed5f657de2e596d7b208941614eae8f

It is a partial fix, but I think you may have a bug in your code as well.

**Comment by pyciko** [comment]
+1, same behaviour on 1.14.11

**Comment by chipweinberger** [comment]
@pyciko open a new issue
