### ISSUE TITLE
[Bug]: Geolocator permissions missing with FlutterBluePlus

### ISSUE THREAD

**Issue by danni5326** [boskokg/flutter_blue_plus#438]
### FlutterBluePlus Version

1.11.8

### What OS?

Android

### OS Version

12

### What happened?

I have an application that implements Geolocator and FlutterBluePlus simultaneously. Until version 1.5.2, my functionality to obtain the current location worked correctly, but since version 1.7.0, it shows an error stating that location permissions are missing in the manifest.
I have added the permissions following the documentation with both possible options, but the error persists.
![image](https://github.com/boskokg/flutter_blue_plus/assets/19170252/0121efa8-1c59-43da-8ff9-145a983f589e)

I tried reverting to version 1.5.2, and it works again. The issue started after I updated FlutterBluePlus; that's when my application got damaged

### Logs

```shell
Unhandled Exception: No location permissions are defined in the manifest. Make sure at least ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION are defined in the manifest.
```

**Comment by Narayanhegde14** [comment]
@danni5326 

I also faced the same issue and the solution is in the package files and you have the Android folder in which you have the AndroidManifest.xml file which is not required because if there need to be any permissions needs to be added that should be in the application projects AndroidManifest.xml file.

**Comment by chipweinberger** [comment]
you need this 

```
<!-- add tools -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">

<!-- remove the plugin permission which sets neverForLocation -->
<uses-permission
    android:name="android.permission.BLUETOOTH_SCAN"
    tools:node="remove"
    tools:selector="com.boskokg.flutter_blue_plus">
</uses-permission>

<!-- remove the plugin permission which sets maxSdkVersion 30 -->
<uses-permission
    android:name="android.permission.ACCESS_FINE_LOCATION"
    tools:node="remove"
    tools:selector="com.boskokg.flutter_blue_plus">
</uses-permission>

<!-- add back without neverForLocation, and without maxSdkVersion -->
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

```

**Comment by chipweinberger** [comment]
better, use version 1.12.1, I have simplified permissions.

**Comment by danni5326** [comment]
> o **use la versión 1.12.0+** , tengo permisos simplificados.
> 
> en 1.12.0, el complemento ya no establece permisos. solo tú los configuras.


Thanks...! I tried both options and now it works correctly. I will use the latest version available.
