### ISSUE TITLE
I can't disconnect the device from the connected device if the app restarts

### ISSUE THREAD

**Issue by syahrulafrizal** [boskokg/flutter_blue_plus#44]
Scenario 0

    connect to some device
    disconnect above device
    -----> doing well

■ Scenario 1

    connect to some device
    terminate app
    restart app
    -----> we can find connected device by
    -----> listening connectedDeviceStream

How can i disconnect device what found by connectedDeviceStream
not from manually connectToDevice nor connectToAdvertisingDevice ?

i already know canceling stream from connectToDevice
or connectToAdvertisingDevice take disconnection

but, connected device from connectedDeviceStream have no stream
so i can't disconenct those devices..... T_T

■ Trying
after Scenario 1, if i found already connected device
then make connection and cancel...

but can't get disconnected callback by ConnectionStateUpdate
(both stream from connection and FlutterReactiveBle.instants's connectedDeviceStream)

also can't scan that device...

**Comment by sophisticode** [comment]
I assume this happens on Android?

I had a similar problem, so here are my findings.

If you get the list of connected devices with `flutterBlue.connectedDevices()`, they don't behave as if the app has connected to them. The reason is that the native Android part of the plugin does not know the associated gattServer of that device. Therefore, you will not be able to use that device for anything like discovering services, writing and reading characteristics or disconnecting.

The only solution I found for my use-case was to always disconnect the current device when the app goes to the background. This is not possible just by listening to AppLifecycleState events (the disconnect will not run if called after you press the back button), so the disconnect should be done from a top level WillPopScope widget. Then, when the app restarts, your device should not be amongst the connected devices and it is visible in the scan results. 

```
WillPopScope(
  onWillPop: () async {
    await currentDevice.disconnect();
    return true;
  },
  child: <top level scaffold>,
}

```

**Comment by syahrulafrizal** [comment]
> I assume this happens on Android?
> 
> I had a similar problem, so here are my findings.
> 
> If you get the list of connected devices with `flutterBlue.connectedDevices()`, they don't behave as if the app has connected to them. The reason is that the native Android part of the plugin does not know the associated gattServer of that device. Therefore, you will not be able to use that device for anything like discovering services, writing and reading characteristics or disconnecting (unless you call `connect()` for that device again).
> 
> The only solution I found for my use-case was to always disconnect the current device when the app is terminated with the back button. This is not possible just by listening to AppLifecycleState events (the disconnect will not run if called after you press the back button), so the disconnect should be done from a top level WillPopScope widget. Then, when the app restarts, your device should not be amongst the connected devices and it is visible in the scan results.
> 
> ```
> WillPopScope(
>   onWillPop: () async {
>     await currentDevice.disconnect();
>     return true;
>   },
>   child: <top level scaffold>,
> }
> ```

**Comment by syahrulafrizal** [comment]
> I assume this happens on Android?
> 
> I had a similar problem, so here are my findings.
> 
> If you get the list of connected devices with `flutterBlue.connectedDevices()`, they don't behave as if the app has connected to them. The reason is that the native Android part of the plugin does not know the associated gattServer of that device. Therefore, you will not be able to use that device for anything like discovering services, writing and reading characteristics or disconnecting (unless you call `connect()` for that device again).
> 
> The only solution I found for my use-case was to always disconnect the current device when the app is terminated with the back button. This is not possible just by listening to AppLifecycleState events (the disconnect will not run if called after you press the back button), so the disconnect should be done from a top level WillPopScope widget. Then, when the app restarts, your device should not be amongst the connected devices and it is visible in the scan results.
> 
> ```
> WillPopScope(
>   onWillPop: () async {
>     await currentDevice.disconnect();
>     return true;
>   },
>   child: <top level scaffold>,
> }
> ```



but I need the app to stay connected to bluetooth if the app is closed

**Comment by figureai** [comment]
Add the following code to the FlutterBluePlusPlugin.m file under the ios platform
```
if(peripheral == nil) {
        NSArray *periphs = [self->_centralManager retrieveConnectedPeripheralsWithServices:@[[CBUUID UUIDWithString:@"1800"]]];
        for (CBPeripheral *p in periphs) {
          NSString *uuid = [[p identifier] UUIDString];
          p.delegate = self;
          [_scannedPeripherals setObject: p forKey:uuid];
        }
        peripheral = [_scannedPeripherals objectForKey:remoteId];
 }
```

![image](https://user-images.githubusercontent.com/45620405/182846265-15dfb3ae-6eda-40af-9876-379573b19a93.png)

**Comment by a1573595** [comment]
> Scenario 0
> 
> ```
> connect to some device
> disconnect above device
> -----> doing well
> ```
> 
> ■ Scenario 1
> 
> ```
> connect to some device
> terminate app
> restart app
> -----> we can find connected device by
> -----> listening connectedDeviceStream
> ```
> 
> How can i disconnect device what found by connectedDeviceStream not from manually connectToDevice nor connectToAdvertisingDevice ?
> 
> i already know canceling stream from connectToDevice or connectToAdvertisingDevice take disconnection
> 
> but, connected device from connectedDeviceStream have no stream so i can't disconenct those devices..... T_T
> 
> ■ Trying after Scenario 1, if i found already connected device then make connection and cancel...
> 
> but can't get disconnected callback by ConnectionStateUpdate (both stream from connection and FlutterReactiveBle.instants's connectedDeviceStream)
> 
> also can't scan that device...

When I close the app, Android disconnects the bluetooth and iOS stays connected.

**Comment by WeiKuang** [comment]
Same issue on iOS

**Comment by yudeying918** [comment]
> 
i also want to disconnect the device when the app is quit,
should i use the code in dispose() method?

**Comment by lorenzosfarra** [comment]
Any news or suggestion on this side?
It's anyway interesting that the log:

`D/FlutterBluePlugin(26686): mDevices size: 0`

is correct, but the connectedDevices is not.

**Comment by chipweinberger** [comment]
Please try 1.7.6+. reopen a new issue if you still have problems.

feel free to open a PR with a proper fix.
