### ISSUE TITLE
[Bug]: ANDROID 12 no permission idicate, so unable to scan device.

### ISSUE THREAD

**Issue by joyhope** [boskokg/flutter_blue_plus#440]
### FlutterBluePlus Version

1.12.4

### What OS?

Android

### OS Version

android 12

### What happened?

Unable to find BLE device.   1.11.X version is ok.   No permisssion indicate, 

### Logs

```shell
07-27 10:55:00.669 12527 12580 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(startScan, FlutterBluePlus requires android.permission.BLUETOOTH_SCAN permission, null, null)
07-27 10:55:00.669 12527 12580 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
07-27 10:55:00.669 12527 12580 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
07-27 10:55:00.669 12527 12580 E flutter : <asynchronous suspension>
07-27 10:55:00.669 12527 12580 E flutter : #2      FlutterBluePlus.scan (package:flutter_blue_plus/src/flutter_blue_plus.dart:178)
07-27 10:55:00.669 12527 12580 E flutter : <asynchronous suspension>
07-27 10:55:00.669 12527 12580 E flutter : #3      Isolate.run.<anonymous closure> (dart:isolate:291)
07-27 10:55:00.669 12527 12580 E flutter : <asynchronous suspension>
07-27 10:55:00.669 12527 12580 E flutter :
```

**Comment by joyhope** [comment]
sorry,  my phone is HarmonyOS 3.0 ( It may be different from Android 12)

**Comment by joyhope** [comment]
Seems manifest file is missing.

**Comment by shubhamsinghmutualmobile** [comment]
See its solution here: https://github.com/boskokg/flutter_blue_plus/issues/409#issuecomment-1651055224

**Comment by joyhope** [comment]
so user's own app needs to define this permssion.

**Comment by joyhope** [comment]
Permission was added in the user's app's manifest, and it works.

**Comment by shubhamsinghmutualmobile** [comment]
> so user's own app needs to define this permission.

Apparently, on Android 12 and above, we don't require the Location permission in order to just scan for devices, that's what the `BLUETOOTH_SCAN` permission is for and to be on a privacy-safer side, the package maintainers have chosen to not use the location permission for A12 and above that you can easily override with the method shared above.

**Comment by shubhamsinghmutualmobile** [comment]
> Permission was added in the user's app's manifest, and it works.

@joyhope If there are any other questions regarding this issue, you can drop them here and feel free to close the issue whenever you feel it is resolved for you 👍

**Comment by chipweinberger** [comment]
> Permission was added in the user's app's manifest, and it works.

Yes you need to specify permissions yourself.
