### ISSUE TITLE
[Bug]: scan not find any devices

### ISSUE THREAD

**Issue by WeiKuang** [boskokg/flutter_blue_plus#441]
### FlutterBluePlus Version

1.12.4

### What OS?

iOS

### OS Version

16.4.1

### What happened?

Same code, different performance on two versions.
only happens on scan.
in 1.10.10, it is ok.
but in 1.12.4, not find any devices.
```dart
var subscription = FlutterBluePlus.scanResults.listen((results) {
    for (ScanResult r in results) {
        Map<int, List<int>> map = r.advertisementData.manufacturerData;
    }
});

// Start scanning
FlutterBluePlus.startScan(timeout: Duration(seconds: 4));
```

### Logs

```shell
version: 1.10.10
[FBP-iOS] handleMethodCall: isOn
[FBP-iOS] handleMethodCall: stopScan
[FBP-iOS] handleMethodCall: getConnectedDevices
[FBP-iOS] handleMethodCall: startScan
version: 1.12.4
[FBP-iOS] handleMethodCall: isOn
[FBP-iOS] handleMethodCall: stopScan
[FBP-iOS] handleMethodCall: startScan
```

**Comment by chipweinberger** [comment]
works for me (macOS)

**Comment by WeiKuang** [comment]
Of course no problem, glad to help. 
But I'm sure I can fix it because I'm a new coder.

**Comment by chipweinberger** [comment]
FlutterBluePlus.logLevel to verbose

**Comment by WeiKuang** [comment]
it seems to be stuck in a loop。
[FBP-iOS] handleMethodCall: isOn
flutter: \^[[38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;12m│ 16:30:14.832 (+0:00:24.104448)<…>
flutter: \^[[38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;12m│ 💡 _scan Filter Device<…>
flutter: \^[[38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
[FBP-iOS] handleMethodCall: stopScan
flutter: 
BmScanSettings {service_uuids: [], mac_addresses: [], allow_duplicates: false, android_scan_mode: 2, android_uses_fine_location: false}
[FBP-iOS] handleMethodCall: startScan
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral
[FBP-iOS] centralManager didDiscoverPeripheral

**Comment by chipweinberger** [comment]
It is not a loop, there are just a lot of devices, and maybe you have allowDuplicates turned on.

I just tried the example app and it works for me on 1.12.4, with iOS 16.5.1

**Comment by chipweinberger** [comment]
You should put a breakpoint here

<img width="733" alt="Screenshot 2023-07-27 at 1 40 43 AM" src="https://github.com/boskokg/flutter_blue_plus/assets/1863934/4579c887-4a6d-41fd-9a87-03f6418cf270">

**Comment by WeiKuang** [comment]
Oh, it's my fault.
my code is :
try {
  var subscription = FlutterBluePlus.scanResults.listen((results) {
    for (ScanResult r in results) {
      Map<int, List<int>> map = r.advertisementData.manufacturerData;
    }
  });
  FlutterBluePlus.startScan(timeout: const Duration(seconds: 5));
} catch (e) {
  LogUtils.logger!.e('Error during Bluetooth scan: $e');
} finally {
  FlutterBluePlus.stopScan();
}
When the scan starts, it stops immediately。
so remove finally is OK

**Comment by chipweinberger** [comment]
great!
