### ISSUE TITLE
[Bug]: isOn not returning correct value on iOS 16.6 (v1.12.8)

### ISSUE THREAD

**Issue by keskink** [boskokg/flutter_blue_plus#452]
### FlutterBluePlus Version

1.12.8

### Flutter Version

3.10.xx

### What OS?

iOS

### OS Version

16.6

### What happened?

isOn function not returning correct value on iOS 16.6. 
works on 15.7.8.

### Logs

```shell
..
```

**Comment by chipweinberger** [comment]
```
else if ([@"isOn" isEqualToString:call.method])
        {
            if (self.centralManager.state == CBManagerStatePoweredOn)
            {
                result(@(YES));
            }
            else
            {
                result(@(NO));
            }
        }
```

this code looks correct to me.

try turning on verbose logs

**Comment by chipweinberger** [comment]
`FlutterBluePlus.adapterState` might be better to use

**Comment by chipweinberger** [comment]
you can also try using `adapterState`

**Comment by keskink** [comment]
FlutterBluePlus.adapterState.listen(
returning BluetoothAdapterState.unauthorized.
I am sure that all permission active.

**Comment by keskink** [comment]
Logs as below


[FBP-iOS] handleMethodCall: setLogLevel
[FBP-iOS] handleMethodCall: getConnectedSystemDevices
[FBP-iOS] handleMethodCall: getAdapterState
flutter: [FBP] \^[[1;30m<getConnectedSystemDevices>\^[[0m result: \^[[1;33m{devices: [<…>
flutter: [FBP] \^[[1;30m<getConnectedSystemDevices>\^[[0m args: \^[[1;35mnu<…>
[FBP-iOS] handleMethodCall: getConnectedSystemDevices
flutter: [FBP] \^[[1;30m<getAdapterState>\^[[0m args: \^[[1;35mnu<…>
[FBP-iOS] handleMethodCall: getAdapterState
flutter: [FBP] \^[[1;30m<getAdapterState>\^[[0m result: \^[[1;33m{adapter_state: <…>
flutter: [FBP] \^[[1;30m<getConnectedSystemDevices>\^[[0m result: \^[[1;33m{devices: [<…>
flutter: [FBP] \^[[1;30m<getAdapterState>\^[[0m result: \^[[1;33m{adapter_state: <…>

**Comment by keskink** [comment]
I removed my app from phone, and restart app. it asked permissions again, then it is working now :)
