### ISSUE TITLE
[Feature]: Remove "print" from write-Function

### ISSUE THREAD

**Issue by aklehm** [boskokg/flutter_blue_plus#453]
### Feature Request

Please remove the `print("withoutResponse $withoutResponse");` from the write-Function in the `/lib/src/bluetooth_characteristic.dart` file.
It is very annoying while sending bigger files. If you still want the print statement for debug, you should add a debug flag to that function.

**Comment by chipweinberger** [comment]
thanks. it's a mistake

**Comment by chipweinberger** [comment]
fixed e53b1e1261064f6fc6063d3ec074a5dcbc740d98

will be in `1.12.9`

**Comment by chipweinberger** [comment]
1.12.9 is now released
