### ISSUE TITLE
Can flutter_blue_plus support many-to-many connections between Bluetooth devices? [Question]: 

### ISSUE THREAD

**Issue by abdurahmanshiine** [boskokg/flutter_blue_plus#457]
### Ask your question

Hi there,

I'm working on an offline messaging app that's supposed to use Bluetooth meshes to establish a network between the nodes (something similar to Bridgefy). Could this library be used to that effect? To establish a many-to-many connection between the devices and mass-send messages to all of them at once?

I really appreciate any help you can provide.

**Comment by chipweinberger** [comment]
ya it could do that.

you need to read more about bluetooth central and bluetooth peripheral devices.

flutter blue plus only supports the central mode, so phone to phone direct connection is not possible.
