### ISSUE TITLE
[Question]: iOT device Bluetooth name displayed like unreadable characters in iOS, any solution?

### ISSUE THREAD

**Issue by elmar001** [boskokg/flutter_blue_plus#476]
### Ask your question

I am facing some issues with Bluetooth name display in IOS. Blueeoth name is diplayed as some unreadable text (Fort example "?/*"). It is probably due to GAP device name is prioritized over anything else in iOS. I have found the discussion about the exact same thing in old flutter_blue package [Github discussions](https://github.com/pauldemarco/flutter_blue/issues/524). 

Is it still the case in flutter_blue_plus? Is there any implemented workaround?

**Comment by MrCsabaToth** [comment]
I'd wonder how does the device show up in nRF Connect for example? Is the name Chinese or similar UTF-8 characters? Please show and tell more details.

**Comment by elmar001** [comment]
Have not checked with nRF Connect, sorry. No, no Chinese or any other none uni-code characters in the name. Name example is "15KODY0022'. It is showed correctly in the same implementation with flutter_blue_plus in Android but not in iOS. I have one another native iOS app which shows the name correctly. 

Thinking to fork the package and try the suggested workaround [here](https://github.com/pauldemarco/flutter_blue/issues/524#issuecomment-1118866250)

**Comment by chipweinberger** [comment]
No need to fork. You can just use dart class extensions.

**Comment by chipweinberger** [comment]
<img width="518" alt="Screenshot 2023-08-04 at 6 57 35 PM" src="https://github.com/boskokg/flutter_blue_plus/assets/1863934/2310b837-9936-4072-8574-8c660ddbe1d9">

This is the relevant iOS code.

BmScanResult.device.localName is assigned from [peripheral name]

**Comment by MrCsabaToth** [comment]
> Have not checked with nRF Connect, sorry. No, no Chinese or any other none uni-code characters in the name. Name example is "15KODY0022'. It is showed correctly in the same implementation with flutter_blue_plus in Android but not in iOS. I have one another native iOS app which shows the name correctly.
> 
> Thinking to fork the package and try the suggested workaround [here](https://github.com/pauldemarco/flutter_blue/issues/524#issuecomment-1118866250)

You won't be able to use that workaround as it is, because Flutter Blue Plus doesn't use protocol buffers any more.

**Comment by chipweinberger** [comment]
All the protobuf classes have direct replacements. `x.fromProtos` still exists. 

That said, you should not have to modify any FlutterBluePlus code.

1. make a new file "ble_adv_name.dart", with a variable `Map advNames`
2. when you scan, add the advertised names to that map `advNames[remoteId] = advName`
3. in "ble_adv_name.dart", create a class extension method on BluetoothDevice, BluetoothDevice.getAdvertisingName that returns the name from the map

**Comment by chipweinberger** [comment]
closing this because there are no FBP changes required.

**Comment by elmar001** [comment]
Thanks for the detailed explanation!

**Comment by MrCsabaToth** [comment]
If this happens with multiple users it can be worth adding it to the plugin in the future?
