### ISSUE TITLE
[Question]: Print image

### ISSUE THREAD

**Issue by kyawthet-wam** [boskokg/flutter_blue_plus#487]
### Ask your question

I want to know this package support printing image. I try the following way.

> 

         ByteData imageData = await rootBundle.load('assets/images/b.png');
          Uint8List dataBytes = imageData.buffer.asUint8List();
          for (int i = 0; i < dataBytes.length; i += 20) {
            final chunk = dataBytes.sublist(
                i, i + 20 < dataBytes.length ? i + 20 : dataBytes.length);
            await characteristic.write(chunk);
          }

> 

But the length of byte list is so big and printing unkown charaters.

**Comment by chipweinberger** [comment]
Yes you could use this package to print an image. 

There is also https://pub.dev/packages/blue_print_pos

But you should change its pubspec.yaml to use flutter_blue_plus 1.4.0

**Comment by kyawthet-wam** [comment]
@chipweinberger Thanks for reply. Can you please check which part of my code is wrong ?

**Comment by chipweinberger** [comment]
it looks correct.

perhaps there is a bug elsewhere

**Comment by utkuvrs** [comment]
Hello, this code doesn't work.

It prints out random characters instead.
