### ISSUE TITLE
[Bug]: connected and disconnected event will not send to device's connectionState stream in dart

### ISSUE THREAD

**Issue by leelai** [boskokg/flutter_blue_plus#496]
### FlutterBluePlus Version

1.14.6

### Flutter Version

3.10.0-6.0.pre.27

### What OS?

Android

### OS Version

12

### What happened?

      here is my code snippet,
 
        await device.connect();
        await device.connectionState; <--timeout here (35s), and i found that something wrong in java in the commit today.
        
  Please check here. 
  https://github.com/boskokg/flutter_blue_plus/commit/06511c068b603f93b95a9c74a93e40d07af186d7#r124309109
  
i works after using "&&" instead of "||"

### Logs

```shell
n/a
```

**Comment by chipweinberger** [comment]
fixed in 1.14.7

thanks for reporting. silly mistake!
