### ISSUE TITLE
After I successfully connected the Bluetooth, I always lost the connection for a while and reported an error state=133

### ISSUE THREAD

**Issue by wuchao110** [boskokg/flutter_blue_plus#501]
### FlutterBluePlus Version

1.12.9

### Flutter Version

3.7.10

### What OS?

Android

### OS Version

12.3.1

### What happened?

After I successfully connected the Bluetooth, I always lost the connection for a while and reported an error state=133

### Logs

```shell
D/BluetoothGatt( 9518): onClientConnectionState() - status=133 clientIf=6 device=DC:BE:7A:01:00:42
D/[FBP-Android]( 9518): [FBP-Android] onConnectionStateChange: status: 133 newState: disconnected
D/BluetoothGatt( 9518): close()
D/BluetoothGatt( 9518): unregisterApp() - mClientIf=6
```

**Comment by chipweinberger** [comment]
133 == ANDROID_SPECIFIC_ERROR

 133 can mean anything. This is a common android error code for any problem.

You can read online about the many ways people try to fix it. 

FlutterBluePlus cannot fix this.
