### ISSUE TITLE
[Bug]: writeLarge() method in documentation is incorrect

### ISSUE THREAD

**Issue by eriksoderstrom** [boskokg/flutter_blue_plus#502]
### FlutterBluePlus Version

1.14.9

### Flutter Version

3.10.5

### What OS?

Android

### OS Version

Android 13

### What happened?

The example for the writeLarge extension method is incorrect.

`List<int> subvalue = value.sublist(i, max(i + chunk, value.length));`
In the first loop,`subvalue.length` will always be the length of `value`, causing the write call to throw
`Unhandled Exception: PlatformException(writeCharacteristic, data longer than mtu allows. dataLength: 512 > max: 23, null, null)` error.
Fixed by using "min()" instead of "max()".
I also believe that the call to write should be prefixed with await?

### Logs

```shell
D/[FBP-Android](18511): [FBP-Android] onMethodCall: writeCharacteristic
E/flutter (18511): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(writeCharacteristic, data longer than mtu allows. dataLength: 257> max: 62, null, null)
E/flutter (18511): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (18511): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (18511): <asynchronous suspension>
E/flutter (18511): #2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:302:19)
E/flutter (18511): <asynchronous suspension>
E/flutter (18511): #3      BluetoothCharacteristic.write (package:flutter_blue_plus/src/bluetooth_characteristic.dart:157:7)
E/flutter (18511): <asynchronous suspension>
E/flutter (18511):
```

**Comment by chipweinberger** [comment]
thanks!
