### ISSUE TITLE
[Bug]: (IOS): request pairing is forced for BLE, it doesn't need to pairing devices in BLE mode

### ISSUE THREAD

**Issue by mohsen1javadian** [boskokg/flutter_blue_plus#510]
### FlutterBluePlus Version

1.14.11

### Flutter Version

3.10.3

### What OS?

iOS

### OS Version

14.5.1 iPad os

### What happened?

When we want use BLE connection should not to be forced pairing devices.

### Logs

```shell
no log
```

**Comment by chipweinberger** [comment]
in iOS pairing is automatic if your devise advertises support

FkutterBluePlus cannot control this
