### ISSUE TITLE
[Bug]: Scan shows BLE device forever even after the device is turned off

### ISSUE THREAD

**Issue by manel-github** [boskokg/flutter_blue_plus#512]
### FlutterBluePlus Version

1.12.10

### Flutter Version

3.7.12

### What OS?

Android

### OS Version

30.0.3

### What happened?

Once we start the Scan and extract the ScanResults the list of the devices is incremented with the same object (Ble Device) with a timestamp for each scan. However if one shuts down the BleDevice  (no longer available to be scanned) the ScanResult keeps identifying the BleDevice as though it is there.

Is there a way to reset the ScanResult List at each cycle so that if a Ble Device is no longer in reach or it is shut down it does not appear?

Thank you so much.

### Logs

```shell
...
```

**Comment by chipweinberger** [comment]
There is no way to do that automatically.

you can do it yourself using the scanResult.timestamp

**Comment by chipweinberger** [comment]
here is some chat GPT code

you can use this to continually remit the scanResults

and then you just need to add code to strip out old results 

---

If you have a Dart `Stream` and you want to create another `Stream` that re-emits the most recent value from the original stream every second, you can utilize Dart's `Stream` class combined with the `async*` and `yield` keywords.

Here's a way to achieve this:

1. First, create a function that takes the original `Stream` as an argument.
2. Inside this function, use an `async*` generator function to yield values.
3. Listen to the original `Stream` and store its most recent value.
4. Use a periodic timer to emit the stored value every second.

Here's a code example:

```dart
import 'dart:async';

Stream<T> repeatLatestValueEverySecond<T>(Stream<T> originalStream) async* {
  T? latestValue;

  // Listen to the original stream to get the latest value.
  originalStream.listen((value) {
    latestValue = value;
  });

  // Create a periodic stream that emits every second.
  await for (var _ in Stream.periodic(Duration(seconds: 1))) {
    if (latestValue != null) {
      yield latestValue!;
    }
  }
}

void main() {
  final myStream = Stream<int>.periodic(Duration(seconds: 3), (count) => count).take(5);

  repeatLatestValueEverySecond(myStream).listen((value) {
    print('Repeated value: $value');
  });
}
```

This example creates an original stream `myStream` that emits increasing integers every 3 seconds. The transformed stream, created by the `repeatLatestValueEverySecond` function, will print the most recent value from `myStream` every second.

**Comment by manel-github** [comment]
> There is no way to do that automatically.
> 
> you can do it yourself using the scanResult.timestamp
> 
> make sure you turn on allowDuplicates so that the timestamp is continually updated for each advertisement

Thank you Chipweinberger for the quick reply.

Testing a Ble Device, turning on the "allowDuplicates" and printing the scan result l get the following timestamps:

![image](https://github.com/boskokg/flutter_blue_plus/assets/60964677/69ac686a-7362-41e3-b1ae-ff2b8a82bc62)
  
When the timestamp is at 09:48:31.180249 I turn off the Ble Device. From that point forward I do not identify any parameter change including the timestamp which continues to go forward, that may help me to identify that the the Ble Device is no longer available (out of reach or turned off). 

What is it that I'm missing?

Thank you.

**Comment by chipweinberger** [comment]
could be a bug

**Comment by chipweinberger** [comment]
I dont see any obvious bugs. You might need to figure it out yourself.

**Comment by manel-github** [comment]
Thank you for the help ChipWeinberger

**Comment by chipweinberger** [comment]
did you figure out the timestamp issue?

**Comment by chipweinberger** [comment]
closing. this is expected behavior.

**Comment by chipweinberger** [comment]
btw, in newer FBP you can use `onScanResults` instead of `scanResults` to fix this behavior.
