### ISSUE TITLE
[Question]: How manage cross connection with different iOS device

### ISSUE THREAD

**Issue by AndreaGiulianini** [boskokg/flutter_blue_plus#514]
### FlutterBluePlus Version

1.14.11

### Flutter Version

3.10.6

### What OS?

iOS

### OS Version

16.15.1

### Ask your question

I want to save users' BLE devices to a database and give them the ability to reconnect to the same device from different iOS devices, without having to rescan but using the remoteId used previously.

On Android saving the remoteId everything works, on iOS it doesn't because the remoteId is unique per iOS device.

How can I solve this? What data can I save?

### Logs

```shell
*
```

**Comment by chipweinberger** [comment]
completely impossible on ios
