### ISSUE TITLE
[Question]: Error on printing qr code

### ISSUE THREAD

**Issue by caini1213** [boskokg/flutter_blue_plus#520]
### FlutterBluePlus Version

1.14.11

### Flutter Version

3.10.4

### What OS?

Android

### OS Version

11

### Ask your question

Hi, I was trying to print QR code but then error throw as below : 

"The WRITE property is not supported by this BLE characteristic" and
"data longer than mtu allows. dataLength: 456> max: 20"

### Logs

```shell
PlatformException(writeCharacteristic, The WRITE property is not supported by this BLE characteristic, null, null)

PlatformException(writeCharacteristic, data longer than mtu allows. dataLength: 512> max: 20, null, null)
```

**Comment by chipweinberger** [comment]
the problem is in your code or, the ble device code.

**Comment by caini1213** [comment]
> the problem is in your code or, the ble device code.

can i show u my code to see where should i modify?

**Comment by chipweinberger** [comment]
i won't know. i've never used ble printing

**Comment by caini1213** [comment]
how to say the problem might in my ble device code ya?

**Comment by chipweinberger** [comment]
you can also try write(withoutResponse:true)
