### ISSUE TITLE
[Bug]: Timestamp of Scan Result Not Updating in iOS Version

### ISSUE THREAD

**Issue by leelai** [boskokg/flutter_blue_plus#529]
### FlutterBluePlus Version

Dart SDK 3.1.0-11.0.dev

### Flutter Version

3.10.0-6.0.pre.27

### What OS?

iOS

### OS Version

12

### What happened?
I used example and just change scan duration to 1500sec to avoid keeping pressing scan button.
FlutterBluePlus.startScan(timeout: const Duration(seconds: 1500), androidUsesFineLocation: false);
and  i observe that the timestamp of the scan results remains static and doesn't update as expected.
 
class ScanResult {
  final BluetoothDevice device;
  final AdvertisementData advertisementData;
  final int rssi;
  final DateTime timeStamp; <--here.

The timestamp of scan results should update in real-time as new scan data is received from nearby Bluetooth devices on iOS devices, just like it does on the Android version.

**Comment by leelai** [comment]
and i found example will updated the timestamp of all my apple devices(ipad, macbook..), but non-apple devices will not.

**Comment by leelai** [comment]
I need to keep pressing scan button in example app to make timestamp of scan result updated.

**Comment by chipweinberger** [comment]
does allowDuplicates fix it?

**Comment by leelai** [comment]
allowDuplicates works. thank you.
