### ISSUE TITLE
How can i check connecting device state?

### ISSUE THREAD

**Issue by chinzorigts** [boskokg/flutter_blue_plus#53]
Please help me!

How can i check connecting or disconnecting device state value in dart code?

I am using StreamBuilder<BluetoothDeviceState>. But it is only returning connected, disconnected device state value.

**Comment by WeiKuang** [comment]
StreamBuilder<BluetoothDeviceState>(
                                              stream: ble.bluetoothDevice.state,
                                              initialData: BluetoothDeviceState.disconnecting,
                                              builder: (c, state) {
                                                switch (state.data) {
                                                  case BluetoothDeviceState.connected:
                                                    break;
                                                  case BluetoothDeviceState.disconnected:
                                                    break;
                                                  case BluetoothDeviceState.connecting:
                                                    text = '连接中';
                                                    break;
                                                  case BluetoothDeviceState.disconnecting:
                                                    break;
                                                  default:
                                                    break;
                                                }
