### ISSUE TITLE
[Question]: Is it possible that two android devices connect to each other and send messages to each other ?

### ISSUE THREAD

**Issue by Eashubh128** [boskokg/flutter_blue_plus#530]
### FlutterBluePlus Version

1.14.11

### Flutter Version

3.10.6

### What OS?

All

### OS Version

/

### Ask your question

I have a weird question , whether or not two android devices connect and send messages to each other . Like a chat application but with ble .

### Logs

```shell
/No Logs
```

**Comment by chipweinberger** [comment]
see the readme. you'd need to implement ble peripheral role
