### ISSUE TITLE
[Feature]: macos requires 12.0, can it be lowered?

### ISSUE THREAD

**Issue by mengzhidaren** [boskokg/flutter_blue_plus#533]
### FlutterBluePlus Version

1.4.11

### Flutter Version

3.13.0

### What OS?

macOS

### OS Version

macos 10.14

### Feature Request

`
s.platform = :osx, '12.00'

s.framework = 'CoreBluetooth'
`
There are still many old macos versions on the market that are only 10.14. The macos version upgrade may not be as fast as ios. Why does the version support on the macos platform start from 12.0? I don’t know much about macos development, but I inquired about CoreBluetooth. Support is low Version, is there any plan to support lower version platforms in the future?

**Comment by chipweinberger** [comment]
I'm not sure. I imagine it was set to 12.00 to fix some build error.

You can try setting it lower, I'm sure it will work no problem.

**Comment by chipweinberger** [comment]
did you try lowering it?

**Comment by chipweinberger** [comment]
fixed in 1.14.16

lowered to `macos 10.11`

**Comment by mengzhidaren** [comment]
Many thanks to the author for his contribution
