### ISSUE TITLE
is the startscan scan the ble devices that are connected to any other device? 

### ISSUE THREAD

**Issue by ranjitIN** [boskokg/flutter_blue_plus#535]
### FlutterBluePlus Version

1.4.11

### Flutter Version

3.10.6

### What OS?

Android, iOS

### OS Version

12.3.1

### Ask your question

i wanna to know how to scan ble devices that are already connected to any other device.

### Logs

```shell
no logs
```

**Comment by chipweinberger** [comment]
You cannot. 

If the device stops advertising, you cannot discover it. This is impossible.
