### ISSUE TITLE
[Bug]: the device turned off，but the disconnect is not called.

### ISSUE THREAD

**Issue by zhou5852** [boskokg/flutter_blue_plus#538]
### FlutterBluePlus Version

1.14.9

### Flutter Version

3.10.6

### What OS?

iOS

### OS Version

IOS 16

### What happened?

The device turned off ,but the disconnect is not called，I use wireshark and tools to found my device send “
.... ..01 = LLID: Continuation fragment of an L2CAP message, or an Empty PDU (0x1)" between the master and slave,
but I turned off my device, the master send "Empty PDU" ， our API can't be called  because some problem。 May be we should solve this problem 。

<img width="1675" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/5857054/00a1febd-6992-48ca-b531-8aa7ea1f464a">

<img width="1675" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/5857054/1f0594b1-395e-4fbd-a1e9-bfe557056233">

### Logs

```shell
14915	345.412	Master_0xaf9ab59b	LE 1M	LE LL	192	48442µs	0	0	False	711			L2CAP Fragment
15166	352.282	Slave_0xaf9ab59b	LE 1M	LE LL	4	150µs	1	0	False	852			L2CAP Fragment
15184	353.013	Slave_0xaf9ab59b	LE 1M	LE LL	1	149µs	0	1	False	867			L2CAP Fragment
15266	355.450	Master_0xaf9ab59b	LE 1M	LE LL	1	48670µs	0	0	False	917			L2CAP Fragment
15384	358.718	Slave_0xaf9ab59b	LE 1M	LE LL	96	150µs	0	1	False	984			L2CAP Fragment
15434	360.424	Slave_0xaf9ab59b	LE 1M	LE LL	96	149µs	0	1	False	1019			L2CAP Fragment
15518	362.778	Slave_0xaf9ab59b	LE 1M	LE LL	4	149µs	0	1	False	1069			L2CAP Fragment
15552	363.802	Slave_0xaf9ab59b	LE 1M	LE LL	4	149µs	1	0	False	1090			L2CAP Fragment
15589	364.874	Slave_0xaf9ab59b	LE 1M	LE LL	64	150µs	0	1	False	1112			L2CAP Fragment
```

**Comment by zhou5852** [comment]
<img width="1678" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/5857054/d18a9c4e-ec9a-485e-9f95-70b2c564a401">

**Comment by chipweinberger** [comment]
FlutterBluePlus uses the `onConnectioStateChanged` callback from the OS platform to detect disconnection.

do you think this is a bug in iOS?

**Comment by chipweinberger** [comment]
any updates?

**Comment by zhou5852** [comment]
OK，I'm sorry to late response,Yes!!! it's ok and work well, I test my app, our plugins can get the EmptyPDU not response event and connectionstate changed。

**Comment by zhou5852** [comment]
Thanks a lot , I love FlutterBluePlus。
