### ISSUE TITLE
[Question]: When call device.createBond() application crashes

### ISSUE THREAD

**Issue by alisherbu** [boskokg/flutter_blue_plus#551]
### FlutterBluePlus Version

1.14.23

### Flutter Version

3.13.1

### What OS?

Android

### OS Version

Samsung Android 12

### Ask your question

But If I call device.connect(), everything work fine. To connect to device, first we should bond/pair. Is it right? However, device.connect() method is doing bond/pair and connect operations.

### Logs

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(createBond, device is disconnected, null, null)
```

**Comment by chipweinberger** [comment]
You cannot create a bond with a disconnected device. 

**Question for you:** is the error confusing?

i.e. `PlatformException(createBond, device is disconnected`.

How could I make the flutter blue plus api better?

Doe `PlatformException` make it seem like FBP is misbehaving?

Would It be better if I throw this error from the dart side? as a FlutterBluePlusException?

**Comment by alisherbu** [comment]
Wow, thank you!
