### ISSUE TITLE
[Bug]: Characteristics send duplicate notifications when device is reconnected

### ISSUE THREAD

**Issue by changewhite** [boskokg/flutter_blue_plus#559]
### FlutterBluePlus Version

1.15.5

### Flutter Version

3.10.6

### What OS?

Android

### OS Version

Android 13

### What happened?

Characteristics are sending duplicate notifications when device is reconnected
![ad0c4192f19eda57ebf1feda47e4720](https://github.com/boskokg/flutter_blue_plus/assets/45277365/fd48c494-8dd6-4789-a6ef-c832597a1eb4)

### Logs

```shell
No error log output
```

**Comment by chipweinberger** [comment]
logs are needed. Ideally verbose logs. 

please reopen when you have logs.

I'm not aware of any code in FBP that would cause this.

**Comment by chipweinberger** [comment]
you need to stop listening to the stream (i.e. call `cancel`) when you disconnect

```
  final subscription = stream.listen((data) {
    print('Data: $data');
  });

  await subscription.cancel();
```
