### ISSUE TITLE
[1.15.0]: MacAddresses filtering when scanning

### ISSUE THREAD

**Issue by dlewis2017** [boskokg/flutter_blue_plus#563]
### FlutterBluePlus Version

1.15.2

### Flutter Version

3.13.0

### What OS?

iOS

### OS Version

iPadOS 16.6.1

### What happened?

More of a feature request than bug but - The scan function that allows filtering by MacAddresses is deprecated. Could the mac address filtering be added back in for developer testing when multiple Bluetooth devices with the same build are being tested by different developers? Thanks.

### Logs

https://github.com/boskokg/flutter_blue_plus/blob/49066942fbacd324c46b58b9f062ee125535f703/lib/src/flutter_blue_plus.dart#L371

**Comment by chipweinberger** [comment]
it is easy to filter by mac address in your own code, so I do not plan to add this feature.

but thank you for filing :)

**Comment by chipweinberger** [comment]
if you're reading this in the future, see [MIGRATION.md](https://github.com/boskokg/flutter_blue_plus/blob/master/MIGRATION.md)

**Comment by dlewis2017** [comment]
@chipweinberger I wanted to circle back to this because it seems the remoteId associated with the device is a 128-bit uuid. Mac Addresses seem to have a [different format](https://www.cmu.edu/computing/services/endpoint/network-access/mac-address.html) Is remoteId definitely where the macAddress exsits?

**Comment by chipweinberger** [comment]
yes use remoteId

macAddress was just a bad name imo.

**Comment by chipweinberger** [comment]
this has been added back, btw. use 1.26.0+
