### ISSUE TITLE
startScan call back is triggered when scan is started, we need a callback when it is done

### ISSUE THREAD

**Issue by ekabiri** [boskokg/flutter_blue_plus#568]
### FlutterBluePlus Version

1.15.5

### Flutter Version

3.9.0-1.0.pre.52

### What OS?

All

### OS Version

iOS 16.3.1

### What happened?

the older version behavior was as expected and when startScan passed the timeout duration call_back was called and user could proceed with after scan tasks.
in New version user has to define a separate Timer so when it passes scan duration it starts after scan tasks.  

### Logs

```shell
NA
```

**Comment by chipweinberger** [comment]
use `FlutterBluePlus.isScanning`

**Comment by chipweinberger** [comment]
see [MIGRATION.md](https://github.com/boskokg/flutter_blue_plus/blob/master/MIGRATION.md)
