### ISSUE TITLE
[Bug]: Readable/writable characteristic is not readable/writable in Android

### ISSUE THREAD

**Issue by qawitherev** [boskokg/flutter_blue_plus#573]
### FlutterBluePlus Version

1.14.12

### Flutter Version

3.13.2

### What OS?

All

### OS Version

Android 12, iOS 16.4

### Bluetooth Module

Esp32

### What happened?

Readable/writable characteristic is not readable/writable in Android. Sample code: 

`void provisionTest() async {`
`await getServiceList();`
`getCharacteristics();`
`final ourCharacteristics = characteristicsList[0];`
`final canRead = ourCharacteristics.properties.read;`
`print("QAWI3 - can read: $canRead");`
`}`

On Android 12: 
<img width="354" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/59358911/dd8b32d5-ed4f-416c-b722-267dd8d8af22">

On iOS 16.4, behaves like what expected: 
<img width="354" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/59358911/461bab11-7e95-4715-a272-cc0f511954f6">

### Logs

```shell
Above picture
```

**Comment by chipweinberger** [comment]
thanks for filing.

Can you add some logs to the android java code? to see if this issue is in android OS or fbp code

**Comment by qawitherev** [comment]
Init BLE
<img width="561" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/59358911/2adcec4a-a87a-4fe6-9774-1861fc1bae60">

Scanning
<img width="704" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/59358911/61f4f1e4-2c47-454e-80fc-0be1ca048e0c">

Connecting
<img width="821" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/59358911/e5d99413-3a55-4717-afb7-6d0b7f4cf250">

Read Attempt
<img width="1079" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/59358911/4fde2ea5-1fb6-4896-ad69-8ca857308b5c">

**Comment by chipweinberger** [comment]
This is the java code

```
    HashMap<String, Object> bmCharacteristicProperties(int properties) {
        HashMap<String, Object> props = new HashMap<>();
        props.put("broadcast",                      (properties & 1)   != 0 ? 1 : 0);
        props.put("read",                           (properties & 2)   != 0 ? 1 : 0);
        props.put("write_without_response",         (properties & 4)   != 0 ? 1 : 0);
        props.put("write",                          (properties & 8)   != 0 ? 1 : 0);
        props.put("notify",                         (properties & 16)  != 0 ? 1 : 0);
        props.put("indicate",                       (properties & 32)  != 0 ? 1 : 0);
        props.put("authenticated_signed_writes",    (properties & 64)  != 0 ? 1 : 0);
        props.put("extended_properties",            (properties & 128) != 0 ? 1 : 0);
        props.put("notify_encryption_required",     (properties & 256) != 0 ? 1 : 0);
        props.put("indicate_encryption_required",   (properties & 512) != 0 ? 1 : 0);
        return props;
    }
```

**Comment by chipweinberger** [comment]
You should also print the uuid to make sure you are comparing the same thing

print("QAWI3 - can read: $canRead uuid ${chr.uuid}");

**Comment by qawitherev** [comment]
ok, found another weird thing, idk if this supposed to be happening
<img width="741" alt="image" src="https://github.com/boskokg/flutter_blue_plus/assets/59358911/01d7f97e-cef8-4431-b241-2b8ccb88e9ea">

on ios, theres only 2 characteristics (as it should), but on android there's 3 of them with different uuid as its ios counterpart

**Comment by chipweinberger** [comment]
ya that's fine. iOS handles some ble characteristics internally, whereas android exposes them.

**Comment by chipweinberger** [comment]
ignore the characteristics you don't care about

**Comment by qawitherev** [comment]
The characteristics that I want to interact with are ff01 and ff02, but in android, the service doesn't have these characteristics.
