### ISSUE TITLE
[Bug]: PlatformException(startScan, getBluetoothLeScanner() is null. Is the Adapter on?, null, null)

### ISSUE THREAD

**Issue by HuangWenJunGT** [boskokg/flutter_blue_plus#576]
### FlutterBluePlus Version

1.15.8

### Flutter Version

3.10.5

### What OS?

Android

### OS Version

13

### Bluetooth Module

Nordic 52840

### What happened?

Calling the startScan method on an Android 13 phone will result in the following error. Unable to scan surrounding Bluetooth devices properly. But on phones under Android 13, they can be used normally。

### Logs

```shell
W/BluetoothAdapter(18400): getBluetoothLeScanner() ble not available
E/flutter (18400): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(startScan, getBluetoothLeScanner() is null. Is the Adapter on?, null, null)
E/flutter (18400): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (18400): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (18400): <asynchronous suspension>
E/flutter (18400): #2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:325:13)
E/flutter (18400): <asynchronous suspension>
E/flutter (18400): #3      FlutterBluePlus.startScan (package:flutter_blue_plus/src/flutter_blue_plus.dart:159:5)
E/flutter (18400): <asynchronous suspension>
```

**Comment by chipweinberger** [comment]
permissions issue?

is bluetooth on?

**Comment by ogak-github** [comment]
In my case, FBP stopped at getAdapterState. The value is null.
![image](https://github.com/boskokg/flutter_blue_plus/assets/116913354/a7431b85-6952-410b-af52-2eccc7f6bcf4)
![image](https://github.com/boskokg/flutter_blue_plus/assets/116913354/354f4002-6377-4efb-97ad-8a3afa8fc549)

Tested on Android OS : 6.0.1

**Comment by HuangWenJunGT** [comment]
I confirm that Bluetooth is enabled and declare the following permissions in AndroidManifest.xml:
uses permission android: name="android. permission. BLUETOOTH"
uses permission android: name="android. permission. BLUETOOTH_ADMIN"
uses permission android: name="android. permission. BLUETOOTH_SCAN"
uses permission android: name="android. permission. BLUETOOTH_CONNECT"
uses permission android: name="android. permission. BLUETOOTH_ADVERTISE"
uses permission android: name="android. permission. ACCESS_COARSE_LOCATION"
uses permission android: name="android. permission. ACCESS-FINE_LOCATION"

In addition, during runtime, the following permissions were dynamically applied for：
Permission.bluetoothScan,
Permission.bluetoothConnect,
Permission.bluetoothAdvertise,
Permission.locationWhenInUse,

The testing phones I use are Xiaomi 13 and Samsung S22

**Comment by chipweinberger** [comment]
not sure. do other scanner apps work?

**Comment by HuangWenJunGT** [comment]
I tried using several other Bluetooth libraries and reported error messages similar to the one I provided above.
I carefully reviewed the changes in Android 13 compared to 12, but did not find any significant changes in the Bluetooth section.
Can you try using an Android 13 phone to see if it can solve this problem

**Comment by chipweinberger** [comment]
Did you figure it out?

**Comment by HuangWenJunGT** [comment]
I'm very sorry, it's my problem. After multiple tests, it runs normally on Android 13.

**Comment by chipweinberger** [comment]
what was the issue?

**Comment by chipweinberger** [comment]
bump, what was the issue?
