### ISSUE TITLE
[Help]: Quick Question. on compatibility with Riverpod_generator and mcumgr_flutter

### ISSUE THREAD

**Issue by nissaba** [boskokg/flutter_blue_plus#591]
### FlutterBluePlus Version

^1.15.10

### Flutter Version

3.13.5

### What OS?

Android, iOS

### OS Version

12

### Bluetooth Module

Nordic

### Ask your question

hello, I wanted to know if this package is compatible to use with the mcumgr_flutter aka: the Nordic DFU API. 
I have started a project using the flutter_reactive_ble and I am not able to get the API to update on the connection status. 

So I want to try this API, but I do wish to know first if it is compatible with using the mcumgr_flutter package. 

I am also using Riverpod for state management and using the riverpod generator to generate the providers. 

### Logs

```shell
- no logs
```

**Comment by chipweinberger** [comment]
it's probably compatible. but only you can determine that by trying.

If it was not compatible, that would be a big issue for Nordic DFU API.
