### ISSUE TITLE
[Bug]: IOS getConnectedSystemDevices can not get device's name

### ISSUE THREAD

**Issue by SmallBlueWhale** [boskokg/flutter_blue_plus#595]
### FlutterBluePlus Version

1.15.10

### Flutter Version

3.10.0

### What OS?

iOS

### OS Version

ios 16.0.0

### Bluetooth Module

unknown

### What happened?

When i use getConnectedSystemDevices , i got empty local name in Dart as picture shown below. 
![image](https://github.com/boskokg/flutter_blue_plus/assets/16556147/add8b337-35ae-46eb-bcc6-22d536026c2a)

Also i debug the code in Xcode. i found that i can get the name in this code as picture shown below , but the cache is empty. The name has no usages. Can you fix this?
![image](https://github.com/boskokg/flutter_blue_plus/assets/16556147/97fb8d24-52f1-4dac-bcd4-45e361916c03)
![image](https://github.com/boskokg/flutter_blue_plus/assets/16556147/ea3f48f0-d33f-493c-8062-0401073dc382)
![image](https://github.com/boskokg/flutter_blue_plus/assets/16556147/93ceec37-82da-4935-afb4-ea3dce87947b)

### Logs

```shell
as picture shown
```

**Comment by chipweinberger** [comment]
thanks for filing. I'll consider a solution to this.

**Comment by chipweinberger** [comment]
try master branch.

**Comment by chipweinberger** [comment]
fixed in 1.16.0
