### ISSUE TITLE
[Bug]: about bluetooth receiving data with connected device

### ISSUE THREAD

**Issue by Mani2049** [boskokg/flutter_blue_plus#597]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### FlutterBluePlus Version

flutter_blue_plus: ^1.5.2

### Flutter Version

flutter 3.13.1

### What OS?

Android, iOS

### OS Version

version 11.7.9

### Bluetooth Module

esp-32

### What happened?

https://blog.flutterflow.io/creating-an-app-for-interacting-with-any-iot-devices-using-ble/
i followed this link to solve my problem but i stuck under receive data function its not receiving a response. from my device. and i used to read like this await characteristic.read()

### Logs

```shell
1.5.2 
[fix] Android: setNotification was throwing exception (regression)
```

**Comment by BachewalSuresh** [comment]
we also facing same bluetooth receiving data  issue please solve head of the department

**Comment by BachewalSuresh** [comment]
import 'package:flutter_blue_plus/flutter_blue_plus.dart';

Future<String?> receiveData(BTDeviceStruct deviceInfo) async {
  final device = BluetoothDevice.fromId(deviceInfo.id, name: deviceInfo.name);
  final services = await device.discoverServices();
  for (BluetoothService service in services) {
    for (BluetoothCharacteristic characteristic in service.characteristics) {
      final isRead = characteristic.properties.read;
      final isNotify = characteristic.properties.notify;
      if (isRead && isNotify) {
        final value = await characteristic.read();
        return String.fromCharCodes(value);
      }
    }
  }
  return null;
}

this code we are using to receive a data from my esp-32 device

**Comment by chipweinberger** [comment]
you need to include logs 

logs are required

**Comment by chipweinberger** [comment]
upgrade to latest version

`flutter_blue_plus: 1.16.1`

then make some small changes to code. see `MIGRATION.md` file.

**Comment by BachewalSuresh** [comment]
where do i find MIGRATIOn.md file

**Comment by BachewalSuresh** [comment]
> where do i find MIGRATIOn.md file

MIGRATION.md

**Comment by BachewalSuresh** [comment]
i am facing a problem with stripe payment getting me that [An unknown error occurred] in flutterflow project.
