### ISSUE TITLE
[Bug]: After setting the Notify value to true and reading characteristics, onValueReceived does not work

### ISSUE THREAD

**Issue by rahul110897** [boskokg/flutter_blue_plus#604]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### FlutterBluePlus Version

1.16.4

### Flutter Version

3.13.6

### What OS?

All

### OS Version

Latest

### Bluetooth Module

PSoC 6 Board

### What happened?

After setting the Notify value to true and reading characteristics, onValueReceived does not work

### Logs

```shell
logs are not coming
```

**Comment by chipweinberger** [comment]
not enough details. cannot help you.

**Comment by rahul110897** [comment]
In flutter_blue_plus  Version "1.16.2 " this functionality is working fine but in the "1.16.4" version not working.

**Comment by chipweinberger** [comment]
i've retracted 1.16.4. use older version.

**Comment by rahul110897** [comment]
In flutter_blue_plus Version "1.16.2 " this functionality is working fine but in the "1.16.3" version not working.

**Comment by chipweinberger** [comment]
try master branch

**Comment by rahul110897** [comment]
The issue "[Fix] Android: setNotify would time out if CCCD descriptor did not exist" has been resolved from your end. Have you implemented any additional code from our end?

**Comment by chipweinberger** [comment]
> Means Which Plugin Version?

master branch. change pubspec.yaml to master branch. google for directions.

**Comment by rahul110897** [comment]
I am not getting any platform

![Screenshot 2023-10-06 at 3 39 52 PM](https://github.com/boskokg/flutter_blue_plus/assets/109333361/498ea8ed-594a-4d60-8330-bbf944118480)

**Comment by chipweinberger** [comment]
that is a problem with pub.dev.  There is a delay. wait 10 minutes.

**Comment by rahul110897** [comment]
Ok thanks for the update and quick response we appreciate.
