### ISSUE TITLE
[Bug]: Unhandled exception when connecting to a peripheral

### ISSUE THREAD

**Issue by OnlySid** [boskokg/flutter_blue_plus#605]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### FlutterBluePlus Version

^1.16.3 (Works fine in 1.16.2)

### Flutter Version

3.13.6

### What OS?

All

### OS Version

Latest

### Bluetooth Module

BGM111

### What happened?

Since 1.16.3, something happens that assumes the bool "changed" influtter_blue_plus/src/bluetooth_device.dart:64 is an int and the exception is unhandled. This persists in 1.16.4 as well.

### Logs

```shell
2023-10-06 09:55:28.908 wheeltune[4702:94237] [FBP-iOS] handleMethodCall: startScan
2023-10-06 09:55:33.390 wheeltune[4702:94237] [FBP-iOS] handleMethodCall: connect
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'int' is not a subtype of type 'bool'
#0      BluetoothDevice.connect
package:flutter_blue_plus/src/bluetooth_device.dart:64
<asynchronous suspension>
```

**Comment by chipweinberger** [comment]
same https://github.com/boskokg/flutter_blue_plus/issues/603
