### ISSUE TITLE
[Help]:  After writing to a Bluetooth characteristic using characteristic.setNotifyValue(!characteristic.isNotifying), there are instances where data is not received in the onValueReceived stream.

### ISSUE THREAD

**Issue by faiyaz-shaikh** [boskokg/flutter_blue_plus#607]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### FlutterBluePlus Version

1.14.24

### Flutter Version

3.10.0

### What OS?

Android, iOS

### OS Version

android 12, iPadOS 16.6

### Bluetooth Module

Blu-Dex 

### Summary
After writing to a Bluetooth characteristic using `characteristic.setNotifyValue(!characteristic.isNotifying)`, there are instances where data is not received in the `onValueReceived` stream.

### Steps to Reproduce
1. Write to a Bluetooth characteristic using `characteristic.setNotifyValue(!characteristic.isNotifying)`.
2. Listen for characteristic updates using `characteristic.onValueReceived`.
3. Observe that sometimes data is not received after the write operation.

### Expected Behavior
The `onValueReceived` stream should consistently provide updates after a write operation on the Bluetooth characteristic.

### Code Sample
```dart
await characteristic.setNotifyValue(!characteristic.isNotifying);
await _onWriteData(bluetoothCharacteristic!);
streamSubscription = characteristic.onValueReceived.listen((value) async {
  // Switch cases for handling characteristic values
  switch (cases) {
    // Handle characteristic values
   // Characteristics Write operations
  // await characteristic.write(data, withoutResponse: true);
  }
});

Future<void> _onWriteData(BluetoothCharacteristic characteristic) async {
   
    startTimer();
   
    state.current = States.beginning;
    ackNum = 1; 
    dexValues = [];
    previousValue = [];
    receivedID = [];
    newPacket = [];

  
    await characteristic.writeLarge(_getLineBreakBytes());
   
    await characteristic.writeLarge(_getEnqBytes());
   
  }


### Logs

```shell
..
```

**Comment by chipweinberger** [comment]
you did not read the README common problems!

**Comment by chipweinberger** [comment]
## onValueReceived is never called

onValueReceived is only called for reads & notifies, not writes.

You can do a single read with await characteristic.read(...)
