### ISSUE TITLE
Bluetooth connection problem

### ISSUE THREAD

**Issue by HanJiuYuan** [boskokg/flutter_blue_plus#61]
How to judge bluetooth status when the program is still connected after the bluetooth device is manually shut down

**Comment by Hitbee-dev** [comment]
``` dart
BluetoothDeviceState event
```
Please check this out

**Comment by HanJiuYuan** [comment]
> ```dart
> BluetoothDeviceState event
> ```
> 
> 请检查一下

Can you tell me the specific way to achieve it?

**Comment by HanJiuYuan** [comment]
> For example, The code below is included in DeviceScreen.
> 
> ![image](https://user-images.githubusercontent.com/83276163/169482970-e22f0160-d358-4c05-879e-59815da8bd00.png)
> 
> `print("snapshot.data: ${snapshot.data}");` You can use to get the current state.
> 
> Result: ![image](https://user-images.githubusercontent.com/83276163/169482719-e08f1e9a-0881-4501-9619-7fe8856a91e4.png)

Thank you. That's very helpful
