### ISSUE TITLE
[Help]: Disconnect code 133 ANDROID_SPECIFIC_ERROR

### ISSUE THREAD

**Issue by kyleb-app** [boskokg/flutter_blue_plus#612]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### FlutterBluePlus Version

1.15.8

### Flutter Version

3.13.5

### What OS?

Android

### OS Version

12

### Bluetooth Module

STM32

### Ask your question

The problem is I stop being able to connect to my bluetooth module after about 15 minutes of using my app.

Things I have tried:
* turnOff() then turnOn() before every connect
* clearGattCache() before every connect
* removeBond() after every disconnect
* stopScan() before every reconnect

Restarting the App resolves this issue.

I am not sure I am handling connects/disconnects correctly... this issue ONLY occurs after a successful connection to the peripheral, then a successful disconnection. After this, another attempt to reconnect returns the error code (usually), sometimes a reconnect will happen 1 or 2 times before we receive the 133 error. Is there some way I should be saving the bluetooth device, and handling a reconnect differently than a standard connect?

### Logs

```shell
I/flutter (16641): [FBP] [[ OnConnectionStateChanged ]] result: {disconnect_reason_code: 133, disconnect_reason_string: ANDROID_SPECIFIC_ERROR, remote_id: C0:80:E1:26:D2:BB, connection_state: 0}
```

**Comment by chipweinberger** [comment]
I would catch the error and reattempt the connection 2-3 more times.

ANDROID_SPECIFIC_ERROR is difficult to solve. You can google and there are lots of suggestions.

**Comment by kbessemer** [comment]
> I would catch the error and reattempt the connection 1-2 more times.
> 
> ANDROID_SPECIFIC_ERROR is difficult to solve. You can google and there are lots of suggestions.

Re-attempting the connection is not solving the problem

**Comment by chipweinberger** [comment]
Something you can try: 

1. Clone the repo & update pubspec.yaml
```
  flutter_blue_plus:
    path: /user/downloads/flutter_blue_plus
```

2. Then search the codebase for `getMutexForKey`

<img width="406" alt="Screenshot 2023-10-09 at 3 35 42 PM" src="https://github.com/boskokg/flutter_blue_plus/assets/1863934/f634f94d-4f92-4a4b-9bdd-36a89d2c0cc1">

3. Replace all references with this:

```
    String key = "bluetoothMutex";
    _Mutex readMutex = await _MutexFactory.getMutexForKey(key);
```

The one exception is `_MutexFactory.getMutexForKey("invokeMethod")`.  DO NOT CHANGE THIS.

**With these changes, your bluetooth code will only do 1 bluetooth operation at a time.**

You could also try adding a delay to `_Mutex.take`

```
  Future<void> take() async {
    ... original code ...
    await Future.delayed(Duration(milliseconds:500)); // slow everything down
  }
```

**Comment by chipweinberger** [comment]
last suggestion, do not use `autoConnect` if you are using it.

**Comment by kbessemer** [comment]
Thank you for the help, I have been testing for the last hour on Android 12 and the issue seems resolved. I changed the timeout in the task function to 100ms and it did the trick. Also did the other change you recommended with 'key'.

I am wondering if you could shed some light as to why you think this was happening, I am new to BLE. I am basically downloading data from my bluetooth peripheral, and with each Read I am making a Write as an ACK or NACK. This is all happening very fast. We have over 12,000 data points being sent total, across all received payloads. Between each set of READ/WRITE I am doing an await timeout of 250ms, then moving on to the next payload.

**Comment by chipweinberger** [comment]
I've read online that android bluetooth is bad at doing multiple things

https://medium.com/@martijn.van.welie/making-android-ble-work-part-1-a736dcd53b02

**Comment by kbessemer** [comment]
I am wondering if you know if this would break anything on iOS, because my download process is failing on iOS now... should I make the change to the keys variable specific to Android only?

**Comment by chipweinberger** [comment]
It wont break it, but it will just make everything slower.

**Comment by kbessemer** [comment]
I found what was happening on iOS, the fix you gave has resolved my issue on Android & iOS

**Comment by chipweinberger** [comment]
can you give detailed explanation to help me =)

**Comment by kbessemer** [comment]
The problem on iOS was unrelated to the code you had me change, but it was effecting something that was specific to iOS... the change to FBP plugin seemed to make a pending read/write not return at the same point it used to. That is what was effecting my app, but it was an easy fix - the fix was not to FBP code.

**Comment by chipweinberger** [comment]
glad you figured it out!

**Comment by NaeemUllah121** [comment]
I/flutter (22603): [FBP] [[ OnConnectionStateChanged ]] result: {disconnect_reason_code: 133, disconnect_reason_string: ANDROID_SPECIFIC_ERROR, remote_id: FF:10:32:40:00:5E, connection_state: 0}   
i have tried all the things but it still gives me same error when i try to connect with ecel fob device

**Comment by chipweinberger** [comment]
probably a device problem

**Comment by NaeemUllah121** [comment]
can you suggest what could be the problem of device?

**Comment by NaeemUllah121** [comment]
Even i have tested it on different devices it shows same problem on android when ever i try to connect with ecel fob band device

**Comment by IHNEL** [comment]
hi @chipweinberger 
I have similar issue and finally found that it's caused if I add this line in my connecting feature:
>     device.cancelWhenDisconnected(subscription, delayed: true, next: true);

Remove this line fixes the issue for me, can't tell why but I hope this is helpful to find out root cause.

**Comment by burekas7** [comment]
Any ideas how can I verify if it's a device issue or an Android issue?
Do I must modify files?
