### ISSUE TITLE
[Help]: onValueReceived not working on Android 10

### ISSUE THREAD

**Issue by rahul110897** [boskokg/flutter_blue_plus#619]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.17.5

### Flutter Version

3.13.7

### What OS?

Android

### OS Version

10

### Bluetooth Module

PSoC 6 Board

### What is your problem?

The below issue is not resolved in Android 10, it is working in android 12 and Android 13.
**"Android: onValueReceived was not working on Android 12 & lower"**

### Logs

```shell
No
```

**Comment by chipweinberger** [comment]
if you fix it, please open a PR

**Comment by rahul110897** [comment]
- No logs or crashes have been reported to us, but we have received notified values in Android 12 and 13.

**Comment by rahul110897** [comment]
- This issue is from our side so I have closed this ticket.
