### ISSUE TITLE
[Help]: Why can I still scan the device after it is powered off?

### ISSUE THREAD

**Issue by shuizhuyu1015** [boskokg/flutter_blue_plus#620]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.17.3

### Flutter Version

3.3.2

### What OS?

Android, iOS

### OS Version

Android 12, iOS 16.6

### Bluetooth Module

Nordic nRF5

### What is your problem?

After the device is disconnected automatically, `startScan()`is called again, and the device that has been powered off is still returned in `scanResults`.

Only after `hot restart`,  `scanResults` show no devices that have been powered off.

### Logs

```shell
no logs
```

**Comment by chipweinberger** [comment]
try example app

**Comment by shuizhuyu1015** [comment]
The example app does not scan the device after it is powered off, but my own App can scan the device after it is powed off.
I don't know why, upset.😭

**Comment by chipweinberger** [comment]
fixed 1.17.6
