### ISSUE TITLE
[Help]: flutter_blue_plus doesn't support spp mode?

### ISSUE THREAD

**Issue by p709723778** [boskokg/flutter_blue_plus#623]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

flutter_blue_plus: ^1.17.5

### Flutter Version

3.13.7

### What OS?

Android, iOS

### OS Version

none

### Bluetooth Module

android, ios

### What is your problem?

flutter_blue_plus doesn't support spp mode?

### Logs

```shell
none
```

**Comment by chipweinberger** [comment]
spp is bluetooth classic
