### ISSUE TITLE
[Help]: Bluetooth device showing in scan after turning off

### ISSUE THREAD

**Issue by kbessemer** [boskokg/flutter_blue_plus#624]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.17.0

### Flutter Version

3.13.5

### What OS?

Android

### OS Version

12

### Bluetooth Module

STM 32

### What is your problem?

The problem is that FBP is reporting my STM32 in the scan results even after the STM32 has been powered off. Is there something I should be doing before each scan to clear a cache of some sort?

### Logs

```shell
Logs would not really help with this, I am just using the basic startScan
 function with a timeout and services filter. FBP is showing my STM32 
in the scan results in the console logs each scan.
```

**Comment by chipweinberger** [comment]
fixed 1.17.6
