### ISSUE TITLE
[Feature]: Please add print support

### ISSUE THREAD

**Issue by Sebuahhobi** [boskokg/flutter_blue_plus#626]
### FlutterBluePlus Version

1.18.3

### Flutter Version

3.13.2

### What OS?

Android

### OS Version

10, 11, 12, 13

### Bluetooth Module

Android

### What is your feature request?

I want 1 package for ble and print

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
that is out of scope of this project. 

use https://pub.dev/packages/bluetooth_print
