### ISSUE TITLE
iOS : Failed to Write characteristic even 4byte. 

### ISSUE THREAD

**Issue by ShubhamAryanBansal** [boskokg/flutter_blue_plus#64]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/69369116/169472856-c7cd91c5-3c1a-4112-bde8-e17a8e10534f.png">
This exception is coming every time when I am writing.. sometimes when I write 7bytes, exception comes but write happens, but sometimes doesn't. And even sometimes write doesn't happen with 4byte.

**Comment by designerslab** [comment]
Remove "withoutResponse : false".
