### ISSUE TITLE
[Help]: Getting different device ID on iOS (same ID given in Android)

### ISSUE THREAD

**Issue by kbessemer** [boskokg/flutter_blue_plus#645]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.17.6

### Flutter Version

3.13.7

### What OS?

iOS

### OS Version

17

### Bluetooth Module

STM32

### What is your problem?

I notice that the ID of the STM32 (peripheral) is different when fetching it on iOS versus Android, even for the same peripheral. Is there a way to get the ID/Mac address on iOS, the same way it is given on Android?

### Logs

```shell
void ListenToScanResults() {
    var subscription = FlutterBluePlus.scanResults.listen((results) {
      // do something with scan results
      for (ScanResult r in results) {
        print(r);
        print('${r.device.name} found! rssi: ${r.rssi}');
        if (!deviceListTechnical.contains(r.device.id.toString())) {
          deviceListTechnical.add(r.device.id.toString());
          BuildList(r);
        }
      }
    });
  }
```

**Comment by chipweinberger** [comment]
no.

ios does not allow it
