### ISSUE TITLE
[Help]: How can I distinguish app bluetooth auth & device system bluetooth auth

### ISSUE THREAD

**Issue by estherzhangyue** [boskokg/flutter_blue_plus#646]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

^1.20.1

### Flutter Version

3.13.2

### What OS?

iOS

### OS Version

16.7.1

### Bluetooth Module

not need

### What is your problem?

I wanna get phone bluetooth auth & app auth via `BluetoothAdapterState`, but when I turn off  both device bluetooth auth & app bluetooth auth, it only return `BluetoothAdapterState.unauthorized`, same with the situation I turn on device bluetooth auth, turn off app bluetooth auth. How can I get exact auth status from FlutterBluePlus?

### Logs

```shell
not important
```

**Comment by chipweinberger** [comment]
you cannot get them separate. 

if you have no app bluetooth auth, you will always get `BluetoothAdapterState.unauthorized`.
