### ISSUE TITLE
iOS build issue on Flutter 3.0.1

### ISSUE THREAD

**Issue by DivyanshuCaremonitor** [boskokg/flutter_blue_plus#65]
I am getting this issue on xcode.

error: open /Users/usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue_plus-1.1.3/ios/gen/Flutterblueplus.pbobjc.h: No such file or directory (in target 'flutter_blue_plus' from project 'Pods')

![image](https://user-images.githubusercontent.com/80573166/169565044-440e0bd4-df76-41a9-8b78-7c18260ab2b5.png)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
divyanshusrivastava@Divyanshus-MacBook-Pro cm-app-flutter % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
    • Flutter version 3.0.1 at /usr/local/Caskroom/flutter/2.8.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (17 hours ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/divyanshusrivastava/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Divyanshu’s iPhone (mobile) • 1fae8c5d9f5e1a9dcdff01d807e89096eb99d906 • ios            • iOS 15.1 19B74
    • macOS (desktop)             • macos                                    • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by adriangarro** [comment]
@DivyanshuCaremonitor just click this checkbox:

<img width="959" alt="Screen Shot 2022-05-25 at 23 14 07" src="https://user-images.githubusercontent.com/7646684/170420826-47530d12-91ff-43a3-8336-0c9e175fae20.png">

**Comment by DivyanshuCaremonitor** [comment]
Well unfortunately I downgraded my libraries. I will try this in upcoming week and let you know the result.
@adriangarro Thanks for the reply.

**Comment by arnsteinkjellevold** [comment]
@DivyanshuCaremonitor Could you please elaborate on why this is now necessary and how it is related to 3.0.1?
