### ISSUE TITLE
[Help]: How to Connect and Getting Data in a single function or single tap on the button

### ISSUE THREAD

**Issue by zubair999** [boskokg/flutter_blue_plus#655]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.20.8

### Flutter Version

3.10.6

### What OS?

Android

### OS Version

21

### Bluetooth Module

C2541

### What is your problem?

I am getting data, but there are so many steps from getting it. I am figuring out how to connect and get data only in one tap on the button. 

How can we do this? I am new to Blue Plus library and 

`

### Logs

```shell
No logs
```

**Comment by chipweinberger** [comment]
sorry you'll need to figure this out yourself. 

it is too much for me to explain. the README should be all you need.
