### ISSUE TITLE
[Help]: Is it compatible with Android 12? 

### ISSUE THREAD

**Issue by Charlie5DH** [boskokg/flutter_blue_plus#659]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.25.1

### Flutter Version

3.13.3

### What OS?

Android

### OS Version

Android 12

### Bluetooth Module

not important

### What is your problem?

Is working fine on a phone with Android 11 but is not scanning on Android 12

### Logs

```shell
""
```

**Comment by chipweinberger** [comment]
yup
