### ISSUE TITLE
[Bug]: /flutter_blue_plus-1.27.4/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:1787: error: illegal start of expression                     response.put("advertisements", new ArrayList<>(););

### ISSUE THREAD

**Issue by kmmalikads** [boskokg/flutter_blue_plus#664]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.27.4

### Flutter Version

3.16.0

### What OS?

Android

### OS Version

13

### Bluetooth Module

ble

### What is your problem?

 /flutter_blue_plus-1.27.4/android/src/main/java/com/lib/flutter_blue_plus/FlutterBluePlusPlugin.java:1787: error: illegal start of expression                     response.put("advertisements", new ArrayList<>(););

### Logs

```shell
.
```

**Comment by chipweinberger** [comment]
fixed 1.27.5
