### ISSUE TITLE
[Feature]: scan filter by "Manufacturer specific data"

### ISSUE THREAD

**Issue by dkozenkov** [boskokg/flutter_blue_plus#667]
### FlutterBluePlus Version

1.16.2

### What OS?

Android

### What is your feature request?

Please add the ability to filter Android devices by the content of "Manufacturer specific data", as is possible in the original Android API:
https://developer.android.com/reference/android/bluetooth/le/ScanFilter

**Comment by chipweinberger** [comment]
can you open a PR?

**Comment by chipweinberger** [comment]
great. glad it works.

> You are creating a very good library!

thats the idea! thanks.
