### ISSUE TITLE
[Bug]: Android - BluetoothCharacteristic.setNotifyValue(...) causes exception from version 1.28.5 onwards.

### ISSUE THREAD

**Issue by MartinXBcn** [boskokg/flutter_blue_plus#669]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.28.5

### Flutter Version

3.13.9

### What OS?

Android

### OS Version

Android 11

### Bluetooth Module

ESP32-S3

### What is your problem?

Changes between version 1.28.4 and 1.28.5 have side-effects on ```BluetoothCharacteristic.setNotifyValue(...)``` and causes exceptions from version 1.28.5 ff:
``
Exception has occurred.
PlatformException (PlatformException(setNotifyValue, service not found '5cb7', null, null))
``

What I found out in function ```BluetoothCharacteristic.setNotifyValue(...)``` are different values in the structure ```BmSetNotifyValueRequest request``` before calling ```FlutterBluePlus._invokeMethod('setNotifyValue', request.toMap())```

Version 1.28.4
```request.serviceUuid = Guid (00005cb7-0001-9923-4d7d-0000000080ba)```

Version 1.28.5/1.28.6
```request.serviceUuid = Guid (5cb7)```

### Logs

```shell
X
```

**Comment by chipweinberger** [comment]
> 00005cb7-0001-9923-4d7d-0000000080ba

is this a custom uuid? 

afaik, you can only use short ids for XXXXXX-0000-1000-8000-00805f9b34fb

so Guid (5cb7) is not valid.

**Comment by chipweinberger** [comment]
ah, now I get what you are saying. and yes I found the bug

**Comment by chipweinberger** [comment]
fixed 1.28.7

**Comment by MartinXBcn** [comment]
Works, thank you!
Although you are right, good point: uuid is created by me, I never thought about if it is "valid", but it worked for me up to now.
