### ISSUE TITLE
[Help]: How could I get the device name?

### ISSUE THREAD

**Issue by rocioaltairr** [boskokg/flutter_blue_plus#682]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.28.13

### Flutter Version

3.10.6

### What OS?

Android

### OS Version

Android

### Bluetooth Module

Not sure

### What is your problem?

Hello!

I would like to ask a question.
I saw the local name was deprecated.
How could I get the name of the device then, because through the rootId I could not connect to a specific device. Or there is any way to do it?

Thanks and Regard

### Logs

```shell
ScanResult BluetoothDevice{remoteId: 6D:35:67:9C:3B:C2, platformName: , services: null}
```

**Comment by chipweinberger** [comment]
you can use advName or platformName

not all devices advertise a name
