### ISSUE TITLE
[Feature]: return early if turnOn is rejected

### ISSUE THREAD

**Issue by ToxicGamer-exe** [boskokg/flutter_blue_plus#692]
### FlutterBluePlus Version

1.28.13

### Flutter Version

3.10.6

### What OS?

Android

### OS Version

Android 11

### Bluetooth Module

Not needed

### What is your feature request?

I'd like to get bool, that would indicate whether the user accepted or rejected the turnOn() dialog. Not only the func doesn't return anything, but if the user rejects, the awaited request is stuck unless the timeout goes out and then it throws exception (basically the only indication user didn't accept). Ending the timeout after the rejection would be appreciated ofc :D 

### Logs

```shell
No logs needed
```

**Comment by chipweinberger** [comment]
if you want this, feel free to open a PR.

**Comment by chipweinberger** [comment]
I've pushed a fix to master branch. try it out! untested.

**Comment by ToxicGamer-exe** [comment]
I'm gonna test it right out, thanks in advance! :)

**Comment by chipweinberger** [comment]
did it work?

**Comment by chipweinberger** [comment]
I tested it, it works.

**Comment by chipweinberger** [comment]
fixed in 1.29.5
