### ISSUE TITLE
[Help]: What are the keys used in ScanResult.AdvertisementData.ManufacturerData?

### ISSUE THREAD

**Issue by claudeJURA** [boskokg/flutter_blue_plus#694]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.20.17

### Flutter Version

3.13.8

### What OS?

Android

### OS Version

Android 13

### Bluetooth Module

unknown

### What is your problem?

When scanning for BLE devices we receive a map containing all advertisement data (ScanResult.AdvertisementData.ManufacturerData). 

I assumed the keys in this map correspond to the BLE standard keys (https://www.bluetooth.com/wp-content/uploads/Files/Specification/Assigned_Numbers.pdf?id=3). 

For instance Manufacturer Specific Data has the Flag 0xFF (dec:255) but I am receiving key 0xAB (dec:171) instead.

Is this an error or am I misinterpreting the meaning of the key? If so, what is the meaning of the key? Is the data provided in ScanResult.AdvertisementData.ManufacturerData already only the data marked with the 0xFF Flag? If so, can we somehow get access to the full list of advertisement data somehow?

### Logs

```shell
no logs
```

**Comment by chipweinberger** [comment]
manufacturer id
