### ISSUE TITLE
[Help]: connect to earbuds

### ISSUE THREAD

**Issue by mafzaldev** [boskokg/flutter_blue_plus#701]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.29.6

### Flutter Version

3.13.1

### What OS?

Android

### OS Version

Android 10

### Bluetooth Module

Redmi Buds Essential

### What is your problem?

Hi, I want to create an app to connect my phone to my earbuds, is it possible to implement functionality using this package?
Thanks!

### Logs

```shell
None
```

**Comment by chipweinberger** [comment]
nope
