### ISSUE TITLE
[Help]: Write more than 20 bytes

### ISSUE THREAD

**Issue by orsenigo** [boskokg/flutter_blue_plus#702]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

^1.28.10

### Flutter Version

Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git Framework • revision efbf63d9c6 (3 months ago) • 2023-08-15 21:05:06 -0500 Engine • revision 1ac611c64e Tools • Dart 3.1.0 • DevTools 2.25.0

### What OS?

Android, iOS

### OS Version

ios 15 andorid 10

### Bluetooth Module

smartphone

### What is your problem?

I  need to write some bytes on charateristic using the command write,but the library returns this error:

Unhandled Exception: PlatformException(writeCharacteristic, data longer than allowed. dataLen: 29 > max: 20 (withResponse, noLongWrite), null, null)

How i can write more than 20 bytes on ios and andorid ? 

Thks

### Logs

```shell
flutter: Write Profile Command : 05 02 01 36 22 FE 1E 1B 18 15 13 11 10 0F 0E 0D 0C 0B FE 58 58 58 58 00 00 00 00 00 00

<asynchronous suspension>
#2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:469:13)
<asynchronous suspension>
#3      BluetoothCharacteristic.write (package:flutter_blue_plus/src/bluetooth_characteristic.dart:203:7)
<asynchronous suspension>
#4      BluetoothManager.squareWriteProfile.<anonymous closure> (package:quadro_app/bt_manager.dart:972:13)
<asynchronous suspension>
```

**Comment by chipweinberger** [comment]
read the readme
