### ISSUE TITLE
Is there a way how we know that the ble  device is in DFU mode: 

### ISSUE THREAD

**Issue by Snofkin** [boskokg/flutter_blue_plus#704]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.29.5

### Flutter Version

3.10.5

### What OS?

Android

### OS Version

13

### Bluetooth Module

Nordic

### What is your problem?

My device is in DFU mode...I want to know how we identify that the device in DFU mode 

### Logs

```shell
.
```

**Comment by chipweinberger** [comment]
no. 

dfu mode is not part of the ble protocol.
