### ISSUE TITLE
How to stream Manufacturer Data ( bluetooth core 4.1)

### ISSUE THREAD

**Issue by tm-topnet** [boskokg/flutter_blue_plus#71]
Dear,
thank you in advance.

 I have a problem, I should analyze data from a ble that is sent in advertising. Looking at the nfc connect app the data is under the name of manufacturer data (bluetooth core 4.1). How can I do it with this amazing library?

**Comment by sophisticode** [comment]
You can retrieve it from ScanResult which you get when scanning for devices:

scanResult.advertisementData.manufacturerData

**Comment by tm-topnet** [comment]
Thanks, is there a way to analize that data as stream?

**Comment by sophisticode** [comment]
FlutterBluePlus.instance.scan() provides a stream with ScanResult objects, so you can extract manufacturer data directly from those objects.
