### ISSUE TITLE
BLE send data multiple times in while loop (await not working)

### ISSUE THREAD

**Issue by farhantandia** [boskokg/flutter_blue_plus#72]
Hi, I want to send a bunch of commands to my device but need only one command to send in one time using while loop, I have used await function in device.write(), however it will write multiple times to my device, which is not what I want.

for (int j = 0; j < cmdAll.length; j++) {
while (true) {

await Future.delayed(const Duration(milliseconds: 10));
await BLEUtils()
.writeByteData(cmdAll[j], targetCharacteristic);
}
}

I put while loop because my device sometimes does not give the response w.r.t my command in the first time due too sleep condition
 is there any missing function or implementation I have skipped?, thank you :)

**Comment by vishalideastoimpact** [comment]
**try delay this way**
 
await Future.delayed(const Duration(seconds: 1), () async { 
  await BLEUtils().writeByteData(cmdAll[j], targetCharacteristic);
 });
