### ISSUE TITLE
[Help]: No response value for long commands.

### ISSUE THREAD

**Issue by kimdindoo** [boskokg/flutter_blue_plus#721]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.30.3

### Flutter Version

3.13.7

### What OS?

Android

### OS Version

12

### Bluetooth Module

I don't know

### What is your problem?

![스크린샷 2023-12-08 오후 4 45 59](https://github.com/boskokg/flutter_blue_plus/assets/87438680/d1093131-8368-4f15-b055-3fd8c6289b3f)

I set the max mtu to 512, but the value displayed in the app is 241.

      List<int> dataToWrite =
          'set_cfg bpt cal_result C9840300077D0000780000004600000000000000A6B3003C00008542588C4F40D43930BBE345563D852F153EB5BC873E68EECC3E362A093FB51B273F6BE43E3F488F523F905A623F52BF6D3FF703753F5605793F9E117A3FBBD9793F201A793F5E0A783FC96F783F7CD3793FAC957B3FD76A7C3FC34A7C3FB7067A3FA8CF763FFBC1723FA1386D3F3F99663FC4735E3F37D8553FBE194D3F77E9433F21733A3F04DF303F1A01273F874B1D3F7E81143F80E20A3FF4DD003F0613EE3EF004DB3EFDC8C73EEE1FB23EC78C9B3E97A8863E3274603ED67E2D3EEEE5EE3DBB9A823D90DA813C31EA5EBC000000004D4D4D4\n'
              .codeUnits;

      final int maxChunkSize = 16;

      for (int i = 0; i < dataToWrite.length; i += maxChunkSize) {
        final chunk =
            dataToWrite.sublist(i, i + maxChunkSize > dataToWrite.length ? dataToWrite.length : i + maxChunkSize);

      print('chunk: $chunk');
      await c.write(chunk, withoutResponse: c.properties.writeWithoutResponse);
      }

Since the Bluetooth device can read 16 bytes at a time, I implemented it like the code above.
However, no response value comes.

### Logs

```shell
{error_string: GATT_SUCCESS, service_uuid: 6e400000-b5a3-f393-e0a9-e50e24dcca9e, success: 1, remote_id: 00:18:80:4F:07:26, error_code: 0, characteristic_uuid: 6e400002-b5a3-f393-e0a9-e50e24dcca9e, value: 0000000000000000000000000000000000000000}
```

**Comment by chipweinberger** [comment]
sorry i don't understand the issue. 

if there is no response you should get a timeout

**Comment by kimdindoo** [comment]
thank you for the reply. My problem is that when I try to receive data larger than the mtu size, there is no response. Is there something I need to implement separately?

**Comment by chipweinberger** [comment]
if you want to receive data larger than mtu size you must use subscriptions and onValueReceived to get your data in chunks.

you cannot use READ.

**Comment by chipweinberger** [comment]
@daveols just call `chr.read()` multiple times

**Comment by chipweinberger** [comment]
FBP cannot fix that. sorry.

**Comment by chipweinberger** [comment]
yup
