### ISSUE TITLE
[Help]: How to send data to a chip "jdy-10m" ble

### ISSUE THREAD

**Issue by JoshuaLee0321** [boskokg/flutter_blue_plus#728]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.29.6

### Flutter Version

3.16.0-13.0.pre.17

### What OS?

Android, iOS

### OS Version

Android

### Bluetooth Module

jdy-10

### What is your problem?

I am not familiar with bluetooth coding, the only thing i know is to write to a characteristic, but that didn't work on my chip
I am thinking bluetooth device as a socket that connects two endpoints thus to send data and recieve data, but i cannot find any code to help me send the corresponding data

### Logs

```shell
No logs
```

**Comment by chipweinberger** [comment]
You need to read some BLE tutorial guides. Cannot help you here.
