### ISSUE TITLE
[Help]: iOS: device name does not update

### ISSUE THREAD

**Issue by guduqiucai** [boskokg/flutter_blue_plus#742]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.31.3

### Flutter Version

3.10.2

### What OS?

iOS

### OS Version

16.4.1

### Bluetooth Module

unknown

### What is your problem?

[Bug]: After modifying the name of a Bluetooth device, the iOS device still scanAfter modifying the name of a Bluetooth device, the iOS device still scans the old Bluetooth name, while the Android device scans the new name. The nrf Connect software also scans the new Bluetooth name.

### Logs

```shell
no
```

**Comment by chipweinberger** [comment]
use advName instead of platformName

**Comment by guduqiucai** [comment]
for (ScanResult r in results) {
          if (Platform.isAndroid) {
            if (r.device.localName != '' &&
                !blueName.contains(r.device.localName)) {
              blueName.add(r.device.localName);
              if (mounted) {
                setState(() {
                  this._blueDevice.add(r);
                });
              }
            }
          } else {
            if (r.device.advName != '' &&
                !blueName.contains(r.advertisementData.localName)) {
              blueName.add(r.advertisementData.advName);
              if (mounted) {
                setState(() {
                  this._blueDevice.add(r);
                });
              }
            }
          }
        }

The getter 'advName' isn't defined for the type 'BluetoothDevice'.

**Comment by chipweinberger** [comment]
its defined here

https://github.com/boskokg/flutter_blue_plus/blob/fb436621b0951b4940d97853e3248f9d6a95b535/lib/src/bluetooth_device.dart#L35

**Comment by guduqiucai** [comment]
Will this be uniformly modified in subsequent versions, or can only I modify it locally?

**Comment by guduqiucai** [comment]
> Will this be uniformly modified in subsequent versions, or can only I modify it locally?

Or how should I use it?

**Comment by chipweinberger** [comment]
```
/// Advertised Named
  ///  - the is the name advertised by the device during scanning
  ///  - it is only available after you scan with FlutterBluePlus
  ///  - it is cleared when the app restarts.
  ///  - not all devices advertise a name
```

**Comment by GhazanfarU6** [comment]
i have the same issue some device names are being displayed but some are not advertising their name, so is there any other solution to get their names because in my context its necessary to show device name that are being scanned.

**Comment by chipweinberger** [comment]
if your device does not share its name, there is nothing we can do.
