### ISSUE TITLE
[Help]:  How To scan and connect Non LE devices?

### ISSUE THREAD

**Issue by xyzbilal** [boskokg/flutter_blue_plus#743]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.30.3

### Flutter Version

3.13.5

### What OS?

Android

### OS Version

Android  12

### Bluetooth Module

dont know

### What is your problem?

We have a project that we need to use some legacy devices. As I see there is no feature that this package can scan and connect legacy devices. 
İs there any idea how to resolve this issue on this package?

### Logs

```shell
Do I need to provide logs?
```

**Comment by chipweinberger** [comment]
you need to make your own bluetooth classic library 

read apple docs and android docs
