### ISSUE TITLE
[Help]: Is it safe to use this plugin simultaneously along with flutter_reactive_ble

### ISSUE THREAD

**Issue by samnbd** [boskokg/flutter_blue_plus#748]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.31.4

### Flutter Version

3.7.11

### What OS?

Android, iOS

### OS Version

iOS 17.2.1, Android 12

### Bluetooth Module

Nordic NRF

### What is your problem?

We tried flutter_blue_plus and loved how it works, and we have an app that already uses flutter_reactive_ble plugin to pair and communicate with one of our external devices. But now we want to use flutter_blue_plus with a new type of device but in the same app, to experiment with it's stability before deciding to switch to flutter_blue_plus and use it with our old type of devices. The issue is that we have to use flutter_blue_plus along with flutter_reactive_ble in the same app since the same app will be used for both connecting and communicating with both old and new type of devices. 
We only gonna use flutter_blue_plus for scanning and pairing our new type of devices and use flutter_reactive_ble in case of a user that wants to connect the old type of device. 
So will this be okey ? 

### Logs

```shell
No logs to include
```

**Comment by chipweinberger** [comment]
no. very unlikely.
