### ISSUE TITLE
[Help]: getting advertisement interval

### ISSUE THREAD

**Issue by SahilShirsat17** [boskokg/flutter_blue_plus#757]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.31.8

### Flutter Version

3.16.5

### What OS?

Android

### OS Version

android 13

### Bluetooth Module

Xioami 11 i   - bluetooth 5.2

### What is your problem?

How can we display advertisement interval  in scan result  

### Logs

```shell
No logs
```

**Comment by chipweinberger** [comment]
you cant. there are all the possible keys

https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/advertisement_data_retrieval_keys

**Comment by SahilShirsat17** [comment]
Can't we use the package and display the advertising interval in the scan result rather going for native android

**Comment by chipweinberger** [comment]
not currently possible. you will need to open a PR.
