### ISSUE TITLE
[Help]:  This plugin implements the IRK (Identity Resolving Key) code?

### ISSUE THREAD

**Issue by rahul110897** [boskokg/flutter_blue_plus#777]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.20.8

### Flutter Version

3.16.9

### What OS?

Android, iOS

### OS Version

16

### Bluetooth Module

PSoC 6 Board

### What is your problem?

We need some permanent keys after pairing and bonding the device

### Logs

```shell
NA
```

**Comment by chipweinberger** [comment]
no

**Comment by rahul110897** [comment]
Thanks for the update
