### ISSUE TITLE
[Feature]: on Android it sends two pairing requests on connect() !

### ISSUE THREAD

**Issue by mohamedsl23** [boskokg/flutter_blue_plus#779]
### FlutterBluePlus Version

1.31.12

### Flutter Version

3

### What OS?

Android

### OS Version

all

### Bluetooth Module

reg

### What is your feature request?

Hey, 
I don't know if it's an issue, but in android when I do device.connect() I get two pairing requests although in IOS just one, is there away to receive only one pairing request in android ? 
Thanks

### Logs

```shell
12
```

**Comment by chipweinberger** [comment]
https://github.com/boskokg/flutter_blue_plus?tab=readme-ov-file#android-pairing-popup-appears-twice

android pairing popup appears twice
