### ISSUE TITLE
[Help]: setNotityValue(true) error

### ISSUE THREAD

**Issue by roger66** [boskokg/flutter_blue_plus#781]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.31.12

### Flutter Version

3.16.9

### What OS?

Android

### OS Version

10

### Bluetooth Module

unknown

### What is your problem?

setNotifyValue return GATT_WRITE_NOT_PERMITTED，but FBP1.1.3 is success

### Logs

```shell
D/[FBP-Android]( 6078): [FBP] onMethodCall: setNotifyValue
D/BluetoothGatt( 6078): setCharacteristicNotification() - uuid: b044efa0-71ed-11ec-a494-020017000b7b enable: true
E/[FBP-Android]( 6078): [FBP] onDescriptorWrite:
E/[FBP-Android]( 6078): [FBP]   chr: b044efa0-71ed-11ec-a494-020017000b7b
E/[FBP-Android]( 6078): [FBP]   desc: 2902
E/[FBP-Android]( 6078): [FBP]   status: GATT_WRITE_NOT_PERMITTED (3)
E/flutter ( 6078): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FlutterBluePlusException | setNotifyValue | android-code: 3 | GATT_WRITE_NOT_PERMITTED
E/flutter ( 6078): #0      BluetoothCharacteristic.setNotifyValue (package:flutter_blue_plus/src/bluetooth_characteristic.dart:280:11)
```

**Comment by roger66** [comment]
peripheral's descriptor only have PERMISSION_READ，use FBP1.13 no problem

**Comment by chipweinberger** [comment]
If you want the same behavior as 1.1.3, you can just ignore the error.

FBP 1.1.3 did not check for errors. It had no error handling support.

**Comment by roger66** [comment]
After ignoring，Does onValueReceived work？

**Comment by chipweinberger** [comment]
depends on your device!

**Comment by roger66** [comment]
Is it the same if I don't call setNotifyValue?

**Comment by chipweinberger** [comment]
not the same. it still sends the request to your device.

**Comment by roger66** [comment]
If I ignore the setNofityValue error

**Comment by roger66** [comment]
E/flutter (31546): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FlutterBluePlusException | writeCharacteristic | android-code: 133 | UNKNOWN_GATT_ERROR (133)
E/flutter (31546): #0      BluetoothCharacteristic.write (package:flutter_blue_plus/src/bluetooth_characteristic.dart:215:9)
E/flutter (31546): <asynchronous suspension>
E/flutter (31546): #1      BleUtils._subpackageSend (package:test_ble/ble_utils.dart:204:5)
E/flutter (31546): <asynchronous suspension>
E/flutter (31546):

**Comment by roger66** [comment]
writeCharacteristic not work

**Comment by roger66** [comment]
Before I call setNotifyValue，writeCharacteristic can work

**Comment by chipweinberger** [comment]
you should be looking at the logs on your device. these are GATT errors. i.e. device errors.
