### ISSUE TITLE
How to solve BluetoothDevice.state problem?

### ISSUE THREAD

**Issue by chinzorigts** [boskokg/flutter_blue_plus#79]
Hi, guys 

I am using that plugin. I have a one problem. If the BLE device connects and disconnects, then connects again. When device state created duplicate. Example:
if device connects and disconnects. Then connects again. When BluetoothDeviceState.connected running 2 times.
How to solve that problem ?

**Comment by arnsteinkjellevold** [comment]
Are you receiving BluetoothDeviceState.connected twice without getting any other state in between?

If not, and the device is disconnecting and reconnecting, and the BluetoothDeviceState is reporting this just as it happens then everything is working as designed.

If you have code the triggers on BluetoothDeviceState.connected then I think you will have to handle multiple states on your side perhaps by having a local state that knows the "connected" code has already run.
