### ISSUE TITLE
[Help]: Is descriptorUuid equivalent of a Descriptor Type?

### ISSUE THREAD

**Issue by Ben1980** [boskokg/flutter_blue_plus#796]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.31.14

### Flutter Version

3.16.9

### What OS?

iOS

### OS Version

iOS 17+

### Bluetooth Module

Suunto EON Core

### What is your problem?

I need the BluetoothDescriptor Type according to [QBluetoothUuid::DescriptorType](https://doc.qt.io/qt-6/qbluetoothuuid.html#DescriptorType-enum). In particular, I need to know if the descriptor is of type `ClientCharacteristicConfiguration`. I found that my device descriptor has the `descriptorUuid` of 2902 which would fit what I need. Am I right that the `descriptorUuid` is equivalent to the type or is it just a coincidence that it has the right value?
If it's the right value, why is it of type Guid instead of a simple hex or int?

### Logs

```shell
flutter: Preferred service found: 98ae7120-e62e-11e3-badd-0002a5d5c51b
flutter: Descriptor remoteId: E74CA49A-C525-CA79-99D3-6357C0791663
flutter: Descriptor serviceUuid: 98ae7120-e62e-11e3-badd-0002a5d5c51b
flutter: Descriptor characteristicUuid: d0fd6b80-e62e-11e3-a2e9-0002a5d5c51b
flutter: Descriptor descriptorUuid: 2902
```

**Comment by chipweinberger** [comment]
yes you're right. 

it's of type Guid because that's what makes sense.
