### ISSUE TITLE
[Help]: Able to auto-connect (bonding) BLE device when app launched again?

### ISSUE THREAD

**Issue by mtiendat** [boskokg/flutter_blue_plus#797]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.31.7

### Flutter Version

 3.16.7

### What OS?

Android

### OS Version

android 13

### Bluetooth Module

nordic nRF5340

### What is your problem?

I see method device.connect(autoconnect: true).  is it auto connect to device when app launched next time?

### Logs

```shell
I see method device.connect(autoconnect: true).  is it auto connect to device when app launched next time?
```

**Comment by chipweinberger** [comment]
no.

it resets after app launch

**Comment by mtiendat** [comment]
> no.
> 
> it resets after app launch
> 
> also you should update

ok, I was mistake with the autoconnect.
So. In my case,  I have to check 
` final bondedDevices = await FlutterBluePlus.bondedDevices;`
whenever re-launched app. if bondedDevices has my BLE device, I don't need to scan again.

**Comment by chipweinberger** [comment]
ya. only works on android though

**Comment by mtiendat** [comment]
@chipweinberger  if I don't call createBond() after device.connect() I always got bonded state BluetoothBondState.none. Do you know this issue, why it doesn't automatically bond ?

**Comment by chipweinberger** [comment]
could be a device issue. not sure.

why do you need to bond?

**Comment by mtiendat** [comment]
@chipweinberger because I don't want to re-scan whenever I launch app, only scan first time launch app and then I want to use bonding when connecting to BLE

**Comment by chipweinberger** [comment]
you could try saving the device id in a file

**Comment by mtiendat** [comment]
@chipweinberger thank you for your help! save  `RemoteId` to local and retrieve it then connect might be better than use `FlutterBluePlus.bondedDevices`
