### ISSUE TITLE
[Help]: How to connect the device that specifies the MAC address? For example, scan a QR code to get the MAC address of the device,

### ISSUE THREAD

**Issue by shijianoo** [boskokg/flutter_blue_plus#804]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

flutter_blue_plus: ^1.31.15

### Flutter Version

3.16.9

### What OS?

Android

### OS Version

33

### Bluetooth Module

xiaomi 14

### What is your problem?

How to connect the device that specifies the MAC address? For example, scan a QR code to get the MAC address of the device,

### Logs

```shell
How to connect the device that specifies the MAC address? For example, scan a QR code to get the MAC address of the device,
```

**Comment by chipweinberger** [comment]
you need to scan, look for the mac in the results, then connect

i don't think it will work on ios
