### ISSUE TITLE
[Help]: Is there a way to use the scan as a Future that returns a device list?

### ISSUE THREAD

**Issue by CarlosEspinozaMaruri** [boskokg/flutter_blue_plus#811]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.31.16

### Flutter Version

3.10.0

### What OS?

Android, iOS

### OS Version

Any

### Bluetooth Module

Mobile integrated

### What is your problem?

I Want to know if exists a way to get scan results from a Future.

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
sure

1. call startScan w/ timeout
2. await isScanning.where((v) => v == false)
3. use lastScanResults
