### ISSUE TITLE
[Help]: How can I understand if the device is currently uploading data?

### ISSUE THREAD

**Issue by VladyslavForm** [boskokg/flutter_blue_plus#819]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.31.4

### Flutter Version

3.16

### What OS?

iOS

### OS Version

iOS 17

### Bluetooth Module

-

### What is your problem?

How can I understand if the device is currently uploading data? The Android version returns 201 error, while iOS returns nothing. It would be convenient to simply check if another writing is already happening at the time of calling the write function. In this case, I could control this situation myself. Thanks in advance for any tips.

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
youll need to write your own code to handle this, for fork FBP.

I suggest a wrapper around the "write" function.
