### ISSUE TITLE
[Question]: Documentation might be wrong for BluetoothCharacteristic.write()

### ISSUE THREAD

**Issue by danger-ahead** [boskokg/flutter_blue_plus#823]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.31.17

### Flutter Version

3.16.9

### What OS?

All

### OS Version

Latest

### Bluetooth Module

NA

### What is your problem?

https://github.com/boskokg/flutter_blue_plus/blob/d2bc7b572512aa7a3dc374a7cc0de0461348ff15/lib/src/bluetooth_characteristic.dart#L154

There's no parameter called `withResponse` in the original function definition.
Is this line needed?

### Logs

```shell
NA
```

**Comment by chipweinberger** [comment]
thanks. updated.
