### ISSUE TITLE
[Feature]: Convert To Federated Plugin

### ISSUE THREAD

**Issue by FXschwartz** [boskokg/flutter_blue_plus#824]
### What is your feature request?

Converting flutter_blue_plus to a federated plugin would greatly help implementing support for additional platforms. 

@chipweinberger I know you've voiced concerns about the additional complexity of this but I think even if we decided to not endorse additional platforms, converting this to a federated plugin would help other developers create non endorsed platform integration.

Adding support for additional platforms through a fork in the current implementation while would still be beneficial would be extremely risky to use in production applications as it could break at any moment.

Parts of this have been discussed in #6

**Comment by chipweinberger** [comment]
Thanks for filing. I don't plan to switch to federated.

People should implement other platforms using a platform channel, as discussed in #6.

Windows example:
```
flutter::MethodChannel<EncodableValue>>(
          registrar->messenger(), "flutter_blue_plus/methods",
          &flutter::StandardMethodCodec::GetInstance());
```

But more importantly, I'm not going to implement Windows or Linux, and it appears no one else wants to either.
