### ISSUE TITLE
[Feature]: Is there a method for real-time scanning of Bluetooth results？

### ISSUE THREAD

**Issue by Ervin2018** [boskokg/flutter_blue_plus#826]
### FlutterBluePlus Version

3.19.4

### Flutter Version

3.19.4

### What OS?

Android, iOS

### OS Version

17.2.1

### Bluetooth Module

-

### What is your feature request?

Continuously scanning Bluetooth until the application closes

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
ya. use `oneByOne` option & `continuousUpdates`
