### ISSUE TITLE
[Help]: Listening on ScanResults does not trigger onError

### ISSUE THREAD

**Issue by ShawnHuang1982** [boskokg/flutter_blue_plus#831]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.32.0

### Flutter Version

3.19.0

### What OS?

Android

### OS Version

6.0.1

### Bluetooth Module

esp32

### What is your problem?

I use the following code to listen for scan events:
```
    final subscription = FlutterBluePlus.onScanResults.listen(
      (results) {
        print("OnScanResponse : $results");
        if (results.isNotEmpty) {
          ScanResult r = results.last;
          print(
              '${r.device.remoteId}: "${r.advertisementData.advName}" found!');
        }
      },
    ).onError(
      (error, stackTrace) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('$error')),
        );
        print('scan error: $error');
      },
    );
```

When monitoring scanning events, my application typically functions smoothly during the scanning process while running. However, occasionally, I encounter the following error message in the debug console:
```
'[FBP] [[ OnScanResponse ]] result: {error_string: SCAN_FAILED_APPLICATION_REGISTRATION_FAILED, advertisements: [], error_code: 2, success: 0}',
```
Despite encountering this error, the execution path does not enter the onError block, which is unexpected.

After investigating the source code at the following link:
https://github.com/boskokg/flutter_blue_plus/blob/69ccb70711180908d5474ab28be1e1019afea134/lib/src/bluetooth_msgs.dart#L183C5-L183C68
I made the following adjustment:
Original:
```
bool success = json['success'] == null || json['success'] == 0;
```
Modified:
```
bool success = json['success'] == null;
```

This change revealed that the application's execution could enter the onError block when this error occurs.

I'm curious whether the device itself has a problem or if there's another underlying issue.Thank you for your assistance.

### Logs

```shell
Launching lib/main.dart on SM G610Y in debug mode...
I/flutter (23881): [FBP] [[ OnScanResponse ]] result: {advertisements: [{remote_id: 7C:D9 *hidden*
I/flutter (23881): OnScanResponse : [ScanResult{device: BluetoothDevice{remoteId: 5B:2B *hidden*
I/flutter (23881): 7C:D9*hidden* "" found!
I/flutter (23881): stop scanning
I/flutter (23881): [FBP] <stopScan> args: null
I/flutter (23881): isScanning state: false
I/flutter (23881): [FBP] [[ OnScanResponse ]] result: {advertisements: [{remote_id: 4A:76 *hidden*
I/flutter (23881): [FBP] [[ OnScanResponse ]] result: {advertisements: [{remote_id: 59:1E *hidden*
I/flutter (23881): [FBP] [[ OnScanResponse ]] result: {advertisements: [{remote_id: 71:4D *hidden*
I/flutter (23881): [FBP] <stopScan> result: true
I/flutter (23881): start scanning
I/flutter (23881): [FBP] <startScan> args: {with_services: [], with_remote_ids: [], with_names: [], with_keywords: [], with_msd: [], with_service_data: [], continuous_updates: false, continuous_divisor: 1, android_scan_mode: 2, android_uses_fine_location: false}
I/flutter (23881): isScanning state: true
I/flutter (23881): [FBP] <startScan> result: true
I/flutter (23881): OnScanResponse : []
I/flutter (23881): [FBP] [[ OnScanResponse ]] result: {error_string: SCAN_FAILED_APPLICATION_REGISTRATION_FAILED, advertisements: [], error_code: 2, success: 0}
I/flutter (23881): OnScanResponse : []

---
*hidden*: hidden information
```

**Comment by chipweinberger** [comment]
fixed https://github.com/boskokg/flutter_blue_plus/commit/d3aa378e92de81652322c9d0d4ed16120cd0bcc0

will be in 1.32.1

**Comment by lwx123** [comment]
`scanResultsSubscription = FlutterBluePlus.scanResults.listen((results) {
      results = results.where((r) => r.device.platformName.isNotEmpty).toList();
      _scanResults = results;
      if (mounted) {
        setState(() {});
      }
    }, onError: (e) {
      Snackbar.show(ABC.b, prettyException("Scan Error:", e), success: false);
    });`

**Comment by lwx123** [comment]
[ OnScanResponse ] result: {error_string: SCAN_FAILED_APPLICATION_REGISTRATION_FAILED, advertisements: [], success: 0, error_code: 2}
BluetoothLeScanner(): onScannerRegistered() - status=0 scannerId=7 mScannerId=-1

can you help me?

**Comment by chipweinberger** [comment]
please open a new issue specifically for "SCAN_FAILED_APPLICATION_REGISTRATION_FAILED"

**Comment by lwx123** [comment]
ok
