### ISSUE TITLE
[Help]: I don't know how to get data from bluetooth device 

### ISSUE THREAD

**Issue by GereyTatarkhanov** [boskokg/flutter_blue_plus#838]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

latest

### Flutter Version

latest

### What OS?

Android

### OS Version

14

### Bluetooth Module

i dont know

### What is your problem?

I do not know how to get data from a bluetooth device. I opened this test project and connected to my bluetooth device. I see in the logs that data is coming in with a certain frequency. But I can't figure out where to get this data in the code. I used lastValueStream.listen((value){ print(value) for this });
But there is always the same result, although in default locks (those that are set like this: FlutterBluePlus.setLogLevel(LogLevel.verbose, color: true);) the data comes as it should. Does anyone know what the problem might be?

### Logs

```shell
///////////
```

**Comment by chipweinberger** [comment]
logs needed.
