### ISSUE TITLE
[Feature]: Set/update device name

### ISSUE THREAD

**Issue by rgootjes** [boskokg/flutter_blue_plus#839]
### FlutterBluePlus Version

1.31.15

### Flutter Version

3.19.0

### What OS?

Android

### OS Version

Android 14

### Bluetooth Module

Unknown module

### What is your feature request?

Hey just wondering if it would be possible to add a feature where the device name can be updated. Would also be ideal if the advertising data was updated as well to reflect the name change

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
not possible.
