### ISSUE TITLE
[Help]: Huawei phones cannot search for Bluetooth devices

### ISSUE THREAD

**Issue by 362228416** [boskokg/flutter_blue_plus#851]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.31

### Flutter Version

3.10.7

### What OS?

Android

### OS Version

HarmonyOS 3.0

### Bluetooth Module

any

### What is your problem?

Huawei phones cannot search for Bluetooth devices. The system is HarmonyOS, and the WeChat mini program can search for Bluetooth. What is the solution for the same phone with the same system? The latest example code I use cannot scan any Bluetooth devices either

### Logs

```shell
no error
```

**Comment by chipweinberger** [comment]
closing. need more info.
