### ISSUE TITLE
[Help]: 订阅蓝牙连接状态结果返回太久

### ISSUE THREAD

**Issue by devYoungyang** [boskokg/flutter_blue_plus#857]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.31.15

### Flutter Version

3.3.0

### What OS?

All

### OS Version

17.0

### Bluetooth Module

EFR32MG21

### What is your problem?

蓝牙连接外设成功后记下remoteId，下次打开app后通过 BluetoothDevice device =  BluetoothDevice(remoteId: DeviceIdentifier(remoteId)); device.connect连接状态要等到设定的timeout才能返回结果，

### Logs

```shell
null
```

**Comment by chipweinberger** [comment]
sorry i dont understand chinese!
