### ISSUE TITLE
How to clear the scan results before start the scan.

### ISSUE THREAD

**Issue by sureace** [boskokg/flutter_blue_plus#86]
Hi, 
    Thanks for providing support. We are getting old results when start the bluetooth scan. Is there any way to clear the old scan results before we start the scan.  Something like below
void clearScanResults(){
    _scanResults.value.clear();
  }

Thank you
Sureace

**Comment by bagintz** [comment]
@boskokg you closed this but I don't see any mention of the method or suggestion?

**Comment by shubhamsinghmutualmobile** [comment]
I'm looking an answer for this same question. Can anyone help? (@chipweinberger maybe?)

**Comment by chipweinberger** [comment]
just use `onScanResults`

**Comment by shubhamsinghmutualmobile** [comment]
> just use `onScanResults`

Awesome! This worked perfectly ✅ Thank you 🙌
