### ISSUE TITLE
[Help]: Parsing characteristic data

### ISSUE THREAD

**Issue by NobodyForNothing** [boskokg/flutter_blue_plus#860]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.4

### Flutter Version

 3.22.0-0.2.pr

### What OS?

Android

### OS Version

Android 10 / 14

### What is your problem?

What is the recommended way of parsing the List<int> values received from subscriptions? 
 - Are there any known libraries/generators from this or do I have parse them myself?
 - If I need to parse them myself, can you confirm whether [this](https://www.bluetooth.com/de/specifications/blp-1-1-1/) is the correct specification?

**Comment by chipweinberger** [comment]
parse yourself. 

the spec depends on the device / service
