### ISSUE TITLE
[Help]: How to use write indicate 

### ISSUE THREAD

**Issue by GMarki** [boskokg/flutter_blue_plus#862]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.26.4

### Flutter Version

3.16.8

### What OS?

Android

### OS Version

Android 12

### Bluetooth Module

Device OnePlus 9

### What is your problem?

Hello, I need to get indicate results after calling write from characteristic. How can I solve it?   
I'm calling: [write method](https://pub.dev/documentation/flutter_blue_plus/latest/flutter_blue_plus/BluetoothCharacteristic/write.html) to set my value but there is no way to get a response from this method.   
With regards

### Logs

```shell
no logs
```

**Comment by chipweinberger** [comment]
use `characterstic.setNotifyValue`. see README for "subscriptions.
