### ISSUE TITLE
iOS every 30 seconds i get (didDisconnectPeripheral)

### ISSUE THREAD

**Issue by simondukaric** [boskokg/flutter_blue_plus#87]
Only on iOS devices every 30 seconds i get (didDisconnectPeripheral)... Android works fine. Any solution to this or whats causing this?

**Comment by Ladegeraet** [comment]
I have the same problem. Although not every 30 seconds and not on every iPhone, but the error occurs very often. 
@simondukaric have you already found a solution?

**Comment by simondukaric** [comment]
In a "hacky" way yes. I have stored device in state and I listen to device connection state stream, and when state is "disconnected" i immediately connect again to the saved device. But this wouldnt work if you actually turn off BLE device or go outside of the proximity of the device...

**Comment by boskokg** [comment]
@simondukaric @Ladegeraet I cannot reproduce this issue.
Please make investigation and give us the merge request to fix it.
