### ISSUE TITLE
[Feature]: iBeacons are not supported on iOS. Apple requires you to use CoreLocation.

### ISSUE THREAD

**Issue by securexperts** [boskokg/flutter_blue_plus#878]
### FlutterBluePlus Version

1.32.6

### Flutter Version

3.19.6

### What OS?

iOS

### OS Version

iOS 17.4.1

### Bluetooth Module

Minew Tech Software=nRF52-SDK13.0 / Hardware=MS71SF6_V1.0.0

### What is your feature request?

Hello, 

Today I use the flutter_beacon: ^0.5.1 but would like to use your plugin.
Do you plan to integrate CoreLocation to be able to recognize also iBeacons on iOS. On Android it works like a charm.
What would be the estimate time to make it available?.
Do you need Hardware piece for the integration?

Many Thanks
Roman from SecureXperts 

### Logs

```shell
New Feature -> no Logs
```

**Comment by chipweinberger** [comment]
This is not a feature I will implement. 

CoreLocation support should be implemented in a different flutter package.
