### ISSUE TITLE
[Reature]:Bluetooth search problem[Help]: 

### ISSUE THREAD

**Issue by wkk199** [boskokg/flutter_blue_plus#883]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.7

### Flutter Version

3.19.6

### What OS?

Android

### OS Version

Android 13

### Bluetooth Module

esp32

### What is your problem?

My mundane calls to startScan and stopScan ended up with an empty onScanResults callback

### Logs

```shell
_scanResultsSubscription = FlutterBluePlus.onScanResults.listen(
        (results) {
          if (results.isNotEmpty) {
            for (ScanResult result in results) {
              print("result=====>>${result.device.platformName} ");
            }
          } else {
            print("result=====>>----------$results");
          }
        },
1. Trivial toggle results.isNotEmpty will work
```

**Comment by wkk199** [comment]
Second, after about 4 minutes of searching, onScanResults won't return any results

**Comment by chipweinberger** [comment]
check permissions

handle onError for scanResults

**Comment by chipweinberger** [comment]
and give your logs

**Comment by wkk199** [comment]
![Uploading image.png…]()
That is, when I click stopScan() and startScan() repeatedly, the isScanning state is true, but the searched device is empty @chipweinberger

**Comment by wkk199** [comment]
![Uploading 1715831418341.jpg…]()
That is, when I click stopScan() and startScan() repeatedly, the isScanning state is true, but the searched device is empty @chipweinberger

**Comment by wkk199** [comment]
![1715831418341](https://github.com/boskokg/flutter_blue_plus/assets/76580696/6f70f226-4da7-41b7-a73b-a92c4e637c3d)

**Comment by wkk199** [comment]
https://github.com/boskokg/flutter_blue_plus/assets/76580696/8bac09c4-1fd0-41e4-8a75-9c0333dc1f0e

1.These are my steps @chipweinberger

**Comment by chipweinberger** [comment]
handle onError

you can only scan 6 times per minute

**Comment by wkk199** [comment]
> 处理错误
> 
> 在 Android 上每分钟只能扫描 6 次

I'm not sure what you mean, is startScan() can only be called 6 times per minute? If more than 6 times, how can I continue scanning

**Comment by wkk199** [comment]
> 处理错误
> 
> 在 Android 上每分钟只能扫描 6 次

I tried to make sure that the scan will not continue if it is larger than 6 times, but onError also did not execute, I change if I handle this problem, I can continue scanning

**Comment by wkk199** [comment]
@chipweinberger 

> 无法取消限制

ok，thank you
