### ISSUE TITLE
[Help]: Can't get sendData on iOS

### ISSUE THREAD

**Issue by kirasoga** [boskokg/flutter_blue_plus#887]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.7

### Flutter Version

3.19.1

### What OS?

iOS

### OS Version

17.5.1

### Bluetooth Module

general

### What is your problem?

I created GattServiceProvider with dotnet.   
On Android, the value in ServiceData can be retrieved normally, but on Android, it is not possible to retrieve it.

dotnet is https://qiita.com/gpsnmeajp/items/481fd731851e0e538263

Is this an iOS only specification?

### Logs

```shell
sorry. notting log
```

**Comment by chipweinberger** [comment]
?

**Comment by chipweinberger** [comment]
need logs

**Comment by chipweinberger** [comment]
closing. no response.
