### ISSUE TITLE
Android state always connected

### ISSUE THREAD

**Issue by giroskii** [boskokg/flutter_blue_plus#89]
![image](https://user-images.githubusercontent.com/34018919/177497994-36f56e3c-38bb-46a4-a105-7ec6f0f13f1b.png)

android device state always return connected. is this bug? my test phone android12, iPhone was no problem.

call device.disconnect() return stream disconnected but, change connected

**Comment by boskokg** [comment]
@giroskii please debug the issue and try to provide the merge request. Thanks in advance.
