### ISSUE TITLE
[Help]: stopScan: already stopped

### ISSUE THREAD

**Issue by vikyfandd** [boskokg/flutter_blue_plus#896]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.32.7

### Flutter Version

3.10.5

### What OS?

iOS

### OS Version

15.8.2

### Bluetooth Module

Accu Check Instant

### What is your problem?

Pin input not showing when i try to connect for IOS, any solution to trigger it ? android working fine with create bond and how to do it for IOS ? thanks 

this is my code for connect 
{
device!.connect(timeout: const Duration(seconds: 2));
}

### Logs

```shell
flutter: [FBP] stopScan: already stopped
[FBP-iOS] handleMethodCall: startScan
[FBP-iOS] handleMethodCall: stopScan
[FBP-iOS] handleMethodCall: connect
[FBP-iOS] handleMethodCall: getAdapterState
[FBP-iOS] didConnectPeripheral
[FBP-iOS] handleMethodCall: connect
[FBP-iOS] already connected
flutter: [FBP] stopScan: already stopped
```

**Comment by chipweinberger** [comment]
**Pin input not showing when i try to connect for IOS,**

iOS handles this automatically. there is nothing FPB can do.
