### ISSUE TITLE
I connect my smart watch(boat) only getting 3 service like start with 1801,1800,f618 

### ISSUE THREAD

**Issue by krupalieBizTrait** [boskokg/flutter_blue_plus#897]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.7

### Flutter Version

3.16.5

### What OS?

iOS

### OS Version

14.3.1

### Bluetooth Module

Smart watch

### What is your problem?

I connect my smart watch(boat) only getting 3 service like start with 1801,1800,f618 
bcz of i need sleep data ,heart rate data all health related data i required

### Logs

```shell
I getting only this 3starting with UUID 

UUID.........1801
UUID.........1800
UUID.........f618
```

**Comment by chipweinberger** [comment]
you should contact the manufacturer of your smart watch. 

There is nothing FBP can do.
