### ISSUE TITLE
bondedDevices isConnected

### ISSUE THREAD

**Issue by save-us-prophet** [boskokg/flutter_blue_plus#898]
### FlutterBluePlus Version

1.32.7

### Flutter Version

3.19.6

### What OS?

Android

### OS Version

android 12

### Bluetooth Module

Exynos

### What is your feature request?

```dart
FlutterBluePlus.bondedDevices.then((bondedDevices) {
      for (final device in bondedDevices) {
        print(device.isConnected);
      }
    });
```

All connected devices also return **FALSE**.

### Logs

```shell
FlutterBluePlus.bondedDevices.then((bondedDevices) {
      for (final device in bondedDevices) {
        print(device.isConnected);
      }
    });
```

**Comment by chipweinberger** [comment]
you can be bonded but not connected 

bonded just means "previously paired"

**Comment by save-us-prophet** [comment]
```kotlin
fun isConnected(device: BluetoothDevice): Boolean {
        return try {
            val method = device.javaClass.getMethod("isConnected")
            method.invoke(device) as Boolean
        } catch (e: Exception) {
            throw IllegalStateException(e)
        }
    }
```
It would be nice to have a function that could check the connection status.

What do you think?

**Comment by chipweinberger** [comment]
i dont understand

**Comment by efraespada** [comment]
@save-us-prophet is talking about the connection with the system, not the app.

This method access to the private field `isConnected` which allows to know if a BT device is connected to the smartphone: 

```kotlin
fun isConnected(device: BluetoothDevice): Boolean {
        return try {
            val method = device.javaClass.getMethod("isConnected")
            method.invoke(device) as Boolean
        } catch (e: Exception) {
            throw IllegalStateException(e)
        }
    }
```

I think it is not implemented in this library. Sadly 😞
