### ISSUE TITLE
how to initialize ScanResults?

### ISSUE THREAD

**Issue by kindkmj** [boskokg/flutter_blue_plus#9]
Whenever Bluetooth scans are performed, they are accumulating in ScanResults.
However, ScanResults is not initialized and data continues to accumulate.

How can we initialize ScanResults' data and accumulate only new data?

**Comment by WeiKuang** [comment]
// Start scanning
flutterBlue.startScan(timeout: Duration(seconds: 4));

// add this line code
await Future.delayed(const Duration(milliseconds: 200));

// Listen to scan results
var subscription = flutterBlue.scanResults.listen((results) {
    // do something with scan results
    for (ScanResult r in results) {
        print('${r.device.name} found! rssi: ${r.rssi}');
    }
});

// Stop scanning
flutterBlue.stopScan();
