### ISSUE TITLE
[Feature]: refactor code：An additional colon is added

### ISSUE THREAD

**Issue by LeoAiolia** [boskokg/flutter_blue_plus#904]
### FlutterBluePlus Version

1.32.7

### Flutter Version

null

### What OS?

Android

### OS Version

null

### Bluetooth Module

null

### What is your feature request?

![image](https://github.com/boskokg/flutter_blue_plus/assets/16910025/1f472fc9-36d5-4f41-bffb-e714ac0e01c1)
An additional colon is added

### Logs

```shell
None
```

**Comment by LeoAiolia** [comment]
An additional colon is added here, it is recommended to remove it

**Comment by chipweinberger** [comment]
fixed 68a36c6969c701c799f665b252c698fa38bb3978
