### ISSUE TITLE
[Help]: 2 Bytes missing in advertisementData.manufacturerData

### ISSUE THREAD

**Issue by kle-wang** [boskokg/flutter_blue_plus#907]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.7

### Flutter Version

3

### What OS?

Android, iOS

### OS Version

android 12

### Bluetooth Module

headphones

### What is your problem?

link to: https://github.com/pauldemarco/flutter_blue/issues/102
2 Bytes missing in advertisementData.manufacturerData
because of my device detect by using manufacturerData. if i lost 2 Bytes,i can not discover my device correct.
could any way to slove it.i want to get the begin 2 bytes data.

### Logs

```shell
full :【82,83,0,1,0,1,0,11,1,100,0,209,2,3,4,5,161】
      【~~,~~,0, 1, 0, 1, 0, 11, 1, 100, 0, 209, 2, 3, 4, 5, 161】
```

**Comment by chipweinberger** [comment]
the first two bytes are the key of the map.

i.e. manufacturer id
