### ISSUE TITLE
[Help]: Is there a method to obtain the connected classic Bluetooth in the system？

### ISSUE THREAD

**Issue by kle-wang** [boskokg/flutter_blue_plus#908]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.7

### Flutter Version

3.22.1

### What OS?

Android, iOS

### OS Version

17.5.1

### Bluetooth Module

headphone

### What is your problem?

Is there a method to obtain the connected classic Bluetooth in the system and try to connect to the ble connection corresponding to this classic Bluetooth.
Is there a method to obtain the connected classic Bluetooth in the system and try to connect to the ble connection corresponding to this classic Bluetooth

### Logs

```shell
no logs
```

**Comment by chipweinberger** [comment]
no.

ble only.
