### ISSUE TITLE
[Feature]: Ability to check if its bluetooth 5 or not.

### ISSUE THREAD

**Issue by cimplesid-tekkon** [boskokg/flutter_blue_plus#918]
### FlutterBluePlus Version

latest

### Flutter Version

latest

### What OS?

All

### OS Version

latest

### Bluetooth Module

bluetooth 5

### What is your feature request?

Ability to check if its bluetooth 5 or not.Since isLe2MPhySupport is only from Bluetooth 5

### Logs

```shell
no logs
```

**Comment by chipweinberger** [comment]
not possible.

if you know of an api, let me know

but there is no api for this afaik

**Comment by chipweinberger** [comment]
but we already have code to get phy support

FlutterBluePlus.getSupportedPhy

**Comment by cimplesid-tekkon** [comment]
> but we already have code to get phy support
> 
> FlutterBluePlus.getPhySupport

do we also have the `isLeCodedPhySupported` , `isLeExtendedAdvertisingSupported` ,  .isLePeriodicAdvertisingSupported'?

**Comment by chipweinberger** [comment]
The code is open source

Please be self reliant and answer your own simple questions

**Comment by sqcsabbey** [comment]
@chipweinberger Doesn't look like isLeExtendedAdvertisingSupported et al are supported; would you be interested in a PR with that?
