### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by zhouhouwen** [boskokg/flutter_blue_plus#919]
### FlutterBluePlus Version

1.31.7

### Flutter Version

3.13.6

### What OS?

All

### OS Version

12

### Bluetooth Module

eps32-c3

### What is your feature request?

![1719570143239](https://github.com/boskokg/flutter_blue_plus/assets/18208207/e43c3f6b-6999-43a6-95de-47fc02e67909)
![WechatIMG1361](https://github.com/boskokg/flutter_blue_plus/assets/18208207/3e71b451-631c-4993-aa3d-d197883b1147)
Why can't you see the byte 0xff on AdvertisementData

### Logs

```shell
1
```

**Comment by chipweinberger** [comment]
we dont show that byte. it can be assumed.
