### ISSUE TITLE
[Help]: Bonding on IOS necessary

### ISSUE THREAD

**Issue by simiii** [boskokg/flutter_blue_plus#926]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.4

### Flutter Version

>=3.3.4 <4.0.0

### What OS?

iOS

### OS Version

iOS 17.5.1

### Bluetooth Module

custom

### What is your problem?

I need to bond a device with ble on iOS because the device refuses to keep the connection without bonding. What would be the best way to bond a device from an app using this library to ensure the user performs the bonding with the device?

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
FPB does not control bonding on iOS.

please file an issue with Apple support.
