### ISSUE TITLE
[Help]: Android: Race condition between disconnect and connect leaves connection stranded

### ISSUE THREAD

**Issue by jasaw** [boskokg/flutter_blue_plus#927]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.32.8

### Flutter Version

3.22.2

### What OS?

Android

### OS Version

7 & 14

### Bluetooth Module

Nordic nRF

### What is your problem?

Sometimes calling `bluetoothDevice.connect(autoConnect: false)` then shortly after (around 500ms), calling `bluetoothDevice.disconnect(queue: false)` does not cancel the connect call, but FBP thinks that there's no active Bluetooth connection. `bluetoothDevice.isDisconnected` returns true. This leaves the active Bluetooth connection stranded because calling `bluetoothDevice.disconnect(queue: false)` does nothing.

Sometimes FBP throws this exception `FlutterBluePlusException | connect | fbp-code: 10 | connection canceled`, sometimes it doesn't, but regardless of the exception, the outcome is the same, stranded Bluetooth connection.

### Logs

```shell
D/[FBP-Android](32473): [FBP] onMethodCall: connect
D/BluetoothGatt(32473): connect() - device: DA:71:BA:6D:29:3B, auto: false
D/BluetoothAdapter(32473): isSecureModeEnabled
D/BluetoothGatt(32473): registerApp()
D/BluetoothGatt(32473): registerApp() - UUID=bcf24f3c-294a-473c-abe9-c78b490a8d23
D/BluetoothGatt(32473): onClientRegistered() - status=0 clientIf=7
I/flutter (32473): 0:01:06.344230	I	Device:	 Disconnecting Bluetooth connection
D/[FBP-Android](32473): [FBP] onMethodCall: disconnect
I/flutter (32473): 0:01:06.346947	D	Device:	 BLE device disconnected
D/[FBP-Android](32473): [FBP] disconnect: cancelling connection in progress
D/BluetoothGatt(32473): cancelOpen() - device: DA:71:BA:6D:29:3B
I/flutter (32473): 0:01:06.347598	W	Device:	 Bluetooth device isDisconnected: true
D/BluetoothGatt(32473): close()
D/BluetoothGatt(32473): unregisterApp() - mClientIf=7
I/flutter (32473): 0:01:06.419830	W	Device:	 Disconnecting Bluetooth connection again
D/[FBP-Android](32473): [FBP] onMethodCall: disconnect
D/[FBP-Android](32473): [FBP] already disconnected
*** Bluetooth connection is still active at this point ***
```

**Comment by chipweinberger** [comment]
Your logs dont show any problem?

"disconnect: cancelling connection in progress" - seems like it worked as expected.

"*** Bluetooth connection is still active at this point ***" - the logs show it never connected.

**Comment by jasaw** [comment]
The logs show Bluetooth connection was cancelled but did not pick up on the connection established event that happened right after the cancellation. That is why the Bluetooth connection is stranded; I can't disconnect a connection if FBP thinks that there's no connection.

I can reliably reproduce this on Android 7 and 14.

**Comment by chipweinberger** [comment]
i'm confused. how do you know the connection occurred if it's not in the logs

please show complete logs

**Comment by chipweinberger** [comment]
if the connection is not in the logs, then android does not think it happened either

and then you will have to file issue with google/android

**Comment by jasaw** [comment]
My Bluetooth device turns on blue led when there is a connection. That's how I know.

**Comment by chipweinberger** [comment]
seems like a problem with android.

**Comment by chipweinberger** [comment]
you can try deleting these lines

```
                    if (gatt == null) {
                        log(LogLevel.DEBUG, "already disconnected");
                        result.success(false);  // no work to do
                        return;
                    }
```

maybe try deleting this too, line 770

```
                        // cleanup
                        gatt.close();
```

But I dont see those as a proper fix even if they did work.

**Comment by chipweinberger** [comment]
closing. I don't think this is a issue in FBP

If im wrong, please open PR

**Comment by jasaw** [comment]
@chipweinberger 
Just for completeness, it is indeed a bug in Android and Google refuses to fix it.
https://issuetracker.google.com/issues/37121040
I just have my app enforce a 2 second gap between connect and disconnect. I tried 1 second gap and that's not enough.

**Comment by chipweinberger** [comment]
thanks for sharing this. very appreciated.

**Comment by chipweinberger** [comment]
perhaps we should enforce this 2 delay in FBP as well

**Comment by chipweinberger** [comment]
@jasaw, if you could open a PR to fix this, that would be great.

I think it's easiest to fix on the Dart side

just save the most recent time we call "connect" in a map

and if we call disconnect within 2 seconds, add a delay for android devices with a log that says we are enforcing a delay.

**Comment by jasaw** [comment]
@chipweinberger I've been testing this and observed another scenario where the race condition between Android `gatt.close()` and the stack establishing Bluetooth connection causing `onConnectionStateChange:connected` to be triggered. See the logs below. In this case, the app can disconnect the connection if the app is aware of it. The proper fix for this race condition is to add the closed Gatt device to map and auto disconnect it if it gets connected later in the `onConnectionStateChange` callback.

Thoughts?


```
D/[FBP-Android](30007): [FBP] onMethodCall: connect
D/BluetoothAdapter(30007): getBleEnabledArray(): ON
D/BluetoothGatt(30007): connect() - device: XX:XX:XX:XX:8A:77, auto: false
D/BluetoothGatt(30007): registerApp()
D/BluetoothGatt(30007): registerApp() - UUID=f06d1d8e-06a2-4466-9beb-a9dbe69aca7f
D/BluetoothGatt(30007): onClientRegistered() - status=0 clientIf=8
D/BluetoothAdapter(30007): getBleEnabledArray(): ON
I/flutter (30007): 0:00:50.491900	I	Device:	 Disconnecting Bluetooth connection
D/[FBP-Android](30007): [FBP] onMethodCall: disconnect
D/[FBP-Android](30007): [FBP] disconnect: cancelling connection in progress
D/BluetoothGatt(30007): cancelOpen() - device: XX:XX:XX:XX:8A:77
D/BluetoothGatt(30007): close()
D/BluetoothGatt(30007): onClientConnectionState() - status=0 clientIf=8 device=XX:XX:XX:XX:8A:77
D/[FBP-Android](30007): [FBP] onConnectionStateChange:connected
D/[FBP-Android](30007): [FBP]   status: SUCCESS
D/BluetoothGatt(30007): unregisterApp() - mClientIf=8
D/[FBP-Android](30007): [FBP] onMethodCall: requestMtu
D/BluetoothGatt(30007): configureMTU() - device: XX:XX:XX:XX:8A:77 mtu: 512
```

**Comment by chipweinberger** [comment]
I think we can just add a ~2 second delay like you suggested.

**Comment by jasaw** [comment]
@chipweinberger The issue I reported 4 hours ago is actually a different Android bug. I'll create a new issue.

**Comment by chipweinberger** [comment]
merged https://github.com/boskokg/flutter_blue_plus/pull/933
