### ISSUE TITLE
[Help]: Scanning devices in the background finds none

### ISSUE THREAD

**Issue by franciscogodoy97** [boskokg/flutter_blue_plus#929]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

^1.32.7

### Flutter Version

3.19.6

### What OS?

Android, iOS

### OS Version

17.5.1

### Bluetooth Module

Bluetooth 5.0 anti-loss device

### What is your problem?

When the app is in the foreground, it scans normally, finds the devices and everything, but when it goes into the background, it scans but returns an empty device list. However, when the app comes back to the foreground, it immediately finds the device.

### Logs

```shell
foreground:
result: \^[[1;33m{advertisements: [{manufacturer_data: {261: ff24032004a16602010300}, service_uuids: [ffe0], rssi: -89, remote_id: 973252A1-F949-6787-F7EA-74E72DF32F11, platform_name: iTAG            , connectable: 1, adv_name: iTAG            }<…>

background:
<startScan>\^[[0m args: \^[[1;35m{with_services: [ffe0], with_remote_ids: [], with_names: [], with_keywords: [iTAG], with_msd: [], with_service_data: [], continuous_updates: false, continuous_divisor: 1, android_scan_mode: 2, android_uses_fine_location: fals<…>
```

**Comment by chipweinberger** [comment]
https://github.com/boskokg/flutter_blue_plus/issues/846
