### ISSUE TITLE
[Help]: Is there a way to dynamically know how many concurrent ble connections are possible on android/iOS device?

### ISSUE THREAD

**Issue by kaciula** [boskokg/flutter_blue_plus#931]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.7

### Flutter Version

3.22.2

### What OS?

Android, iOS

### OS Version

-

### Bluetooth Module

-

### What is your problem?

I want to know how many concurrent ble connections I can do. For instance, a user may have 10 sensors that needs syncing and I want to know how many syncs I can run in parallel. Can this be achieved somehow? Or, are there at least some specifications on the maximum allowed ble connections per device?

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
about 6.
