### ISSUE TITLE
[Feature]: Minimum RSSI level for auto connect

### ISSUE THREAD

**Issue by stam0912** [boskokg/flutter_blue_plus#937]
### FlutterBluePlus Version

1.32.8

### Flutter Version

3.19.6

### What OS?

Android, iOS

### OS Version

iOS 17.5.1, Android 14

### Bluetooth Module

Silicon Labs MGM240SD22VNA

### What is your feature request?

It would be nice if we can set the minimum RSSI for auto connect. 

We want our users to be able to connect to our BLE device only if they are close enough. Our BLE device terminates the connection after a certain period of time in order to reduce power consumption. Ideally, it will stay disconnected until the user gets close to the BLE device, then it'll auto connect. Right now the phone just keeps auto connecting to the BLE device after the connection timed out. We can increase the battery life if we can set the minimum RSSI level for auto connect.

### Logs

```shell
N/A
```

**Comment by chipweinberger** [comment]
not possible. you'll need to implement this yourself.
