### ISSUE TITLE
When I use my iPhone 15 to scan Bluetooth, I cannot detect the device's Bluetooth

### ISSUE THREAD

**Issue by jyljames** [boskokg/flutter_blue_plus#942]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.6

### Flutter Version

3.17

### What OS?

iOS

### OS Version

17.5.1

### Bluetooth Module

aic8800m40

### What is your problem?

When I use my iPhone 15 to scan Bluetooth, I cannot detect the device's Bluetooth, which is an inevitable phenomenon. After checking the logs, I found that the information scanned seems to be somewhat incorrect. This is a screenshot of the log
![75ACD961-E07F-4bc5-B3D4-40FDEDBFE7A0](https://github.com/user-attachments/assets/4b76888e-1c21-4d8e-9fb5-050bcf8bacc1)
Afterwards, I checked the logs using a device that could scan them normally, and I found that the logs of the two were different. Below are the logs that can scan the device normally

![B2FA45AC-EC40-40b5-A033-F784EC92B16B](https://github.com/user-attachments/assets/f89d761d-0e12-4ec9-b2d6-e91e21dd78e2)

### Logs

```shell
log pasted on problem
```

**Comment by chipweinberger** [comment]
this is expected.

**Comment by jyljames** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jyljames** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jyljames** [comment]
What kind of situation can cause the scanned result to be the same as the first image?
