### ISSUE TITLE
Add this android pairing solution

### ISSUE THREAD

**Issue by itamardo** [boskokg/flutter_blue_plus#95]
Currently, the only way to create a pairing request and show the pairing dialog in Android is to connect and try to use the characteristic which is a bit awkward and takes a bit of time. There's already a nice solution by Rexio80 in the flutter_blue repo.

Can you please add this solution by Rexios80 to flutter_blue_plus?
Locally it seems to work nicely, shows the pairing dialog immediately and simplifies the whole pairing/connection process.

https://github.com/pauldemarco/flutter_blue/pull/906

It's just 3 very small additions to 
flutter_blue_plus.dart
bluetooth_device.dart
FlutterBluePlusPlugin.java

Thanks

**Comment by boskokg** [comment]
Thank you commited

**Comment by itamardo** [comment]
Thanks!
