### ISSUE TITLE
[Feature]: read/write/notify value as raw bytes

### ISSUE THREAD

**Issue by boborua** [boskokg/flutter_blue_plus#954]
### FlutterBluePlus Version

1.12.7

### Flutter Version

3.13.9

### What OS?

Android, iOS

### OS Version

iOS 17 / Android 33

### Bluetooth Module

*

### What is your feature request?

It is limited from the type of api arguments when we use blue_pluse reading/writing value, for example write(List<int> value) on a Charateristic.

After having done some research in the repository, I found that in Android platform, data was received in byte[] format (Java side) and encoded to hex string to pass to the dart side.

Is it possible that we can write and read value in Uint8Array/List<Uint8>...etc 

### Logs

```shell
no logs
```

**Comment by chipweinberger** [comment]
not possible.
