### ISSUE TITLE
[Help]: Problems when using with "flutter_ble_peripheral" packge

### ISSUE THREAD

**Issue by snkcrumbs** [boskokg/flutter_blue_plus#957]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.32.11

### Flutter Version

3.22.2

### What OS?

Android

### OS Version

Android U(14)

### Bluetooth Module

I do not know h/w info

### What is your problem?

We are developing an app that scans the device's advertising data and then advertises with the promised data.

This feature was created as an Android native app and worked normally, and we are currently working on converting it to Flutter.

Since this package does not have a "peripheral" function, the ["flutter_ble_peripheral" ](https://pub.dev/packages/flutter_ble_peripheral) package is also used.

The device is using our own BLE device.

It scanned normally until peripheral functions were added.

However, as mentioned, if we add the "flutter_ble_peripheral(1.2.5)" package to the dependency, our device will not be scanned immediately.

After adding it to the dependency, I only performed pub get and did not do any coding.

Scan results from other devices are reported normally.

Are there any cases like this?

### Logs

```shell
This is an exclusion phenomenon from the scan result, not a package error.
No meaningful logs found.
```

**Comment by chipweinberger** [comment]
nothing we can do to fix it

try different ble package
