### ISSUE TITLE
[Help]: Bluetooth device shows up in iOS "Other Devices" but not through FlutterBluePlus

### ISSUE THREAD

**Issue by ryanpager** [boskokg/flutter_blue_plus#960]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.8

### Flutter Version

3.22.2

### What OS?

iOS

### OS Version

17.5.1

### Bluetooth Module

Not Sure

### What is your problem?

So I am trying to pair to an RFID reader that I have. (Gallagher HR5).

I've tried 2 things,

1. Scanning for devices (works)
2. Trying to pair through iOS system devices

The HR5 device shows up in the system bluetooth settings on my iOS device (as HR5) -- but it is not recognized inside of the application or through the FlutterBluePlus.systemDevices pointer.

Is there something else I can try in order to get this to work?

### Logs

```shell
No error logs available; it works completely fine, it just doesnt find the device.
```

**Comment by chipweinberger** [comment]
maybe it uses bluetooth classic?

this is controller by apple, not us
