### ISSUE TITLE
[Feature]:  Refresh cache without connected

### ISSUE THREAD

**Issue by AdemYavuzCelik** [boskokg/flutter_blue_plus#961]
### FlutterBluePlus Version

1.32.11

### Flutter Version

3.22.2

### What OS?

Android

### OS Version

14 

### Bluetooth Module

-

### What is your feature request?

I'm establishing a secure connection with a device that has an ESP module. After disconnecting and reconnecting, I encounter an error 61 (mic_failure). This issue also occurs in your sample application, but I do not experience it on Samsung, Xiaomi, or OnePlus devices—only on the Pixel devices (Pixel 6 , Pixel 7 tested). There's an NRF Connect app where I faced the same issue, but when I refresh the device cache without connecting, the connection can be established. If you could implement a 'refresh device cache' without connecting, it might solve the problem on the Pixel devices.".

### Logs

```shell
-
```

**Comment by chipweinberger** [comment]
if you want this feature, please open a PR

Otherwise, I will close this issue
