### ISSUE TITLE
[Help]: Samsung mobile phone

### ISSUE THREAD

**Issue by xcjpdx** [boskokg/flutter_blue_plus#965]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.7

### Flutter Version

3.22.3

### What OS?

Android

### OS Version

Android 13

### Bluetooth Module

systemDevices

### What is your problem?

三星s20设备，安卓版本是13。
我使用国行版调用**FlutterBluePlus.systemDevices**可以获取到当前设备连接到的蓝牙设备。
当我使用美版调用**FlutterBluePlus.systemDevices**就无法获取到当前设备连接到的蓝牙设备。

Samsung S20 device, Android version is 13.
I can use the Chinese version to call **FlutterBluePlus.systemDevices** to obtain the Bluetooth device connected to the current device.
When I use the US version to call **FlutterBluePlus.systemDevices**, I cannot obtain the Bluetooth device that the current device is connected to.

### Logs

```shell
null
```

**Comment by chipweinberger** [comment]
This is a common problem.

I do not the the reason. OS problem.
