### ISSUE TITLE
[Help]: BluetoothDevice.fromProto::platformName

### ISSUE THREAD

**Issue by nissaba** [boskokg/flutter_blue_plus#968]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

ANY

### Flutter Version

3.24.0

### What OS?

Android

### OS Version

androïde 14

### Bluetooth Module

Android pixel 6 

### What is your problem?

when I create a instance of a saved device using 
```
savedDevice = BluetoothDevice.fromProto(BmBluetoothDevice(
          remoteId: DeviceIdentifier(savedId), platformName: savedName));
```

The savedDevice instance in the debugger reads as such 
`BluetoothDevice{remoteId: CC:16:AC:B1:8A:9B, platformName: , services: null}`

it is not saving the name I gave it. 

I was expecting it to be like this `BluetoothDevice{remoteId: CC:16:AC:B1:8A:9B, platformName: deviceNameFromFile, services: null}`

### Logs

```shell
No logs are emited related to this, I have this at the start of the app so the only thing I get are fairebase stuff and app build /. installation. no error where outputed to the console.
```

**Comment by chipweinberger** [comment]
don't use fromProto

just use withIdentifier or whatever it is called
