### ISSUE TITLE
running app on real iphone device problem

### ISSUE THREAD

**Issue by abdelrahman-abied** [boskokg/flutter_blue_plus#97]
/projects/bluetooth_reader/ios/Pods/Pods.xcodeproj The file "flutter_blue.release.xcconfig" couldn’t be opened because its path couldn't be resolved.  It may be missing.

**Comment by boskokg** [comment]
@abdelrahman-abied there are many similar problems related to this already reported and resolved. Please check them (also check fluter_blue issues). Closing
