### ISSUE TITLE
[Help]: Can't parse the key bytes from advertisementData.manufacturerData

### ISSUE THREAD

**Issue by xOldeVx** [boskokg/flutter_blue_plus#970]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

5.3.1

### Flutter Version

3.22.1

### What OS?

Android

### OS Version

14

### Bluetooth Module

Nordic nRF52

### What is your problem?

I moving my code from `flutter_reactive_ble` to this package, in `flutter_reactive_ble` I could get the _device-id_ in one simple variable, in this package i noticed that the _device-id_ is live in a `Map manufacturerData`, the first 2 bytes is in the `key` and the rest (6 bytes in my case) is in the `value`, however I couldn't to parse the 2 first bytes correctly, instead of getting _L2_ I'm getting _㉌_ symbol.

Here's my result:
![Screenshot 2024-08-18 at 12 19 50](https://github.com/user-attachments/assets/45478fca-a486-47ee-a4bd-6a9c91905660)

I would like to know how to parse it to correct String.

By the way it can be very useful to combine it in the package side like in flutter_reactive_ble.
![reactive_ble](https://github.com/user-attachments/assets/988bbd16-0c12-405c-aff1-b78e832f1158)

### Logs

```shell
Above
```

**Comment by chipweinberger** [comment]
the two bytes are probably reversed from what you expect.

**Comment by chipweinberger** [comment]
or use AdvertisementData.msd
